### ISSUE TITLE
vercel部署失败[Bug] 

### ISSUE THREAD

**Issue by xfxx2022** [lobehub/lobe-chat#1037]
### 💻 系统环境

Windows

### 📦 部署环境

Official Preview

### 🌐 浏览器

Chrome

### 🐛 问题描述

![微信截图_20240113120051](https://github.com/lobehub/lobe-chat/assets/25678988/be7e6093-5a78-4060-87dd-02ce9a2314d4)

### 📷 复现步骤

```
<html>
<body>
<!--StartFragment-->
RangeError: Maximum call stack size exceeded
--
11:58:43.681 | at parse (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:6313)
11:58:43.681 | at picomatch.makeRe (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:21670)
11:58:43.681 | at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19637)
11:58:43.681 | at /vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19294
11:58:43.681 | at Array.map (<anonymous>)
11:58:43.681 | at picomatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:19286)
11:58:43.681 | at micromatch.isMatch (/vercel/path0/node_modules/next/dist/compiled/micromatch/index.js:15:1090)
11:58:43.681 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:245:48
11:58:43.682 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:75:9)
11:58:43.682 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.682 | at Array.every (<anonymous>)
11:58:43.682 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.682 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.682 | at Array.every (<anonymous>)
11:58:43.682 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.682 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.682 | at Array.every (<anonymous>)
11:58:43.682 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.682 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.682 | at Array.every (<anonymous>)
11:58:43.682 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.682 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.682 | at Array.every (<anonymous>)
11:58:43.682 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.682 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.682 | at Array.every (<anonymous>)
11:58:43.682 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.682 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.683 | at Array.every (<anonymous>)
11:58:43.683 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.683 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.683 | at Array.every (<anonymous>)
11:58:43.683 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.683 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.683 | at Array.every (<anonymous>)
11:58:43.683 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.683 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.683 | at Array.every (<anonymous>)
11:58:43.683 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.683 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.683 | at Array.every (<anonymous>)
11:58:43.683 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.683 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.683 | at Array.every (<anonymous>)
11:58:43.683 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.683 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.683 | at Array.every (<anonymous>)
11:58:43.683 | at shouldIgnore (/vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:7)
11:58:43.683 | at /vercel/path0/node_modules/next/dist/build/collect-build-traces.js:86:23
11:58:43.683 | at Array.every (<anonymous>)
11:58:43.828 | error: script "build" exited with code 1
11:58:43.832 | Error: Command "bun run build" exited with 1

<!--EndFragment-->
</body>
</html>
```

**Comment by arvinxx** [comment]
已知问题，应该是 vercel 平台的部署脚本问题，他们应该在修复了，稍等一段时间吧

**Comment by sunsky89757** [comment]
[v0.119.13](https://github.com/lobehub/lobe-chat/releases/tag/v0.119.13) 此版本vercel部署失败。
![image](https://github.com/lobehub/lobe-chat/assets/113254524/8e438e6f-d6ef-465b-ae78-2305e36b18ae)

**Comment by arvinxx** [comment]
@sunsky89757 @xfxx2022 请同步下再部署试试，应该可以了。

**Comment by Edjhernandez** [comment]
I have the same problem

![image](https://github.com/lobehub/lobe-chat/assets/109191350/69217d23-67f5-4082-bf94-2388b4037356)

**Comment by arvinxx** [comment]
@Edjhernandez  please sync with latest code

**Comment by Edjhernandez** [comment]
sorry about that, but, how can I sure to sync with last code

**Comment by arvinxx** [comment]
@Edjhernandez 

<img width="1391" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/7ec8b1eb-245e-4823-a1de-ee4553b338a2">
