### ISSUE TITLE
[Request] 大神門能支持一下copilot-gpt4-service 嗎?

### ISSUE THREAD

**Issue by hephaestus369** [lobehub/lobe-chat#1093]
### 🥰 Feature Description

大神門能加入連接copilot-gpt4-service 嗎?

### 🧐 Proposed Solution

大神門能支持一下copilot-gpt4-service 嗎?
https://github.com/aaamoon/copilot-gpt4-service
localhost:8080
加個自訂API或地址localhost:8080 連接copilot-gpt4-service 或本地LLM
謝謝

**Comment by arvinxx** [comment]
具体需要做什么事情

**Comment by usefortemp** [comment]
使用copilot-gpt4-service会报错
{
  "endpoint": "http://copilot-gpt4-service:****/",
  "error": {
    "headers": {
      "access-control-allow-credentials": "true",
      "access-control-allow-headers": "*",
      "access-control-allow-methods": "*",
      "access-control-allow-origin": "*",
      "content-length": "18",
      "content-type": "text/plain; charset=utf-8",
      "date": "***"
    },
    "stack": "Error: 405 Method Not Allowed\n    at W.generate (/app/.next/server/app/api/openai/chat/route.js:22:1855)\n    at tD.makeStatusError (/app/.next/server/app/api/openai/chat/route.js:22:13240)\n    at tD.makeRequest (/app/.next/server/app/api/openai/chat/route.js:22:13970)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async $ (/app/.next/server/app/api/openai/chat/route.js:2:2906)\n    at async /app/.next/server/app/api/openai/chat/route.js:7:64719\n    at async Y.execute (/app/.next/server/app/api/openai/chat/route.js:7:61612)\n    at async Y.handle (/app/.next/server/app/api/openai/chat/route.js:7:65986)\n    at async eC.handler (/app/.next/server/app/api/openai/chat/route.js:19:34582)\n    at async H (/app/.next/server/app/api/openai/chat/route.js:19:6577)",
    "status": 405
  }
}

**Comment by Hurray0** [comment]
本来就支持吧？设置好docker的环境变量就可以用了
具体是
OPENAI_PROXY_URL设为[url]/v1
OPENAI_API_KEY设为ghu_xxxxx

**Comment by pzcn** [comment]
本来就是支持的
