### ISSUE TITLE
[Bug] Uncaught TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by KnaveM** [lobehub/lobe-chat#1227]
### 💻 Operating System

macOS

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

Can not send chat message to backend

<img width="1032" alt="image" src="https://github.com/lobehub/lobe-chat/assets/33738071/abd93a72-1aaa-402b-9721-1c571fc4f718">

Chrome console logs:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'digest')
    at v (9345-86554b7ca9bee849.js:1:1410)
    at w (9345-86554b7ca9bee849.js:1:2426)
    at A (9345-86554b7ca9bee849.js:1:2583)
    at L.getChatCompletion (9345-86554b7ca9bee849.js:1:3198)
    at L.createAssistantMessage (9345-86554b7ca9bee849.js:1:3006)
    at 14971-b0b20396474da198.js:1:24196
    at r (9345-86554b7ca9bee849.js:1:33874)
    at fetchAIChatMessage (14971-b0b20396474da198.js:1:24187)
    at coreProcessMessage (14971-b0b20396474da198.js:1:23075)
    at async resendMessage (14971-b0b20396474da198.js:1:21476)
3156a9d61-1dd9c2fef065b30d.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'getUserMedia')
    at 81357-7fd7057b085ed47c.js:1:14660
    at 81357-7fd7057b085ed47c.js:1:24227
    at 81357-7fd7057b085ed47c.js:1:18994
    at Object.onClick (58760-b42e0d94977f4ee2.js:1:14465)
    at e5.onClick (92978-cf85e4c3d6274a1b.js:1:19885)
    at Object.aS (156a9d61-1dd9c2fef065b30d.js:1:71762)
    at aN (156a9d61-1dd9c2fef065b30d.js:1:71916)
    at 156a9d61-1dd9c2fef065b30d.js:1:138577
    at sw (156a9d61-1dd9c2fef065b30d.js:1:138676)
    at sS (156a9d61-1dd9c2fef065b30d.js:1:139090)
```

**Comment by arvinxx** [comment]
how to reproduce?

**Comment by KnaveM** [comment]
Command that I used to create the lobe-chat service
```shell
docker run -d -p 3210:3210 \
  -e OPENAI_API_KEY=`cat /path/to/openai_api_key` \
  -e ACCESS_CODE=lobe66 \
  --name lobe-chat \
  lobehub/lobe-chat:v0.123.0
```

**Comment by arvinxx** [comment]
can you reproduce it with `https://chat-preview.lobehub.com/` ?

**Comment by arvinxx** [comment]
can you try this code in your deployment? maybe it's a issue of Web Crypto API missing

```js
if (window.crypto && window.crypto.subtle) {
  console.log("Web Crypto API is available.");
} else {
  console.log("Web Crypto API is not available.");
}
```

**Comment by KnaveM** [comment]
`Web Crypto API is not available.` from console log

Is it related to HTTPS?

**Comment by arvinxx** [comment]
@KnaveM it seems true. Maybe i need to find someway to fix it.

**Comment by zhendery** [comment]
same as u

**Comment by yunzhuqing** [comment]
i run the same question

![image](https://github.com/lobehub/lobe-chat/assets/19723491/3a7c99a3-4fcb-45d9-8536-d349fe76b71e)

![image](https://github.com/lobehub/lobe-chat/assets/19723491/a7de6e39-1593-4348-a9ed-89916a99d617)

**Comment by skywolf123** [comment]
是的，我也是docker安装的，v0.123.0之后的版本都不能发消息了，回退到v0.122.9可以
