### ISSUE TITLE
[Bug] OAuth throws an error

### ISSUE THREAD

**Issue by gijigae** [lobehub/lobe-chat#1274]
### 💻 Operating System

Ubuntu

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

Thank you so much for merging #1143 ! 

![image](https://github.com/lobehub/lobe-chat/assets/81459/b6b0e4b1-a523-47a1-9a9a-ba4f0014fad3)

Upon clicking on the "SSO Login" button, the app returns the following error message.

"Error: This action with HTTP GET is not supported."

Here is the error logs captured in Vercel. 

    [31m [auth][error] [0m UnknownAction: Cannot parse action at /api/oauth/session .Read more at https://errors.authjs.dev#unknownaction
    at (node_modules/@auth/core/lib/utils/web.js:90:14)
    at (node_modules/@auth/core/lib/utils/web.js:23:64)
    at (node_modules/@auth/core/index.js:67:34)
    at (node_modules/next-auth/index.js:128:33)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:189:42)
    at (node_modules/next/dist/esm/server/lib/trace/tracer.js:107:35)
    at (node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:7061)
    at (node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:518)
    at (node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18093)
    at (node_modules/next/dist/compiled/@opentelemetry/api/index.js:1:18853)

![image](https://github.com/lobehub/lobe-chat/assets/81459/3325307a-95bd-4daf-8093-d43f2d06f682)

All the necessary environment variables have been setup in Vercel. Am I missing something here?

![image](https://github.com/lobehub/lobe-chat/assets/81459/863ecd5d-d352-4c4d-9fdd-149b45219547)

### 🚦 Expected Behavior

Upon clicking on the SSO Login button, the app should route the user to a page where he/she can enter email and password to login.

**Comment by arvinxx** [comment]
@CloudPassenger please help to check this issue.

**Comment by CloudPassenger** [comment]
I am investigating this issue. Please bear with me and I will resolve this ASAP.

**Comment by CloudPassenger** [comment]
Thanks for your feedback. I opened a [pull request](https://github.com/lobehub/lobe-chat/pull/1277) to fix the issue you mentioned.

**Comment by gijigae** [comment]
Thanks @arvinxx for tagging the issue! @CloudPassenger , really appreciate the prompt response 👍 . I'm testing the branch and confirmed the initial issue that I reported got fixed. I have one more question, though. For the Allowed Callback URLs, what would be appropriate values?

![image](https://github.com/lobehub/lobe-chat/assets/81459/11919169-06a8-455a-969f-9c40e4698460)

**Comment by gijigae** [comment]
Thank you both of you (@arvinxx and @CloudPassenger) for the fix and thorough documentation! Was able to login with the callback path provided in the document.
