### ISSUE TITLE
[Bug] 显示ConnectTimeoutError，应该如何解决

### ISSUE THREAD

**Issue by atongrun** [lobehub/lobe-chat#1297]
### 💻 Operating System

Other

### 📦 Environment

Docker

### 🌐 Browser

Edge

### 🐛 Bug Description

{
  "error": {
    "cause": {
      "name": "ConnectTimeoutError",
      "code": "UND_ERR_CONNECT_TIMEOUT",
      "message": "Connect Timeout Error"
    }
  },
  "provider": "openai",
  "endpoint": "https://api.openai.com/v1"
}
![image](https://github.com/lobehub/lobe-chat/assets/76803960/e453b4b7-64b6-4831-ada0-4440f87a5f33)

**Comment by atongrun** [comment]
> 咋解决的？？我今天更新了镜像就一直这样：
> 
> ![image](https://private-user-images.githubusercontent.com/46926496/306640992-950f457e-82af-41d4-a2dc-ade12e9dde43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjMwODMsIm5iZiI6MTcwODUyMjc4MywicGF0aCI6Ii80NjkyNjQ5Ni8zMDY2NDA5OTItOTUwZjQ1N2UtODJhZi00MWQ0LWEyZGMtYWRlMTJlOWRkZTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDEzMzk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTlhYWZjY2ZiN2U2YTVmYzA3ZjJmYzgyM2UwZmU0YjcwZWE4ZDkyODdjNmJhZTM0YjI4MDRjOGIyZTIwMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VCLpoWNBYpxG3JRu8adJo_XJdALZkF-GzAvu5BsgKs0)

针对我遇到的问题我写了一篇博客，你看看有帮助吗：https://atong.run/posts/621459748/

**Comment by atongrun** [comment]
> > > 咋解决的？？我今天更新了镜像就一直这样：
> > > ![image](https://private-user-images.githubusercontent.com/46926496/306640992-950f457e-82af-41d4-a2dc-ade12e9dde43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1MjMwODMsIm5iZiI6MTcwODUyMjc4MywicGF0aCI6Ii80NjkyNjQ5Ni8zMDY2NDA5OTItOTUwZjQ1N2UtODJhZi00MWQ0LWEyZGMtYWRlMTJlOWRkZTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIxVDEzMzk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNlYTlhYWZjY2ZiN2U2YTVmYzA3ZjJmYzgyM2UwZmU0YjcwZWE4ZDkyODdjNmJhZTM0YjI4MDRjOGIyZTIwMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VCLpoWNBYpxG3JRu8adJo_XJdALZkF-GzAvu5BsgKs0)
> > 
> > 
> > 针对我遇到的问题我写了一篇博客，你看看有帮助吗：https://atong.run/posts/621459748/
> 
> 配置没问题，就是网络连接不上，用python脚本测试都能本地调用api，不知道为啥lobechat不行
> 
> ![image](https://private-user-images.githubusercontent.com/46926496/306647277-c722830a-340c-4351-b24d-61ba5635fe38.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg1Njk5ODAsIm5iZiI6MTcwODU2OTY4MCwicGF0aCI6Ii80NjkyNjQ5Ni8zMDY2NDcyNzctYzcyMjgzMGEtMzQwYy00MzUxLWIyNGQtNjFiYTU2MzVmZTM4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIyVDAyNDEyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjNWUwNTk2MmU4OTJkNWY0NWMyZTA1MzhhNGYyOTIzOTdlODQ4NDFiZmFkOTkwNDY5OTI2MDBhYmUwZmNlMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.694aZl9GROwyxOtka5sysGL_BgcGB3l-vArCvWetzmc)

机器的3210端口开放了吗？

**Comment by LinightKira** [comment]
我也是这个问题？请问怎么解决？我直接本地跑的，openai接口也能访问到，就是无法聊天，提示超时

**Comment by saccohuo** [comment]
+1

**Comment by ikun-lsw** [comment]
同问
![image](https://github.com/lobehub/lobe-chat/assets/49890835/114a660d-3ecd-49cc-969d-a7fceb6e2c43)

**Comment by bald-girl** [comment]
到底咋解决这个问题哇

**Comment by delfer** [comment]
Hello! I have very slow local llm on cpu and always got this error.
<img width="259" alt="image" src="https://github.com/lobehub/lobe-chat/assets/3233181/82af856e-0e7a-4351-9ec2-94b81c04f63d">

<details>
<summary>Logs</summary>
```
 ⨯ Error: failed to pipe response
    at pipeToNodeResponse (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/pipe-readable.js:126:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async NextNodeServer.runEdgeFunction (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:1250:13)
    at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/next-server.js:248:37)
    at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:816:17)
    at async invokeRender (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:174:21)
    at async handleRequest (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:353:24)
    at async requestHandlerImpl (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/lib/start-server.js:141:13) {
  [cause]: td [Error]:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
      yield
    File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 254, in __aiter__
      async for part in self._httpcore_stream:
    File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__
      raise exc from None
    File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__
      async for part in self._stream:
    File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 349, in __aiter__
      raise exc
    File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 341, in __aiter__
      async for chunk in self._connection._receive_response_body(**kwargs):
    File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body
      event = await self._receive_event(timeout=timeout)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
      data = await self._network_stream.read(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 32, in read
      with map_exceptions(exc_map):
    File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
      self.gen.throw(typ, value, traceback)
    File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
      raise to_exc(exc) from exc
  httpcore.ReadTimeout

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2323, in async_data_generator
      async for chunk in response:
    File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9842, in __anext__
      raise e
    File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9658, in __anext__
      async for chunk in self.completion_stream:
    File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 147, in __aiter__
      async for item in self._iterator:
    File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 160, in __stream__
      async for sse in iterator:
    File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 151, in _iter_events
      async for sse in self._decoder.aiter_bytes(self.response.aiter_bytes()):
    File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 302, in aiter_bytes
      async for chunk in self._aiter_chunks(iterator):
    File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 313, in _aiter_chunks
      async for chunk in iterator:
    File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 929, in aiter_bytes
      async for raw_bytes in self.aiter_raw():
    File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 987, in aiter_raw
      async for raw_stream_bytes in self.stream:
    File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 149, in __aiter__
      async for chunk in self._stream:
    File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 253, in __aiter__
      with map_httpcore_exceptions():
    File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
      self.gen.throw(typ, value, traceback)
    File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
      raise mapped_exc(message) from exc
  httpx.ReadTimeout

      at eE.iterator (/app/.next/server/edge-chunks/836.js:4:1705)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async j (/app/.next/server/edge-chunks/607.js:9:5610)
      at async Object.pull (/app/.next/server/edge-chunks/681.js:172:6021) {
    status: undefined,
    headers: undefined,
    request_id: undefined,
    error: {
      message: '\n' +
        '\n' +
        'Traceback (most recent call last):\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions\n' +
        '    yield\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 254, in __aiter__\n' +
        '    async for part in self._httpcore_stream:\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 367, in __aiter__\n' +
        '    raise exc from None\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 363, in __aiter__\n' +
        '    async for part in self._stream:\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 349, in __aiter__\n' +
        '    raise exc\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 341, in __aiter__\n' +
        '    async for chunk in self._connection._receive_response_body(**kwargs):\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 210, in _receive_response_body\n' +
        '    event = await self._receive_event(timeout=timeout)\n' +
        '            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http11.py", line 224, in _receive_event\n' +
        '    data = await self._network_stream.read(\n' +
        '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 32, in read\n' +
        '    with map_exceptions(exc_map):\n' +
        '  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__\n' +
        '    self.gen.throw(typ, value, traceback)\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions\n' +
        '    raise to_exc(exc) from exc\n' +
        'httpcore.ReadTimeout\n' +
        '\n' +
        'The above exception was the direct cause of the following exception:\n' +
        '\n' +
        'Traceback (most recent call last):\n' +
        '  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2323, in async_data_generator\n' +
        '    async for chunk in response:\n' +
        '  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9842, in __anext__\n' +
        '    raise e\n' +
        '  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9658, in __anext__\n' +
        '    async for chunk in self.completion_stream:\n' +
        '  File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 147, in __aiter__\n' +
        '    async for item in self._iterator:\n' +
        '  File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 160, in __stream__\n' +
        '    async for sse in iterator:\n' +
        '  File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 151, in _iter_events\n' +
        '    async for sse in self._decoder.aiter_bytes(self.response.aiter_bytes()):\n' +
        '  File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 302, in aiter_bytes\n' +
        '    async for chunk in self._aiter_chunks(iterator):\n' +
        '  File "/usr/local/lib/python3.11/site-packages/openai/_streaming.py", line 313, in _aiter_chunks\n' +
        '    async for chunk in iterator:\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 929, in aiter_bytes\n' +
        '    async for raw_bytes in self.aiter_raw():\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 987, in aiter_raw\n' +
        '    async for raw_stream_bytes in self.stream:\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 149, in __aiter__\n' +
        '    async for chunk in self._stream:\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 253, in __aiter__\n' +
        '    with map_httpcore_exceptions():\n' +
        '  File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__\n' +
        '    self.gen.throw(typ, value, traceback)\n' +
        '  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions\n' +
        '    raise mapped_exc(message) from exc\n' +
        'httpx.ReadTimeout\n',
      type: 'None',
      param: 'None',
      code: 500
    },
    code: 500,
    param: 'None',
    type: 'None'
  }
}
Error: aborted
    at abortIncoming (node:_http_server:797:17)
    at socketOnClose (node:_http_server:791:3)
    at Socket.emit (node:events:531:35)
    at TCP.<anonymous> (node:net:338:12)
    at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
  code: 'ECONNRESET'
}
```
</details>

**Comment by arvinxx** [comment]
@delfer maybe it's due to the slow Fisrt token?

**Comment by delfer** [comment]
> @delfer maybe it's due to the slow Fisrt token?

yes, I think yes. How to change time out?

**Comment by lingium** [comment]
+1
