### ISSUE TITLE
[Bug] OAuth throw trusthost error on Docker deployment

### ISSUE THREAD

**Issue by cy948** [lobehub/lobe-chat#1315]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Edge

### 🐛 Bug Description

- **case 1**: Backend console throw [Trusthost](https://authjs.dev/reference/core/errors/#untrustedhost) error while using SSO login.
- **case 2**: Guest user can chat without apikey inputed or SSO logined while specify `OPENAI_API_KEY` and `ACCESS_CODE` at docker start.

### 🚦 Expected Behavior

- **case 1**: no error throw.
- **case 2**: Guest user must signin with SSO or provide access code before chat.

### 📷 Recurrence Steps

> both cases only occured in docker deployment, my docker run script are above

#### Docker run script
```powershell
docker pull lobehub/lobe-chat
docker run -p 3210:3210 
  -e ACCESS_CODE=eH***8vb  
  -e OPENAI_PROXY_URL=https://ga*****op/v1 
  -e ENABLE_OAUTH_SSO=1
  -e NEXTAUTH_SECRET=
  -e AUTH0_CLIENT_ID=
  -e AUTH0_CLIENT_SECRET=
  -e AUTH0_ISSUER=
  -e OPENAI_API_KEY=sk-
  --name lobe-chat -i
  lobehub/lobe-chat
```

**Case 1**

- visit path `/settings/common`, click `Sign in using SSO - Sign In` button
- then backend console throw error:
```log
[auth][error] UntrustedHost: Host must be trusted. URL was: http://0.0.0.0:3210/api/auth/session?nextauth=session .Read more at https://errors.authjs.dev#untrustedhost
    at /app/.next/server/app/api/auth/[...nextauth]/route.js:357:46489
    at nu (/app/.next/server/app/api/auth/[...nextauth]/route.js:357:49162)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/.next/server/app/api/auth/[...nextauth]/route.js:367:64567
    at async C.execute (/app/.next/server/app/api/auth/[...nextauth]/route.js:367:61460)
    at async C.handle (/app/.next/server/app/api/auth/[...nextauth]/route.js:367:65834)
    at async ev.handler (/app/.next/server/app/api/auth/[...nextauth]/route.js:368:31644)
    at async D (/app/.next/server/app/api/auth/[...nextauth]/route.js:368:3661)
    at async runWithTaggedErrors (/app/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/sandbox.js:99:24)
    at async NextNodeServer.runEdgeFunction (/app/node_modules/.pnpm/next@14.1.0_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/next-server.js:1177:24)
```

**Case 2**
- visit path `/chat`, post a message
backend console report same error as **case 1**

### 📝 Additional Information

For the **case 1**, the problem can be solved by adding environment variable `NEXTAUTH_URL=<your_public_url>`, and set trusthost to `true` in nextauth config, like https://github.com/cy948/lobe-chat/commit/87e6860e4a88b4ddf65b1880d70d3b8f973ae3ae , but it would make application become vulnerable, so I post this issue for a better solution.

**Comment by cy948** [comment]
blame [next-auth](https://authjs.dev/getting-started/providers/oauth-tutorial#setting-up-nextauth_url), the environment variable `NEXTAUTH_URL=<your_public_url>` will cause bug like https://github.com/nextauthjs/next-auth/issues/10009.

**Comment by cy948** [comment]
All problems found and solved, I will open a PR to fix it later.
