### ISSUE TITLE
[Bug] vercel已无法部署，有erro

### ISSUE THREAD

**Issue by sunsky89757** [lobehub/lobe-chat#1600]
### 💻 Operating System

Windows

### 📦 Environment

Official Preview

### 🌐 Browser

Chrome

### 🐛 Bug Description

![image](https://github.com/lobehub/lobe-chat/assets/113254524/6f4145e1-f6ee-41c8-bc8f-ec4e57772e87)
如图

**Comment by arvinxx** [comment]
给个复现。我刚测了下没问题哎
<img width="1333" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/4e1b9bb0-5c55-46e2-944e-b9ed1aa80e8a">

**Comment by shangy1yi** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/110846601/51546f00-8c66-4671-a4e0-91b8d36fce10)
同样的问题，无法部署

**Comment by felixiho** [comment]
I'm also facing the same issue when trying to deploy to vercel. 
<img width="1059" alt="Screenshot 2024-03-18 at 15 01 17" src="https://github.com/lobehub/lobe-chat/assets/23721418/aa74a0df-4b39-4a08-bed8-2b9d41c550ae">

💻 Operating System
MacOS

📦 Environment
Vercel Preview

🌐 Browser
Chrome

**Comment by arvinxx** [comment]
@felixiho @shangy1yi Do you try to build without cache?

**Comment by felixiho** [comment]
yes I've tried that countless times

**Comment by arvinxx** [comment]
Are you sync with latest commit？

**Comment by sunsky89757** [comment]
同步最新的版本后已可以正常部署，谢谢大佬

**Comment by QAbot-zh** [comment]
同步最新版本，但部署失败，以下是日志：
```
<html>
<body>
<!--StartFragment-->


Running build in Washington, D.C., USA (East) – iad1
20:54:18.117 | Cloning github.com/QAbot-zh/lobe-chat (Branch: main, Commit: f42ff8c)
20:54:19.000 | Cloning completed: 883.019ms
20:54:45.677 | Skipping build cache since Package Manager changed from "yarn" to "npm"
20:54:51.316 | Running "vercel build"
20:54:55.971 | Vercel CLI 33.6.1
20:54:56.548 | Running "install" command: `bun install`...
20:54:56.722 | bun install v1.0.32 (5fec71bd)
20:54:56.732 | Resolving dependencies
20:55:09.305 | Resolved, downloaded and extracted [9124]
20:55:09.306 | warn: incorrect peer dependency "@octokit/core@5.1.0"
20:55:09.306 |  
20:55:09.306 | warn: incorrect peer dependency "@octokit/core@5.1.0"
20:55:09.306 |  
20:55:09.306 | warn: incorrect peer dependency "@octokit/core@5.1.0"
20:55:09.306 |  
20:55:09.307 | warn: incorrect peer dependency "stylelint@15.11.0"
20:55:09.307 |  
20:55:09.307 | warn: incorrect peer dependency "stylelint@15.11.0"
20:55:09.307 |  
20:55:09.307 | warn: incorrect peer dependency "@octokit/core@5.1.0"
20:55:13.827 | gyp info it worked if it ends with ok
20:55:13.831 | gyp info using node-gyp@9.4.1
20:55:13.831 | gyp info using node@18.19.1 \| linux \| x64
20:55:13.831 | gyp info find Python using Python version 3.9.8 found at "/usr/local/bin/python3"
20:55:13.831 | gyp ERR! UNCAUGHT EXCEPTION
20:55:13.831 | gyp ERR! stack Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/p-map/index.js from /vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js not supported.
20:55:13.831 | gyp ERR! stack Instead change the require of index.js in /vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js to a dynamic import() which is available in all CommonJS modules.
20:55:13.832 | gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js:5:14)
20:55:13.832 | gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/index.js:6:16)
20:55:13.832 | gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/cache/entry.js:4:17)
20:55:13.832 | gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/cache/index.js:2:20)
20:55:13.832 | gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/fetch.js:7:15)
20:55:13.832 | gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/index.js:4:15)
20:55:13.832 | gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/lib/install.js:14:15)
20:55:13.833 | gyp ERR! stack     at self.commands.<computed> [as install] (/vercel/path0/node_modules/node-gyp/lib/node-gyp.js:41:14)
20:55:13.833 | gyp ERR! stack     at getNodeDir (/vercel/path0/node_modules/node-gyp/lib/configure.js:64:20)
20:55:13.833 | gyp ERR! stack     at /vercel/path0/node_modules/node-gyp/lib/configure.js:31:7
20:55:13.833 | gyp ERR! System Linux 5.10.174
20:55:13.833 | gyp ERR! command "/node18/bin/node" "/vercel/path0/node_modules/.bin/node-gyp" "rebuild"
20:55:13.833 | gyp ERR! cwd /vercel/path0/node_modules/tree-sitter-json
20:55:13.833 | gyp ERR! node -v v18.19.1
20:55:13.833 | gyp ERR! node-gyp -v v9.4.1
20:55:13.833 | gyp ERR! Node-gyp failed to build your package.
20:55:13.833 | gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
20:55:13.833 |  
20:55:13.834 | error: install script from "tree-sitter-json" exited with 7
20:55:13.878 | Error: Command "bun install" exited with 7
20:55:15.828

<br class="Apple-interchange-newline"><!--EndFragment-->
</body>
</html>
```

**Comment by Nomamuk** [comment]
build 失败，以下是日志：
[22:50:33.711] Running build in Washington, D.C., USA (East) – iad1
[22:50:34.993] Cloning github.com/Nomamuk/lobe-chat (Branch: main, Commit: f42ff8c)
[22:50:35.392] Previous build cache not available
[22:50:35.850] Cloning completed: 853.465ms
[22:50:36.898] Running "vercel build"
[22:50:37.937] Vercel CLI 33.6.1
[22:50:38.910] Running "install" command: `bun install`...
[22:50:39.121] bun install v1.0.32 (5fec71bd)
[22:50:39.134]  Resolving dependencies
[22:51:03.124]  Resolved, downloaded and extracted [9128]
[22:51:03.124] warn: incorrect peer dependency "@octokit/core@5.1.0"
[22:51:03.125] 
[22:51:03.125] warn: incorrect peer dependency "stylelint@15.11.0"
[22:51:03.125] 
[22:51:03.125] warn: incorrect peer dependency "stylelint@15.11.0"
[22:51:03.125] 
[22:51:03.125] warn: incorrect peer dependency "@octokit/core@5.1.0"
[22:51:03.125] 
[22:51:03.125] warn: incorrect peer dependency "@octokit/core@5.1.0"
[22:51:05.954] gyp info it worked if it ends with ok
[22:51:05.956] gyp info using node-gyp@9.4.1
[22:51:05.957] gyp info using node@18.19.1 | linux | x64
[22:51:05.957] gyp info find Python using Python version 3.9.8 found at "/usr/local/bin/python3"
[22:51:05.957] gyp ERR! UNCAUGHT EXCEPTION 
[22:51:05.957] gyp ERR! stack Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/p-map/index.js from /vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js not supported.
[22:51:05.957] gyp ERR! stack Instead change the require of index.js in /vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js to a dynamic import() which is available in all CommonJS modules.
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js:5:14)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/index.js:6:16)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/cache/entry.js:4:17)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/cache/index.js:2:20)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/fetch.js:7:15)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/index.js:4:15)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/lib/install.js:14:15)
[22:51:05.958] gyp ERR! stack     at self.commands.<computed> [as install] (/vercel/path0/node_modules/node-gyp/lib/node-gyp.js:41:14)
[22:51:05.958] gyp ERR! stack     at getNodeDir (/vercel/path0/node_modules/node-gyp/lib/configure.js:64:20)
[22:51:05.958] gyp ERR! stack     at /vercel/path0/node_modules/node-gyp/lib/configure.js:31:7
[22:51:05.958] gyp ERR! System Linux 5.10.174
[22:51:05.958] gyp ERR! command "/node18/bin/node" "/vercel/path0/node_modules/.bin/node-gyp" "rebuild"
[22:51:05.958] gyp ERR! cwd /vercel/path0/node_modules/tree-sitter-yaml
[22:51:05.958] gyp ERR! node -v v18.19.1
[22:51:05.958] gyp ERR! node-gyp -v v9.4.1
[22:51:05.958] gyp ERR! Node-gyp failed to build your package.
[22:51:05.958] gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
[22:51:05.958] 
[22:51:05.958] error: install script from "tree-sitter-yaml" exited with 7
[22:51:06.010] Error: Command "bun install" exited with 7
[22:51:07.524]

**Comment by Nomamuk** [comment]
> ✅ @sunsky89757
> 
> This issue is closed, If you have any questions, you can comment and reply. 此问题已经关闭。如果您有任何问题，可以留言并回复。

build 失败，以下是日志：
[22:50:33.711] Running build in Washington, D.C., USA (East) – iad1
[22:50:34.993] Cloning github.com/Nomamuk/lobe-chat (Branch: main, Commit: f42ff8c)
[22:50:35.392] Previous build cache not available
[22:50:35.850] Cloning completed: 853.465ms
[22:50:36.898] Running "vercel build"
[22:50:37.937] Vercel CLI 33.6.1
[22:50:38.910] Running "install" command: `bun install`...
[22:50:39.121] bun install v1.0.32 (5fec71bd)
[22:50:39.134]  Resolving dependencies
[22:51:03.124]  Resolved, downloaded and extracted [9128]
[22:51:03.124] warn: incorrect peer dependency "@octokit/core@5.1.0"
[22:51:03.125] 
[22:51:03.125] warn: incorrect peer dependency "stylelint@15.11.0"
[22:51:03.125] 
[22:51:03.125] warn: incorrect peer dependency "stylelint@15.11.0"
[22:51:03.125] 
[22:51:03.125] warn: incorrect peer dependency "@octokit/core@5.1.0"
[22:51:03.125] 
[22:51:03.125] warn: incorrect peer dependency "@octokit/core@5.1.0"
[22:51:05.954] gyp info it worked if it ends with ok
[22:51:05.956] gyp info using node-gyp@9.4.1
[22:51:05.957] gyp info using node@18.19.1 | linux | x64
[22:51:05.957] gyp info find Python using Python version 3.9.8 found at "/usr/local/bin/python3"
[22:51:05.957] gyp ERR! UNCAUGHT EXCEPTION 
[22:51:05.957] gyp ERR! stack Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/p-map/index.js from /vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js not supported.
[22:51:05.957] gyp ERR! stack Instead change the require of index.js in /vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js to a dynamic import() which is available in all CommonJS modules.
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js:5:14)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/index.js:6:16)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/cache/entry.js:4:17)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/cache/index.js:2:20)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/fetch.js:7:15)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/index.js:4:15)
[22:51:05.957] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/lib/install.js:14:15)
[22:51:05.958] gyp ERR! stack     at self.commands.<computed> [as install] (/vercel/path0/node_modules/node-gyp/lib/node-gyp.js:41:14)
[22:51:05.958] gyp ERR! stack     at getNodeDir (/vercel/path0/node_modules/node-gyp/lib/configure.js:64:20)
[22:51:05.958] gyp ERR! stack     at /vercel/path0/node_modules/node-gyp/lib/configure.js:31:7
[22:51:05.958] gyp ERR! System Linux 5.10.174
[22:51:05.958] gyp ERR! command "/node18/bin/node" "/vercel/path0/node_modules/.bin/node-gyp" "rebuild"
[22:51:05.958] gyp ERR! cwd /vercel/path0/node_modules/tree-sitter-yaml
[22:51:05.958] gyp ERR! node -v v18.19.1
[22:51:05.958] gyp ERR! node-gyp -v v9.4.1
[22:51:05.958] gyp ERR! Node-gyp failed to build your package.
[22:51:05.958] gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
[22:51:05.958] 
[22:51:05.958] error: install script from "tree-sitter-yaml" exited with 7
[22:51:06.010] Error: Command "bun install" exited with 7
[22:51:07.524]
