### ISSUE TITLE
[Bug] vercel  deployment failure

### ISSUE THREAD

**Issue by Azhizzz** [lobehub/lobe-chat#1651]
### 💻 Operating System

macOS

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

[00:40:47.455] Running build in Washington, D.C., USA (East) – iad1
[00:40:47.591] Cloning github.com/Azhizzz/lobe-chat (Branch: main, Commit: f42ff8c)
[00:40:47.600] Skipping build cache, deployment was triggered without cache.
[00:40:48.191] Cloning completed: 599.884ms
[00:40:48.644] Running "vercel build"
[00:40:49.133] Vercel CLI 33.6.1
[00:40:49.608] Running "install" command: `bun install`...
[00:40:49.654] bun install v1.0.32 (5fec71bd)
[00:40:49.662]  Resolving dependencies
[00:41:02.418]  Resolved, downloaded and extracted [9126]
[00:41:02.419] warn: incorrect peer dependency "@octokit/core@5.1.0"
[00:41:02.420] 
[00:41:02.420] warn: incorrect peer dependency "@octokit/core@5.1.0"
[00:41:02.420] 
[00:41:02.420] warn: incorrect peer dependency "@octokit/core@5.1.0"
[00:41:02.420] 
[00:41:02.421] warn: incorrect peer dependency "stylelint@15.11.0"
[00:41:02.421] 
[00:41:02.421] warn: incorrect peer dependency "stylelint@15.11.0"
[00:41:02.421] 
[00:41:02.421] warn: incorrect peer dependency "@octokit/core@5.1.0"
[00:41:06.857] gyp info it worked if it ends with ok
[00:41:06.863] gyp info using node-gyp@9.4.1
[00:41:06.864] gyp info using node@18.19.1 | linux | x64
[00:41:06.864] gyp info find Python using Python version 3.9.8 found at "/usr/local/bin/python3"
[00:41:06.864] gyp ERR! UNCAUGHT EXCEPTION 
[00:41:06.864] gyp ERR! stack Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/p-map/index.js from /vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js not supported.
[00:41:06.865] gyp ERR! stack Instead change the require of index.js in /vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js to a dynamic import() which is available in all CommonJS modules.
[00:41:06.865] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js:5:14)
[00:41:06.865] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/index.js:6:16)
[00:41:06.865] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/cache/entry.js:4:17)
[00:41:06.866] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/cache/index.js:2:20)
[00:41:06.866] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/fetch.js:7:15)
[00:41:06.866] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/lib/index.js:4:15)
[00:41:06.866] gyp ERR! stack     at Object.<anonymous> (/vercel/path0/node_modules/node-gyp/lib/install.js:14:15)
[00:41:06.867] gyp ERR! stack     at self.commands.<computed> [as install] (/vercel/path0/node_modules/node-gyp/lib/node-gyp.js:41:14)
[00:41:06.867] gyp ERR! stack     at getNodeDir (/vercel/path0/node_modules/node-gyp/lib/configure.js:64:20)
[00:41:06.867] gyp ERR! stack     at /vercel/path0/node_modules/node-gyp/lib/configure.js:31:7
[00:41:06.871] gyp ERR! System Linux 5.10.174
[00:41:06.871] gyp ERR! command "/node18/bin/node" "/vercel/path0/node_modules/.bin/node-gyp" "rebuild"
[00:41:06.871] gyp ERR! cwd /vercel/path0/node_modules/tree-sitter-json
[00:41:06.872] gyp ERR! node -v v18.19.1
[00:41:06.872] gyp ERR! node-gyp -v v9.4.1
[00:41:06.872] gyp ERR! Node-gyp failed to build your package.
[00:41:06.872] gyp ERR! Try to update npm and/or node-gyp and if it does not help file an issue with the package author.
[00:41:06.872] 
[00:41:06.873] error: install script from "tree-sitter-json" exited with 7
[00:41:06.912] Error: Command "bun install" exited with 7
[00:41:08.293] 

### 🚦 Expected Behavior

successful deployment

### 📷 Recurrence Steps

Each deployment prompts the above error

**Comment by acotor** [comment]
Same issue when redeploy or deploy at upstream sync. Main errors as follow:
```
...
gyp ERR! stack Error [ERR_REQUIRE_ESM]: require() of ES Module /vercel/path0/node_modules/p-map/index.js from /vercel/path0/node_modules/node-gyp/node_modules/make-fetch-happen/node_modules/cacache/lib/verify.js not supported.
...
error: install script from "tree-sitter" exited with 7
Error: Command "bun install" exited with 7
...
```

**Comment by YangShanHui** [comment]
error: install script from "tree-sitter" exited with 7
Error: Command "bun install" exited with 7

**Comment by jerwilcy** [comment]
Same issue when deploy with Vercel. 

Deployment failed with error.

**Comment by gneko** [comment]
Same issue when redeploying.

I managed to workaround by checking "Use existing Build Cache" on succeed deploylment.

**Comment by arvinxx** [comment]
due to https://github.com/oven-sh/bun/issues/9503 and https://github.com/oven-sh/bun/issues/9489#issuecomment-2003903312 , there is install failure with bun@v1.0.32 and 1.0.33. I have created the [PR](https://github.com/lobehub/lobe-chat/pull/1654) to temporarily fix it.
