### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Szymok** [lobehub/lobe-chat#1774]
### 💻 Operating System

Ubuntu

### 📦 Environment

Docker

### 🌐 Browser

Edge

### 🐛 Bug Description

Error after installing the newest version of lobe-chat on docker:
Error: Cannot find module './pl.js'
    at /app/.next/server/chunks/69438.js:1:7617
    at runNextTicks (node:internal/process/task_queues:60:5)
    at listOnTimeout (node:internal/timers:540:9)
    at process.processTimers (node:internal/timers:514:7)
    at async H (/app/.next/server/chunks/69438.js:211:7754)
    at async eu (/app/.next/server/chunks/69438.js:211:8477) {
  code: 'MODULE_NOT_FOUND'
}
[Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
  digest: '1718330264'
}

**Comment by arvinxx** [comment]
are your browser language is set as pl not the pl-PL?

**Comment by PierreMesure** [comment]
Getting the same issue with "sv.js".
