### ISSUE TITLE
[Bug] Application error: a server-side exception has occurred

### ISSUE THREAD

**Issue by BreakWooden** [lobehub/lobe-chat#1886]
### 💻 Operating System

Other Linux

### 📦 Environment

Docker

### 🌐 Browser

Firefox

### 🐛 Bug Description

Application error: a server-side exception has occurred (see the server logs for more information).
Digest: 144739034
This error appearing on my both OS : Windows11 23H1 and Linux Fedora 39

### 🚦 Expected Behavior

A correct Launching of the web app from docker like yesterday 

### 📷 Recurrence Steps

Pulling docker
Running image from docker desktop or terminal (tried multiple port and the default one)

### Server Logs
```
2024-04-03 13:52:05    ▲ Next.js 14.1.4
2024-04-03 13:52:05    - Local:        http://localhost:3210
2024-04-03 13:52:05    - Network:      http://0.0.0.0:3210
2024-04-03 13:52:05 
2024-04-03 13:52:05  ✓ Ready in 73ms
2024-04-03 13:52:20 Error: Cannot find module './fr.js'
2024-04-03 13:52:20     at /app/.next/server/chunks/19750.js:1:7954
2024-04-03 13:52:20     at runNextTicks (node:internal/process/task_queues:60:5)
2024-04-03 13:52:20     at listOnTimeout (node:internal/timers:540:9)
2024-04-03 13:52:20     at process.processTimers (node:internal/timers:514:7)
2024-04-03 13:52:20     at async H (/app/.next/server/chunks/19750.js:226:7754)
2024-04-03 13:52:20     at async eu (/app/.next/server/chunks/19750.js:226:8477) {
2024-04-03 13:52:20   code: 'MODULE_NOT_FOUND'
2024-04-03 13:52:20 }
2024-04-03 13:52:20 [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
2024-04-03 13:52:20   digest: '144739034'
2024-04-03 13:52:20 }
2024-04-03 13:52:20 Error: Cannot find module './fr.js'
2024-04-03 13:52:20     at /app/.next/server/chunks/19750.js:1:7954
2024-04-03 13:52:20     at async H (/app/.next/server/chunks/19750.js:226:7754)
2024-04-03 13:52:20     at async eu (/app/.next/server/chunks/19750.js:226:8477) {
2024-04-03 13:52:20   code: 'MODULE_NOT_FOUND'
2024-04-03 13:52:20 }
2024-04-03 13:52:20 [Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.] {
2024-04-03 13:52:20   digest: '3869975412'
2024-04-03 13:52:20 }
```

**Comment by BreakWooden** [comment]
## 🫧 Solution :

Okay I think I found the origin of the issue.

I have to clear the cookie of the page (localhost:XXXX) and then it's working but if I reload the page I'm getting the website page where I have the message "... a server-side exception ..." wich is pretty annoying. Is it an bug or protection is there any way to solve this ? 

Thanks !

**Comment by nekowis** [comment]
> ## 🫧 Solution :
> 
> Okay I think I found the origin of the issue.
> 
> I have to clear the cookie of the page (localhost:XXXX) and then it's working but if I reload the page I'm getting the website page where I have the message "... a server-side exception ..." wich is pretty annoying. Is it an bug or protection is there any way to solve this ?
> 
> Thanks !

I am facing exactly the same issue. 
The Lobe chat works right after I delete the cookies from the web page, but once I reload the page, it displays ‘… a server-side exception …’ and becomes completely unusable. 
This problem occurs not only in Firefox but in any browser.
