### ISSUE TITLE
[Bug] 使用Vercel默认部署项目，部署失败（附带Vercel部署完整报错日志）

### ISSUE THREAD

**Issue by wangzhazha100** [lobehub/lobe-chat#2092]
### 💻 系统环境

Windows

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用Next.js，没有重写Build and Output Settings，添加一个OPENAI_API_KEY参数，之后部署
![image](https://github.com/lobehub/lobe-chat/assets/50234918/d1d9ed5a-6229-416f-93d6-6b4372b45572)
报错
![image](https://github.com/lobehub/lobe-chat/assets/50234918/67cb412e-f913-4b0c-8e6f-0295ad3f1ca7)

### 🚦 期望结果

希望解决vercel部署失败的问题

### 📷 复现步骤

使用Vercel默认部署项目，使用Next.js，使用默认部署参数，添加OPENAI_API_KEY参数，部署失败

### 📝 补充信息

[11:33:16.028] Running build in Washington, D.C., USA (East) – iad1
[11:33:16.179] Cloning github.com/wangzhazha100/lobe-chat (Branch: main, Commit: 34677f6)
[11:33:16.526] Previous build cache not available
[11:33:16.807] Cloning completed: 627.558ms
[11:33:17.270] Running "vercel build"
[11:33:18.012] Vercel CLI 34.1.1
[11:33:19.367] Running "install" command: `bun install`...
[11:33:19.419] bun install v1.1.4 (fbe2fe0c)
[11:33:19.431]  Resolving dependencies
[11:33:30.709]  Resolved, downloaded and extracted [8866]
[11:33:30.711] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.711] 
[11:33:30.715] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.717] 
[11:33:30.718] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.719] 
[11:33:30.719] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.719] 
[11:33:30.719] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.719] 
[11:33:30.720] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.720] 
[11:33:30.720] warn: incorrect peer dependency "@octokit/core@5.2.0"
[11:33:30.720] 
[11:33:30.720] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.720] 
[11:33:30.720] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.721] 
[11:33:30.723] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.723] 
[11:33:30.723] warn: incorrect peer dependency "stylelint@15.11.0"
[11:33:30.723] 
[11:33:30.723] warn: incorrect peer dependency "@octokit/core@5.2.0"
[11:33:30.723] 
[11:33:30.724] warn: incorrect peer dependency "@octokit/core@5.2.0"
[11:33:39.655] gyp info it worked if it ends with ok
[11:33:39.657] gyp info using node-gyp@9.4.1
[11:33:39.659] gyp info using node@20.12.2 | linux | x64
[11:33:39.661] gyp info find Python using Python version 3.12.2 found at "/usr/local/bin/python3"
[11:33:39.665] gyp http GET https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
[11:33:39.667] gyp http 200 https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
[11:33:39.667] gyp http GET https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
[11:33:39.667] gyp http 200 https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
[11:33:39.668] gyp info spawn /usr/local/bin/python3
[11:33:39.668] gyp info spawn args [
[11:33:39.668] gyp info spawn args   '/vercel/path0/node_modules/node-gyp/gyp/gyp_main.py',
[11:33:39.668] gyp info spawn args   'binding.gyp',
[11:33:39.668] gyp info spawn args   '-f',
[11:33:39.668] gyp info spawn args   'make',
[11:33:39.668] gyp info spawn args   '-I',
[11:33:39.668] gyp info spawn args   '/vercel/path0/node_modules/tree-sitter-yaml/build/config.gypi',
[11:33:39.668] gyp info spawn args   '-I',
[11:33:39.668] gyp info spawn args   '/vercel/path0/node_modules/node-gyp/addon.gypi',
[11:33:39.668] gyp info spawn args   '-I',
[11:33:39.669] gyp info spawn args   '/vercel/.cache/node-gyp/20.12.2/include/node/common.gypi',
[11:33:39.669] gyp info spawn args   '-Dlibrary=shared_library',
[11:33:39.669] gyp info spawn args   '-Dvisibility=default',
[11:33:39.669] gyp info spawn args   '-Dnode_root_dir=/vercel/.cache/node-gyp/20.12.2',
[11:33:39.669] gyp info spawn args   '-Dnode_gyp_dir=/vercel/path0/node_modules/node-gyp',
[11:33:39.669] gyp info spawn args   '-Dnode_lib_file=/vercel/.cache/node-gyp/20.12.2/<(target_arch)/node.lib',
[11:33:39.669] gyp info spawn args   '-Dmodule_root_dir=/vercel/path0/node_modules/tree-sitter-yaml',
[11:33:39.669] gyp info spawn args   '-Dnode_engine=v8',
[11:33:39.669] gyp info spawn args   '--depth=.',
[11:33:39.669] gyp info spawn args   '--no-parallel',
[11:33:39.669] gyp info spawn args   '--generator-output',
[11:33:39.669] gyp info spawn args   'build',
[11:33:39.669] gyp info spawn args   '-Goutput_dir=.'
[11:33:39.669] gyp info spawn args ]
[11:33:39.669] Traceback (most recent call last):
[11:33:39.669]   File "/vercel/path0/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
[11:33:39.669]     import gyp  # noqa: E402
[11:33:39.669]     ^^^^^^^^^^
[11:33:39.669]   File "/vercel/path0/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
[11:33:39.669]     import gyp.input
[11:33:39.669]   File "/vercel/path0/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
[11:33:39.669]     from distutils.version import StrictVersion
[11:33:39.669] ModuleNotFoundError: No module named 'distutils'
[11:33:39.669] gyp ERR! configure error 
[11:33:39.669] gyp ERR! stack Error: `gyp` failed with exit code: 1
[11:33:39.669] gyp ERR! stack     at ChildProcess.onCpExit (/vercel/path0/node_modules/node-gyp/lib/configure.js:325:16)
[11:33:39.669] gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
[11:33:39.670] gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[11:33:39.670] gyp ERR! System Linux 5.10.174
[11:33:39.670] gyp ERR! command "/node20/bin/node" "/vercel/path0/node_modules/.bin/node-gyp" "rebuild"
[11:33:39.670] gyp ERR! cwd /vercel/path0/node_modules/tree-sitter-yaml
[11:33:39.670] gyp ERR! node -v v20.12.2
[11:33:39.670] gyp ERR! node-gyp -v v9.4.1
[11:33:39.670] gyp ERR! not ok 
[11:33:39.670] 
[11:33:39.670] error: install script from "tree-sitter-yaml" exited with 1
[11:33:39.755] Error: Command "bun install" exited with 1
[11:33:43.450]

**Comment by sisiea** [comment]
same here

**Comment by sisiea** [comment]
> same here

去项目的 setting 里面把 Node.js 的版本设置为 18.x, ReDploy 一次就可以解决这个报错。
![image](https://github.com/lobehub/lobe-chat/assets/12793405/93a49df5-b0f6-48b7-83bc-1d0f508c4bd6)
