### ISSUE TITLE
[Bug] Error when deploying to vercel (ModuleNotFoundError: No module named 'distutils')

### ISSUE THREAD

**Issue by fdciabdul** [lobehub/lobe-chat#2102]
### 💻 Operating System

Other

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

just following step on here : https://lobehub.com/docs/self-hosting/platform/vercel
![image](https://github.com/lobehub/lobe-chat/assets/31664438/e5ad213a-123b-4150-9fc3-173762bfe259)

build logs: 

```
[20:50:47.784] Running build in Washington, D.C., USA (East) – iad1
[20:50:47.947] Cloning github.com/fdciabdul/lobe-chat (Branch: main, Commit: 03acac2)
[20:50:47.961] Skipping build cache, deployment was triggered without cache.
[20:50:49.149] Cloning completed: 1.201s
[20:50:50.123] Running "vercel build"
[20:50:51.033] Vercel CLI 33.7.1
[20:50:52.354] Running "install" command: `bun install`...
[20:50:52.498] bun install v1.1.4 (fbe2fe0c)
[20:50:52.515]  Resolving dependencies
[20:51:09.836]  Resolved, downloaded and extracted [8874]
[20:51:09.840] warn: incorrect peer dependency "stylelint@15.11.0"
[20:51:09.840] 
[20:51:09.841] warn: incorrect peer dependency "stylelint@15.11.0"
[20:51:09.841] 
[20:51:09.841] warn: incorrect peer dependency "@octokit/core@5.2.0"
[20:51:09.844] 
[20:51:09.845] warn: incorrect peer dependency "@octokit/core@5.2.0"
[20:51:09.846] 
[20:51:09.846] warn: incorrect peer dependency "stylelint@15.11.0"
[20:51:09.846] 
[20:51:09.846] warn: incorrect peer dependency "stylelint@15.11.0"
[20:51:09.847] 
[20:51:09.847] warn: incorrect peer dependency "@octokit/core@5.2.0"
[20:51:09.847] 
[20:51:09.847] warn: incorrect peer dependency "stylelint@15.11.0"
[20:51:09.848] 
[20:51:09.849] warn: incorrect peer dependency "stylelint@15.11.0"
[20:51:09.859] 
[20:51:09.860] warn: incorrect peer dependency "stylelint@15.11.0"
[20:51:09.860] 
[20:51:09.860] warn: incorrect peer dependency "stylelint@15.11.0"
[20:51:09.861] 
[20:51:09.861] warn: incorrect peer dependency "@octokit/core@5.2.0"
[20:51:17.436] prebuild-install warn install No prebuilt binaries found (target=20.12.2 runtime=node arch=x64 libc= platform=linux)
[20:51:17.436] gyp info it worked if it ends with ok
[20:51:17.436] gyp info using node-gyp@9.4.1
[20:51:17.436] gyp info using node@20.12.2 | linux | x64
[20:51:17.436] gyp info find Python using Python version 3.12.2 found at "/usr/local/bin/python3"
[20:51:17.436] gyp http GET https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
[20:51:17.436] gyp http 200 https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
[20:51:17.436] gyp http GET https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
[20:51:17.436] gyp http 200 https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
[20:51:17.436] gyp info spawn /usr/local/bin/python3
[20:51:17.436] gyp info spawn args [
[20:51:17.436] gyp info spawn args   '/vercel/path0/node_modules/node-gyp/gyp/gyp_main.py',
[20:51:17.436] gyp info spawn args   'binding.gyp',
[20:51:17.436] gyp info spawn args   '-f',
[20:51:17.436] gyp info spawn args   'make',
[20:51:17.436] gyp info spawn args   '-I',
[20:51:17.436] gyp info spawn args   '/vercel/path0/node_modules/tree-sitter/build/config.gypi',
[20:51:17.436] gyp info spawn args   '-I',
[20:51:17.437] gyp info spawn args   '/vercel/path0/node_modules/node-gyp/addon.gypi',
[20:51:17.437] gyp info spawn args   '-I',
[20:51:17.437] gyp info spawn args   '/vercel/.cache/node-gyp/20.12.2/include/node/common.gypi',
[20:51:17.437] gyp info spawn args   '-Dlibrary=shared_library',
[20:51:17.437] gyp info spawn args   '-Dvisibility=default',
[20:51:17.437] gyp info spawn args   '-Dnode_root_dir=/vercel/.cache/node-gyp/20.12.2',
[20:51:17.437] gyp info spawn args   '-Dnode_gyp_dir=/vercel/path0/node_modules/node-gyp',
[20:51:17.437] gyp info spawn args   '-Dnode_lib_file=/vercel/.cache/node-gyp/20.12.2/<(target_arch)/node.lib',
[20:51:17.437] gyp info spawn args   '-Dmodule_root_dir=/vercel/path0/node_modules/tree-sitter',
[20:51:17.437] gyp info spawn args   '-Dnode_engine=v8',
[20:51:17.437] gyp info spawn args   '--depth=.',
[20:51:17.437] gyp info spawn args   '--no-parallel',
[20:51:17.437] gyp info spawn args   '--generator-output',
[20:51:17.437] gyp info spawn args   'build',
[20:51:17.443] gyp info spawn args   '-Goutput_dir=.'
[20:51:17.443] gyp info spawn args ]
[20:51:17.444] Traceback (most recent call last):
[20:51:17.444]   File "/vercel/path0/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
[20:51:17.444]     import gyp  # noqa: E402
[20:51:17.444]     ^^^^^^^^^^
[20:51:17.444]   File "/vercel/path0/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
[20:51:17.445]     import gyp.input
[20:51:17.445]   File "/vercel/path0/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
[20:51:17.445]     from distutils.version import StrictVersion
[20:51:17.445] ModuleNotFoundError: No module named 'distutils'
[20:51:17.445] gyp ERR! configure error 
[20:51:17.446] gyp ERR! stack Error: `gyp` failed with exit code: 1
[20:51:17.446] gyp ERR! stack     at ChildProcess.onCpExit (/vercel/path0/node_modules/node-gyp/lib/configure.js:325:16)
[20:51:17.447] gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
[20:51:17.447] gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[20:51:17.447] gyp ERR! System Linux 5.10.174
[20:51:17.447] gyp ERR! command "/node20/bin/node" "/vercel/path0/node_modules/.bin/node-gyp" "rebuild"
[20:51:17.447] gyp ERR! cwd /vercel/path0/node_modules/tree-sitter
[20:51:17.450] gyp ERR! node -v v20.12.2
[20:51:17.451] gyp ERR! node-gyp -v v9.4.1
[20:51:17.451] gyp ERR! not ok 
[20:51:17.451] 
[20:51:17.451] error: install script from "tree-sitter" exited with 1
[20:51:17.514] Error: Command "bun install" exited with 1
[20:51:20.563] 
```

**Comment by arvinxx** [comment]
fixed with https://github.com/lobehub/lobe-chat/pull/2095

**Comment by arvinxx** [comment]
oh, i have tried but failed again.

**Comment by arvinxx** [comment]
I need to add deps of `node-gyp@10.1.0`, refs: https://github.com/oven-sh/bun/issues/10368#issuecomment-2066249459
