### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'distutils'

### ISSUE THREAD

**Issue by 209726742** [lobehub/lobe-chat#2106]
### 💻 Operating System

Windows

### 📦 Environment

Vercel / Zeabur / Sealos

### 🌐 Browser

Chrome

### 🐛 Bug Description

[23:28:32.053] Running build in Washington, D.C., USA (East) – iad1
[23:28:32.248] Cloning github.com/209726742/lobe-chat111 (Branch: main, Commit: b416b77)
[23:28:32.610] Previous build cache not available
[23:28:34.322] Cloning completed: 2.073s
[23:28:35.423] Running "vercel build"
[23:28:37.759] Vercel CLI 33.7.1
[23:28:38.267] Running "install" command: `npx bun@1.1.3 install`...
[23:28:39.436] npm WARN exec The following package was not found and will be installed: bun@1.1.3
[23:28:42.237] bun install v1.1.3 (2615dc74)
[23:28:42.240]  Resolving dependencies
[23:28:53.448]  Resolved, downloaded and extracted [8872]
[23:28:53.448] warn: incorrect peer dependency "stylelint@15.11.0"
[23:28:53.448] 
[23:28:53.448] warn: incorrect peer dependency "stylelint@15.11.0"
[23:28:53.449] 
[23:28:53.449] warn: incorrect peer dependency "stylelint@15.11.0"
[23:28:53.449] 
[23:28:53.449] warn: incorrect peer dependency "stylelint@15.11.0"
[23:28:53.449] 
[23:28:53.449] warn: incorrect peer dependency "@octokit/core@5.2.0"
[23:28:53.449] 
[23:28:53.449] warn: incorrect peer dependency "@octokit/core@5.2.0"
[23:28:53.449] 
[23:28:53.449] warn: incorrect peer dependency "@octokit/core@5.2.0"
[23:28:53.449] 
[23:28:53.449] warn: incorrect peer dependency "@octokit/core@5.2.0"
[23:28:53.449] 
[23:28:53.449] warn: incorrect peer dependency "stylelint@15.11.0"
[23:28:53.449] 
[23:28:53.449] warn: incorrect peer dependency "stylelint@15.11.0"
[23:29:01.619] gyp info it worked if it ends with ok
[23:29:01.619] gyp info using node-gyp@9.4.1
[23:29:01.619] gyp info using node@20.12.2 | linux | x64
[23:29:01.619] gyp info find Python using Python version 3.12.2 found at "/usr/local/bin/python3"
[23:29:01.620] gyp http GET https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
[23:29:01.620] gyp http 200 https://nodejs.org/download/release/v20.12.2/node-v20.12.2-headers.tar.gz
[23:29:01.620] gyp http GET https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
[23:29:01.620] gyp http 200 https://nodejs.org/download/release/v20.12.2/SHASUMS256.txt
[23:29:01.620] gyp info spawn /usr/local/bin/python3
[23:29:01.620] gyp info spawn args [
[23:29:01.620] gyp info spawn args   '/vercel/path0/node_modules/node-gyp/gyp/gyp_main.py',
[23:29:01.620] gyp info spawn args   'binding.gyp',
[23:29:01.620] gyp info spawn args   '-f',
[23:29:01.620] gyp info spawn args   'make',
[23:29:01.620] gyp info spawn args   '-I',
[23:29:01.620] gyp info spawn args   '/vercel/path0/node_modules/tree-sitter-yaml/build/config.gypi',
[23:29:01.620] gyp info spawn args   '-I',
[23:29:01.620] gyp info spawn args   '/vercel/path0/node_modules/node-gyp/addon.gypi',
[23:29:01.620] gyp info spawn args   '-I',
[23:29:01.620] gyp info spawn args   '/vercel/.cache/node-gyp/20.12.2/include/node/common.gypi',
[23:29:01.620] gyp info spawn args   '-Dlibrary=shared_library',
[23:29:01.620] gyp info spawn args   '-Dvisibility=default',
[23:29:01.621] gyp info spawn args   '-Dnode_root_dir=/vercel/.cache/node-gyp/20.12.2',
[23:29:01.621] gyp info spawn args   '-Dnode_gyp_dir=/vercel/path0/node_modules/node-gyp',
[23:29:01.621] gyp info spawn args   '-Dnode_lib_file=/vercel/.cache/node-gyp/20.12.2/<(target_arch)/node.lib',
[23:29:01.621] gyp info spawn args   '-Dmodule_root_dir=/vercel/path0/node_modules/tree-sitter-yaml',
[23:29:01.621] gyp info spawn args   '-Dnode_engine=v8',
[23:29:01.621] gyp info spawn args   '--depth=.',
[23:29:01.621] gyp info spawn args   '--no-parallel',
[23:29:01.621] gyp info spawn args   '--generator-output',
[23:29:01.621] gyp info spawn args   'build',
[23:29:01.621] gyp info spawn args   '-Goutput_dir=.'
[23:29:01.621] gyp info spawn args ]
[23:29:01.621] Traceback (most recent call last):
[23:29:01.621]   File "/vercel/path0/node_modules/node-gyp/gyp/gyp_main.py", line 42, in <module>
[23:29:01.621]     import gyp  # noqa: E402
[23:29:01.621]     ^^^^^^^^^^
[23:29:01.621]   File "/vercel/path0/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 9, in <module>
[23:29:01.621]     import gyp.input
[23:29:01.621]   File "/vercel/path0/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 19, in <module>
[23:29:01.621]     from distutils.version import StrictVersion
[23:29:01.621] ModuleNotFoundError: No module named 'distutils'
[23:29:01.621] gyp ERR! configure error 
[23:29:01.621] gyp ERR! stack Error: `gyp` failed with exit code: 1
[23:29:01.621] gyp ERR! stack     at ChildProcess.onCpExit (/vercel/path0/node_modules/node-gyp/lib/configure.js:325:16)
[23:29:01.621] gyp ERR! stack     at ChildProcess.emit (node:events:518:28)
[23:29:01.622] gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
[23:29:01.622] gyp ERR! System Linux 5.10.174
[23:29:01.622] gyp ERR! command "/node20/bin/node" "/vercel/path0/node_modules/.bin/node-gyp" "rebuild"
[23:29:01.622] gyp ERR! cwd /vercel/path0/node_modules/tree-sitter-yaml
[23:29:01.622] gyp ERR! node -v v20.12.2
[23:29:01.622] gyp ERR! node-gyp -v v9.4.1
[23:29:01.622] gyp ERR! not ok 
[23:29:01.622] 
[23:29:01.622] error: install script from "tree-sitter-yaml" exited with 1
[23:29:01.680] Error: Command "npx bun@1.1.3 install" exited with 1
[23:29:05.310] 
<img width="556" alt="1713540614548" src="https://github.com/lobehub/lobe-chat/assets/54384262/b566b9ec-5917-411c-975e-eb3ba7083955">
<img width="545" alt="1713540627206" src="https://github.com/lobehub/lobe-chat/assets/54384262/a4da30a3-d05b-4a12-808c-e2fcd9718c62">
<img width="540" alt="1713540635994" src="https://github.com/lobehub/lobe-chat/assets/54384262/e3708b32-2698-4e7d-ace3-3c0edf416b9d">

**Comment by arvinxx** [comment]
fixed with #2104
