### ISSUE TITLE
[Bug] openai请求报错Request Header Fields Too Large

### ISSUE THREAD

**Issue by gaye746560359** [lobehub/lobe-chat#2122]
### 💻 Operating System

Windows

### 📦 Environment

Docker

### 🌐 Browser

Chrome

### 🐛 Bug Description

{
  "error": {
    "headers": {
      "access-control-allow-origin": "*",
      "access-control-expose-headers": "Date,x-fc-request-id,x-fc-error-type,x-fc-code-checksum,x-fc-invocation-duration,x-fc-max-memory-usage,x-fc-log-result,x-fc-invocation-code-version,x-fc-instance-id",
      "alt-svc": "h3=\":443\"; ma=86400",
      "cf-cache-status": "DYNAMIC",
      "cf-ray": "8779e082bcbaa8f2-SIN",
      "content-disposition": "attachment",
      "content-type": "text/html",
      "date": "Sun, 21 Apr 2024 02:17:18 GMT",
      "set-cookie": "__cf_bm=2TYfMVCzDu8G2nTF8dFd5xyn.tPlPaL7bLo6EOsxyMU-1713665838-1.0.1.1-2n5Arh3naciGkS_852CxGr942RYeMuMEmagIzobNLbiNSPTLlMg3MUWhiVe9PQJyBT9i4yXkPfCDzjglLUxWDw; path=/; expires=Sun, 21-Apr-24 02:47:18 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=O0WhEUGsc8wzqjo7bGkAhuMe_QsfdRZcO0s.dAx6chs-1713665838866-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None",
      "strict-transport-security": "max-age=15724800; includeSubDomains",
      "transfer-encoding": "chunked",
      "x-fc-code-checksum": "8429226392270221315",
      "x-fc-instance-id": "c-6624772d-0127fc1c-baace0c36402",
      "x-fc-invocation-duration": "459",
      "x-fc-invocation-service-version": "LATEST",
      "x-fc-max-memory-usage": "51.14",
      "x-fc-request-id": "1-6624772d-0184a361-7a59b3115f69",
      "x-powered-by": "Express",
      "x-ratelimit-limit-requests": "5000",
      "x-ratelimit-limit-tokens": "160000",
      "x-ratelimit-remaining-requests": "4999",
      "x-ratelimit-remaining-tokens": "159724",
      "x-ratelimit-reset-requests": "12ms",
      "x-ratelimit-reset-tokens": "103ms"
    },
    "stack": "Error: 431 <html>\n  <head>\n    <title>Request Header Fields Too Large</title>\n  </head>\n  <body>\n    <h1><p>Request Header Fields Too Large</p></h1>\n    Error parsing headers: &#x27;limit request headers fields&#x27;\n  </body>\n</html>\n\n    at eE.generate (/app/.next/server/edge-chunks/311.js:4:1901)\n    at sx.makeStatusError (/app/.next/server/edge-chunks/311.js:4:14205)\n    at sx.makeRequest (/app/.next/server/edge-chunks/311.js:4:15128)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.chat (/app/.next/server/edge-chunks/797.js:1:8764)\n    at async /app/.next/server/app/api/chat/[provider]/route.js:1:1544\n    at async /app/.next/server/edge-chunks/811.js:6:64200\n    at async O.execute (/app/.next/server/edge-chunks/811.js:6:61093)\n    at async O.handle (/app/.next/server/edge-chunks/811.js:6:65467)\n    at async ey.handler (/app/.next/server/edge-chunks/811.js:7:31644)",
    "status": 431
  },
  "endpoint": "https://chatgpt-southeast-1.fc****pp.run/v1",
  "provider": "openai"
}

**Comment by gaye746560359** [comment]
![image](https://github.com/lobehub/lobe-chat/assets/3060035/2e403351-9b7b-4b34-947e-a7f87eb79c5e)

**Comment by gaye746560359** [comment]
经测试，是带fc的gpt-3.5turbo系列模型无法正常使用

**Comment by arvinxx** [comment]
@gaye746560359 是api原版吗？ 逆向ChatGPT 是不支持 fc 的

**Comment by gaye746560359** [comment]
> @gaye746560359 是api原版吗？ 逆向ChatGPT 是不支持 fc 的

是原版的api key

**Comment by gaye746560359** [comment]
> 160000

通过报错信息能看出问题吗？因为带fc的模型报错导致用不了插件，体验少了一大截

**Comment by arvinxx** [comment]
能否discord上私戳我，我帮你看看？ 我这边测试好像没问题。可能需要借用你的key复现一下试试

**Comment by gaye746560359** [comment]
> > 机器人检测到问题正文的语言不是英语，会自动翻译。 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> > @gaye746560359是原来的API吗？反向ChatGPT不支持fc
> 
> 这是原始的 api 密钥



> 能否discord上私戳我，我帮你看看？ 我这边测试好像没问题。可能需要借用你的key复现一下试试

我刚去创建新的api key发现openai已经启用新的项目api key。我重新创建新的key测试lobechat通过啦。属实意外之旅，感谢
