### ISSUE TITLE
[Bug]  Attempt to export a nullable value for "TextDecoderStream"

### ISSUE THREAD

**Issue by JasonFlyBeauty** [lobehub/lobe-chat#2256]
### 💻 Operating System

Windows

### 📦 Environment

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

(base) PS G:\lobe-chat> bun run dev
$ next dev -p 3010
   ▲ Next.js 14.1.4
   - Local:        http://localhost:3010

 ✓ Ready in 6.4s
 ○ Compiling /trpc/[trpc] ...
 ✓ Compiled /trpc/[trpc] in 2.2s (253 modules)
 ⨯ error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (file://G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:1)
      at addPrimitives (file://G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:13902:25)
      at extend (file://G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:13854:113)
      at new VM (file://G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:13946:88)
      at new EdgeVM (file://G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:13854:16)
      at file://G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:96:163

 ○ Compiling /_error ...
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38
1 | (()=>{var __webpack_modules__={45:e=>{e.exports='"use strict";\nvar __defProp = Object.defineProperty;\nvar __getOwnPropDesc = Object.getOwnPropertyDescriptor;\nvar __getOwnPropNames = Object.getOwnPropertyNames;\nvar __hasOwnProp = Object.prototype.hasOwnProperty;\nvar __name = (target, value) => __defProp(target, "name", { value, configurable: true });\nvar __export = (target, all) => {\n  for (var name in all)\n    __defProp(target, name, { get: all[name], enumerable: true });\n};\nvar __copyProps = (to, from, except, desc) => {\n  if (from && typeof from === "object" || typeof from === "function") {\n    for (let key of __getOwnPropNames(from))\n      if (!__hasOwnProp.call(to, key) && key !== except)\n        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });\n  }\n  return to;\n};\nvar __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);\n\n// src/primitives/abort-controller.js\nvar abort_controller_expor | ... truncated 

error: Attempt to export a nullable value for "TextDecoderStream"
      at defineProperties (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:711758)
      at addPrimitives (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:710442)
      at extend (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705225)
      at new VM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:712552)
      at new EdgeVM (G:\lobe-chat\node_modules\next\dist\compiled\edge-runtime\index.js:1:705155)
      at G:\lobe-chat\node_modules\next\dist\server\web\sandbox\context.js:208:38

### 📷 Recurrence Steps

git clone https://github.com/lobehub/lobe-chat.git
cd lobe-chat
powershell -c "irm bun.sh/install.ps1|iex"
bun i
bun install tree-sitter-yaml
bun i
bun run dev

**Comment by JasonFlyBeauty** [comment]
Recurrence Steps：

1：git clone https://github.com/lobehub/lobe-chat.git
2：cd lobe-chat
3：powershell -c "irm bun.sh/install.ps1|iex"
4：bun i

error：
```
warn: incorrect peer dependency "stylelint@15.11.0"

warn: incorrect peer dependency "stylelint@15.11.0"

warn: incorrect peer dependency "stylelint@15.11.0"

warn: incorrect peer dependency "stylelint@15.11.0"

warn: incorrect peer dependency "@octokit/core@5.2.0"
  ⚙️  sharp [5/7]

prebuild-install warn install No prebuilt binaries found (target=21.6.0 runtime=node arch=x64 libc= platform=win32)
gyp info it worked if it ends with ok
gyp info using node-gyp@10.1.0
gyp info using node@21.6.0 | win32 | x64
gyp info find Python using Python version 3.11.3 found at "D:\Users\s3183\AppData\Local\Programs\Python\Python311\python.exe"
gyp http GET https://nodejs.org/dist/v21.6.0/node-v21.6.0-headers.tar.gz
gyp http 200 https://nodejs.org/dist/v21.6.0/node-v21.6.0-headers.tar.gz
gyp ERR! error while extracting tarball TAR_ENTRY_ERROR Invalid argument
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: There was a fatal problem while downloading/extracting the tarball
gyp ERR! stack at <anonymous> (G:\lobe-chat\node_modules\node-gyp\lib\install.js:169:28)
gyp ERR! stack at processTicksAndRejections (:12:39)
gyp ERR! System Windows_NT 10.0.22000
gyp ERR! command "C:\\Users\\s3183\\AppData\\Local\\Temp\\bun-node-b257a3097\\node.exe" "G:\\lobe-chat\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd G:\lobe-chat\node_modules\tree-sitter
gyp ERR! node -v v21.6.0
gyp ERR! node-gyp -v v10.1.0
gyp ERR! not ok

error: install script from "tree-sitter" exited with 1
```

5：bun install tree-sitter-yaml
6：bun i
7：bun run dev

error：
Attempt to export a nullable value for "TextDecoderStream"

**Comment by arvinxx** [comment]
@JasonFlyBeauty try to use `pnpm` ?

**Comment by JasonFlyBeauty** [comment]
> @JasonFlyBeauty try to use `pnpm` ?
Thanks, pnpm was able to deploy successfully!
