### ISSUE TITLE
[Bug]  使用Azure模型，不可以调用插件。

### ISSUE THREAD

**Issue by silvonli** [lobehub/lobe-chat#2541]
### 💻 系统环境

macOS

### 📦 部署环境

Vercel / Zeabur / Sealos

### 🌐 浏览器

Chrome

### 🐛 问题描述

在设置 Azure openAI 模型后，可以正常聊天，但如果使用插件，则回复内容为空。

在 Vercel 上查看日志，发现“/api/chat/openai”请求报错，提示 API key 不正确。

我没有开通openAI官方API，所以只在设置中开启了Azure模型，为什么会提示openAI API key不正确？

/api/chat/openai 报错信息：
```
Route: [openai] NoOpenAIAPIKey:  Error: 401 Incorrect API key provided: 16ed9055********************5c76. You can find your API key at https://platform.openai.com/account/api-keys.
    at (node_modules/openai/error.mjs:44:0)
    at (node_modules/openai/core.mjs:256:23)
    at (node_modules/openai/core.mjs:299:0)
    at (src/libs/agent-runtime/utils/openaiCompatibleFactory/index.ts:82:25)
    at (src/app/api/chat/[provider]/route.ts:38:11)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:207:0)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:122:0)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:269:0)
    at (node_modules/next/dist/esm/server/web/edge-route-module-wrapper.js:81:0)
    at (node_modules/next/dist/esm/server/web/adapter.js?9fa3:158:0) {
  status: 401,
  headers: {
  connection: 'keep-alive',
  content-length: '282',
  content-type: 'application/json; charset=utf-8',
  date: 'Fri, 17 May 2024 02:41:42 GMT',
  set-cookie: '_cfuvid=I8qBt8Yf.vKjFeaTAGw1CMGdSOf4gBb5Zww2Hzyx.pw-1715913702785-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None',
  strict-transport-security: 'max-age=15724800; includeSubDomains',
  vary: 'Origin',
  x-request-id: 'req_098596ece612a9895f0b1b18fecbbec0'
},
  request_id: 'req_098596ece612a9895f0b1b18fecbbec0',
  error: {
  message: 'Incorrect API key provided: 16ed9055********************5c76. You can find your API key at https://platform.openai.com/account/api-keys.',
  type: 'invalid_request_error',
  param: null,
  code: 'invalid_api_key'
},
  code: 'invalid_api_key',
  param: null,
  type: 'invalid_request_error'
}
```

### 🚦 期望结果

希望 Azure openAI 模型可以正常使用插件。

### 📷 复现步骤

<img width="1384" alt="截屏2024-05-17 12 07 37" src="https://github.com/lobehub/lobe-chat/assets/1960080/b6ae6be2-d695-4021-94c1-289e688f1838">

### 📝 补充信息
版本号：v0.159.12

**Comment by shog86** [comment]
> 你这个报错可能是因为它要用OpenAI的3.5自动重命名，所以报的错。换句话说，这个报错和插件回复不显示没有关系

在issue里搜Azure，已经陆续有好几位遇到Azure下插件用不了的情况了，希望能尽快修复，感谢

https://github.com/lobehub/lobe-chat/issues/2689
