### ISSUE TITLE
[Bug] 助理推荐无法加载

### ISSUE THREAD

**Issue by kaliCYH** [lobehub/lobe-chat#2740]
### 📦 Environment

- [ ] Official
- [ ] Official Preview
- [X] Vercel / Zeabur / Sealos
- [X] Docker
- [ ] Other

### 📌 Version

0.162.11

### 💻 Operating System

- [ ] Windows
- [ ] macOS
- [ ] Ubuntu
- [ ] Other Linux
- [ ] iOS
- [ ] Android
- [ ] Other

### 🌐 Browser

- [ ] Chrome
- [ ] Edge
- [ ] Safari
- [ ] Firefox
- [ ] Other

### 🐛 Bug Description

![90e5147cf5350047487fb910cc18c34](https://github.com/lobehub/lobe-chat/assets/34980061/6eb4e5f0-a4aa-4a04-a053-5abe390a89cd)
![521688f931916050c34120a00063893](https://github.com/lobehub/lobe-chat/assets/34980061/9e82c614-af8a-44e1-a820-4cc3806a4ea9)

### 📷 Recurrence Steps

国内访问不了好像？
chat-agents.lobehub.com，chat-plugins.lobehub.com
国内机 docker部署

⨯ Error: fetch failed
at context.fetch (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/context.js:292:38)
at s (/app/.next/server/edge-chunks/398.js:6:45699)
at L (/app/.next/server/edge-chunks/398.js:6:138327)
at /app/.next/server/edge-chunks/398.js:6:140548
at async T (/app/.next/server/app/api/plugin/store/route.js:1:850)
at async /app/.next/server/edge-chunks/398.js:6:128477
at async M.execute (/app/.next/server/edge-chunks/398.js:6:126734)
at async M.handle (/app/.next/server/edge-chunks/398.js:6:129744)
at async ex.handler (/app/.next/server/edge-chunks/398.js:7:32671)
at async D (/app/.next/server/edge-chunks/398.js:7:3663) {
cause: Error: getaddrinfo EAI_AGAIN chat-plugins.lobehub.com
at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
errno: -3001,
code: 'EAI_AGAIN',
syscall: 'getaddrinfo',
hostname: 'chat-plugins.lobehub.com'
}
}
⨯ Error: fetch failed
at context.fetch (/app/node_modules/.pnpm/next@14.2.3_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/context.js:292:38)
at s (/app/.next/server/edge-chunks/398.js:6:45699)
at L (/app/.next/server/edge-chunks/398.js:6:138327)
at /app/.next/server/edge-chunks/398.js:6:140548
at async c (/app/.next/server/app/api/market/route.js:1:660)
at async /app/.next/server/edge-chunks/398.js:6:128477
at async M.execute (/app/.next/server/edge-chunks/398.js:6:126734)
at async M.handle (/app/.next/server/edge-chunks/398.js:6:129744)
at async ex.handler (/app/.next/server/edge-chunks/398.js:7:32671)
at async D (/app/.next/server/edge-chunks/398.js:7:3663) {
cause: Error: getaddrinfo EAI_AGAIN chat-agents.lobehub.com
at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
errno: -3001,
code: 'EAI_AGAIN',
syscall: 'getaddrinfo',
hostname: 'chat-agents.lobehub.com'
}
}

**Comment by arvinxx** [comment]
网络问题

**Comment by kicool-x** [comment]
我也遇到了同样的问题，我使用了服务器版本的脚本进行部署，
部署完成后，助手无法加载。虚拟机可以ping通。请问要如何处理？
PING chat-plugins.lobehub.com (172.67.164.80) 56(84) bytes of data.
64 bytes from 172.67.164.80: icmp_seq=1 ttl=55 time=4.77 ms
64 bytes from 172.67.164.80: icmp_seq=2 ttl=55 time=4.53 ms
64 bytes from 172.67.164.80: icmp_seq=3 ttl=55 time=4.52 ms
64 bytes from 172.67.164.80: icmp_seq=4 ttl=55 time=4.35 ms
64 bytes from 172.67.164.80: icmp_seq=5 ttl=55 time=4.76 ms
64 bytes from 172.67.164.80: icmp_seq=6 ttl=55 time=4.20 ms
64 bytes from 172.67.164.80: icmp_seq=7 ttl=55 time=4.97 ms
64 bytes from 172.67.164.80: icmp_seq=8 ttl=55 time=4.94 ms
64 bytes from 172.67.164.80: icmp_seq=9 ttl=55 time=4.39 ms
^C
