### ISSUE TITLE
[Bug] S3 上传图片预览链接有误

### ISSUE THREAD

**Issue by sxjeru** [lobehub/lobe-chat#2920]
### 📦 部署环境

Vercel

### 📌 软件版本

1.0.7

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

假设配置了 lobe.chat 与 s3.com 两个网站。lobe.chat 是主站，s3.com 是 S3 站点。
当上传图片后，其在文本预览框的链接为 lobe.chat/s3.com/xxx，多了前面的 `lobe.chat/` 部分，导致图片无法加载。

此外 Cloudflare R2 给出的链接中的斜杠是“%2F”，不应将其解析为“/”。
（比如 #2918 的报错图，实际上将 %2F 解析掉了，至少直接放浏览器是无法访问的，报 404 。）

**Comment by arvinxx** [comment]
你是不是配置错了？

**Comment by sxjeru** [comment]
第一个问题解决了，确实是 NEXT_PUBLIC_S3_DOMAIN 少了前面的 https 导致的。
第二个问题也确认存在，报 404 。

**Comment by AiharaMahiru** [comment]
![screen](https://github.com/lobehub/lobe-chat/assets/124856966/3047e73b-d510-4045-a0dd-c5136e5f06ca)
这是我的配置信息（已处理），当我上传文件时，遇到“文件上传失败，请检查网络连接或稍后再试
详情: TRPCClientError: UNAUTHORIZED”的错误，日志为
'''
[POST] [middleware: "src/middleware"] /trpc/edge/upload.createS3PreSignedUrl status=200
[POST] /trpc/edge/upload.createS3PreSignedUrl?batch=1&nxtPtrpc=upload.createS3PreSignedUrl status=401
Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl
 TRPCError: UNAUTHORIZED
    at (src/libs/trpc/middleware/password.ts:21:12)
    at (node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:0)
    at (node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:182:0)
    at (node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:137:0)
    at (node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:195:0)
    at (node_modules/@trpc/server/dist/adapters/fetch/fetchRequestHandler.mjs:32:0)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:195:0)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:124:0)
    at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:257:0) {
  code: 'UNAUTHORIZED',
  name: 'TRPCError'
}
'''

**Comment by rohman13** [comment]
> > Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿
> 
> ![screen](https://private-user-images.githubusercontent.com/124856966/341692445-3047e73b-d510-4045-a0dd-c5136e5f06ca.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMzQyNDIsIm5iZiI6MTcyMjMzMzk0MiwicGF0aCI6Ii8xMjQ4NTY5NjYvMzQxNjkyNDQ1LTMwNDdlNzNiLWQ1MTAtNDA0NS1hMGRkLWM1MTM2ZTVmMDZjYS5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMFQxMDA1NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGFjMzRmZGI3OTA4NWUyODNhYTdlOTZlODQ5ZmU2MjYwMzA0NGU5YzBhMGFlYmM4MWViOTNhNmRkZTIzMDFjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hqSflNU5I8ExxBir2GQ82JxdWI0VJvqEZGo2mbbDOGI) This is my configuration information (processed), when I upload a file, I encounter "File upload failed, please check the network connection or try again later Details: TRPCClientError: UNAUTHORIZED" error, the log is ''' [POST] [middleware: "src/middleware"] /trpc/edge/upload.createS3PreSignedUrl status=200 [POST] /trpc/edge/upload.createS3PreSignedUrl?batch=1&nxtPtrpc=upload.createS3PreSignedUrl status=401 Error in tRPC handler (edge) on path: upload.createS3PreSignedUrl TRPCError: UNAUTHORIZED at (src/libs/trpc/middleware/password.ts:21:12) at (node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:152:0) at (node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:182:0) at (node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:137:0) at (node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:195:0) at (node_modules/@trpc/server/dist/adapters/fetch/fetchRequestHandler.mjs:32:0) at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:195:0) at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:124:0) at (node_modules/next/dist/esm/server/future/route-modules/app-route/module.js:257:0) { code: 'UNAUTHORIZED', name: 'TRPCError' } '''

you should add ACCESS_CODE to env variable and then input same access code on setting
