### ISSUE TITLE
[Bug] Error 程序崩溃

### ISSUE THREAD

**Issue by ganxiaozhe** [lobehub/lobe-chat#3016]
### 📦 Environment

Docker

### 📌 Version

v1.1.7

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

当进行过一次对话后，几乎任意操作都会触发崩溃。
这包括：继续对话、切换对话、清除对话、新建对话、删除对话、修改对话模型等。

### 📝 Additional Information

```
2024-06-25 00:25:54   ▲ Next.js 14.2.4
2024-06-25 00:25:54   - Local:        http://localhost:3210
2024-06-25 00:25:54   - Network:      http://0.0.0.0:3210
2024-06-25 00:25:54 
2024-06-25 00:25:54  ✓ Starting...
2024-06-25 00:25:54  ✓ Ready in 29ms
2024-06-25 00:26:36  ⨯ Error: fetch failed
2024-06-25 00:26:36     at context.fetch (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/sandbox/context.js:292:38)
2024-06-25 00:26:36     at i (/app/.next/server/edge-chunks/614.js:6:45699)
2024-06-25 00:26:36     at D (/app/.next/server/edge-chunks/614.js:6:75680)
2024-06-25 00:26:36     at /app/.next/server/edge-chunks/614.js:6:77901
2024-06-25 00:26:36     at /app/.next/server/edge-chunks/614.js:6:83830
2024-06-25 00:26:36     at a.with (/app/.next/server/edge-chunks/614.js:1:11313)
2024-06-25 00:26:36     at l.with (/app/.next/server/edge-chunks/614.js:1:5513)
2024-06-25 00:26:36     at l.startActiveSpan (/app/.next/server/edge-chunks/614.js:1:20565)
2024-06-25 00:26:36     at a.startActiveSpan (/app/.next/server/edge-chunks/614.js:1:21099)
2024-06-25 00:26:36     at /app/.next/server/edge-chunks/614.js:6:83377 {
2024-06-25 00:26:36   cause: Error: AggregateError
2024-06-25 00:26:36       at makeNetworkError (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:7365:35)
2024-06-25 00:26:36       at httpNetworkFetch (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:12125:16)
2024-06-25 00:26:36       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-06-25 00:26:36       at async httpNetworkOrCacheFetch (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:12000:33)
2024-06-25 00:26:36       at async httpFetch (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11837:37)
2024-06-25 00:26:36       at async schemeFetch (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11762:18)
2024-06-25 00:26:36       at async eval (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11635:20)
2024-06-25 00:26:36       at async mainFetch (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.2.4_@babel+core@7.23.6_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:11625:20)
2024-06-25 00:26:36 }
```

**Comment by arvinxx** [comment]
截图看下

**Comment by ganxiaozhe** [comment]
![lobechat-error](https://github.com/lobehub/lobe-chat/assets/37825446/9c0b10e1-2729-43af-8159-87af37ed60e9)
先前遇到的崩溃都是上面截图这种。在录复现视频的时候，又出现了另外两种崩溃形式。

视频：[https://gxz-dev.oss-cn-beijing.aliyuncs.com/tmp/lobechat-errors.mp4](https://gxz-dev.oss-cn-beijing.aliyuncs.com/tmp/lobechat-errors.mp4)

**Comment by MoonWeSif** [comment]
> ![lobechat-error](https://private-user-images.githubusercontent.com/37825446/342436798-9c0b10e1-2729-43af-8159-87af37ed60e9.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk2MzUzODIsIm5iZiI6MTcxOTYzNTA4MiwicGF0aCI6Ii8zNzgyNTQ0Ni8zNDI0MzY3OTgtOWMwYjEwZTEtMjcyOS00M2FmLTgxNTktODdhZjM3ZWQ2MGU5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI5VDA0MjQ0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YjNhN2EzMjQ1ZTJkMWUyNDkxY2Q0Zjk0ZGQ2NzA1OGU3NDY2NTRhNDIxNTFjMDgyYjdjODYxNTAyYjBmN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RSGbHbfwTuuXTgmgidke-Ao-Ev3-CCt-jzMNfnegMdk) 先前遇到的崩溃都是上面截图这种。在录复现视频的时候，又出现了另外两种崩溃形式。
> 
> 视频：https://gxz-dev.oss-cn-beijing.aliyuncs.com/tmp/lobechat-errors.mp4

我遇到了和你同样的情况，只不过我并不是在聊天的时候遇到的，我是在某次打开时突然这样的，我刚刚解决了这个问题。

你可以尝试关闭某些浏览器插件（包括篡改猴等第三方插件管理器中的插件），我关闭了几个在此页面生效的插件后，就恢复正常了

**Comment by arvinxx** [comment]
还能复现吗

**Comment by arvinxx** [comment]
@ganxiaozhe 最新版还有出现吗？

**Comment by ganxiaozhe** [comment]
> @ganxiaozhe 最新版还有出现吗？

没有出现该问题，但经常性会遇到客户端请求出错的问题（已排除 API 方问题），例如：

```
请求 OpenAI 服务出错，请根据以下信息排查或重试

{
  "error": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "api.aihubmix.com"
    }
  },
  "endpoint": "https://api.ai****ix.com/v1",
  "provider": "openai"
}
```

**Comment by arvinxx** [comment]
@hezhijie0327 这个是不是 docker 镜像的问题？ 看着像是网址没解析对？

**Comment by hezhijie0327** [comment]
@arvinxx 应该是 DNS 问题（可能解析不稳定，当时的解析结果为空或错误），我刚刚拿 AGH 模拟了下 DNS 域名拦截，能复现问题，但使用情景应该不是在客户端模式下，见下方错误日志

```
服务器请求（直连）问题复现

请求 OpenAI 服务出错，请根据以下信息排查或重试
{
  "error": {
    "cause": {
      "errno": -3008,
      "code": "ENOTFOUND",
      "syscall": "getaddrinfo",
      "hostname": "api.deepbricks.ai"
    }
  },
  "endpoint": "https://api.de****ks.ai/v1",
  "provider": "openai"
}
```
```
客户端模式

请求 OpenAI 服务出错，请根据以下信息排查或重试
{
  "error": {},
  "endpoint": "https://api.de****ks.ai/v1",
  "provider": "openai"
}
```
```
服务器请求（代理模式 - HTTP Proxy）

请求 OpenAI 服务出错，请根据以下信息排查或重试
{
  "error": {
    "cause": {
      "code": "ECONNRESET",
      "host": "api.deepbricks.ai",
      "port": 443,
      "localAddress": null
    }
  },
  "endpoint": "https://api.de****ks.ai/v1",
  "provider": "openai"
}
```

**Comment by arvinxx** [comment]
@hezhijie0327 我看有人说用 alpine 的镜像就会有这个问题。dns 解释报错普遍吗？

**Comment by hezhijie0327** [comment]
@arvinxx 看上去得添加个 `bind-tools` 包，我过会儿提个 PR

ref: https://github.com/nodejs/docker-node/issues/339
