### ISSUE TITLE
[Bug] docker database 版 Auth0 异常

### ISSUE THREAD

**Issue by xudongyss** [lobehub/lobe-chat#3421]
### 📦 Environment

Docker

### 📌 Version

1.9.4

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

[32m[1m✓[22m[39m Starting...
[32m[1m✓[22m[39m Ready in 181ms
[31m[31m[auth][error][0m TypeError: fetch failed[39m
[31m at node:internal/deps/undici/undici:13178:13
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async ia (/app/.next/server/chunks/7247.js:362:40635)
at async ic (/app/.next/server/chunks/7247.js:362:43270)
at async ip (/app/.next/server/chunks/7247.js:362:45903)
at async im (/app/.next/server/chunks/7247.js:362:49738)
at async /app/node_modules/.pnpm/next@14.2.5_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
at async eR.execute (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
at async eR.handle (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512)
at async doRender (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1377:42)[39m
[NextAuth] Error: {
cause: [32m'Configuration'[39m,
message: [32m'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.'[39m,
name: [32m'NextAuth Error'[39m
}

**Comment by arvinxx** [comment]
配置有问题吧

**Comment by xudongyss** [comment]
> NextAuth 配置有问题吧

没有吧，昨天点登陆注册，点开过一次，之后就点不开了。
今天在试，一会提示异常，一会儿莫名其妙的登陆成功了。

**Comment by cy948** [comment]
在中国大陆境内有时候请求auth0 endpoint会失败，建议：
- 多次进行登录重试；
- 在服务端使用代理或更改docker部署地域；
- 更改auth0实例的地域。

**Comment by xudongyss** [comment]
> 在中国大陆境内有时候请求auth0 endpoint会失败，建议：
> 
> * 多次进行登录重试；
> * 在服务端使用代理或更改docker部署地域；
> * 更改auth0实例的地域。

auth0实例的地域怎么修改？
