### ISSUE TITLE
[Bug] 服务器数据库版 S3 使用 minio 报错

### ISSUE THREAD

**Issue by xudongyss** [lobehub/lobe-chat#3452]
### 📦 Environment

Other

### 📌 Version

1.9.6

### 💻 Operating System

Other Linux

### 🌐 Browser

Chrome

### 🐛 Bug Description

> @lobehub/chat@1.9.6 start
> next start -p 3210

▲ Next.js 14.2.5
- Local: http://localhost:3210

✓ Starting...
✓ Ready in 2.6s
{"level":30,"time":1723456455069,"pid":2614202,"hostname":"localhost.localdomain","msg":"Error in tRPC handler (lambda) on path: session.getSessionConfig, type: query"}
a [TRPCError]: UNAUTHORIZED
at /data/www/wwwroot/lobe-chat-test/.next/server/app/trpc/lambda/[trpc]/route.js:6:9664
at t (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/94376.js:1:2180)
at r (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/94376.js:1:2519)
at /data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:1:7099
at Array.map (<anonymous>)
at P (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:1:6623)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async T (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:5:4668)
at async /data/www/wwwroot/lobe-chat-test/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
at async eR.execute (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874) {
code: 'UNAUTHORIZED',
[cause]: undefined
}
a [TRPCError]: UNAUTHORIZED
at /data/www/wwwroot/lobe-chat-test/.next/server/app/trpc/lambda/[trpc]/route.js:6:9664
at t (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/94376.js:1:2180)
at r (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/94376.js:1:2519)
at /data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:1:7099
at Array.map (<anonymous>)
at P (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:1:6623)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async T (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:5:4668)
at async /data/www/wwwroot/lobe-chat-test/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
at async eR.execute (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874) {
code: 'UNAUTHORIZED',
[cause]: undefined
}
{"level":30,"time":1723456455073,"pid":2614202,"hostname":"localhost.localdomain","msg":"Error in tRPC handler (lambda) on path: file.findById, type: query"}
{"level":30,"time":1723456455769,"pid":2614202,"hostname":"localhost.localdomain","msg":"Error in tRPC handler (lambda) on path: message.createMessage, type: mutation"}
a [TRPCError]: UNAUTHORIZED
at /data/www/wwwroot/lobe-chat-test/.next/server/app/trpc/lambda/[trpc]/route.js:6:9664
at t (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/94376.js:1:2180)
at r (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/94376.js:1:2519)
at /data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:1:7099
at Array.map (<anonymous>)
at P (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:1:6623)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async T (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:5:4668)
at async /data/www/wwwroot/lobe-chat-test/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
at async eR.execute (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874) {
code: 'UNAUTHORIZED',
[cause]: undefined
}
a [TRPCError]: UNAUTHORIZED
at /data/www/wwwroot/lobe-chat-test/.next/server/app/trpc/lambda/[trpc]/route.js:6:9664
at t (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/94376.js:1:2180)
at r (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/94376.js:1:2519)
at /data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:1:7099
at Array.map (<anonymous>)
at P (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:1:6623)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async T (/data/www/wwwroot/lobe-chat-test/.next/server/chunks/41704.js:5:4668)
at async /data/www/wwwroot/lobe-chat-test/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
at async eR.execute (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874) {
code: 'UNAUTHORIZED',
[cause]: undefined
}
{"level":30,"time":1723456455770,"pid":2614202,"hostname":"localhost.localdomain","msg":"Error in tRPC handler (lambda) on path: message.removeMessages, type: mutation"}
⨯ Error: failed to pipe response
at pipeToNodeResponse (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/server/pipe-readable.js:126:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async NextNodeServer.runEdgeFunction (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/server/next-server.js:1250:13)
at async NextNodeServer.handleCatchallRenderRequest (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/server/next-server.js:248:37)
at async NextNodeServer.handleRequestImpl (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/server/base-server.js:816:17)
at async invokeRender (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/server/lib/router-server.js:174:21)
at async handleRequest (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/server/lib/router-server.js:353:24)
at async requestHandlerImpl (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/server/lib/router-server.js:377:13)
at async Server.requestListener (/data/www/wwwroot/lobe-chat-test/node_modules/next/dist/server/lib/start-server.js:141:13) {
[cause]: ValidationException: messages.0.content.1.image.source.base64.media_type: Input should be 'image/jpeg', 'image/png', 'image/gif' or 'image/webp'
at et (/data/www/wwwroot/lobe-chat-test/.next/server/edge-chunks/46.js:4:45625)
at ec (/data/www/wwwroot/lobe-chat-test/.next/server/edge-chunks/46.js:4:46700)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async /data/www/wwwroot/lobe-chat-test/.next/server/edge-chunks/46.js:4:46027
at async _.deserializer (/data/www/wwwroot/lobe-chat-test/.next/server/edge-chunks/994.js:16:11619)
at async _.asyncIterator (/data/www/wwwroot/lobe-chat-test/.next/server/edge-chunks/994.js:16:10150)
at async ea (/data/www/wwwroot/lobe-chat-test/.next/server/edge-chunks/765.js:9:9914)
at async Object.pull (/data/www/wwwroot/lobe-chat-test/.next/server/edge-chunks/46.js:172:9744) {
'$fault': 'client',
'$metadata': {
httpStatusCode: undefined,
requestId: undefined,
extendedRequestId: undefined,
cfId: undefined
}
}
}
Error: aborted
at abortIncoming (node:_http_server:797:17)
at socketOnClose (node:_http_server:791:3)
at Socket.emit (node:events:531:35)
at Socket.emit (node:domain:488:12)
at TCP.<anonymous> (node:net:338:12)
at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
code: 'ECONNRESET'
}

**Comment by ImZhangAo** [comment]
Me too, Hope it can be repaired as soon as possible.

**Comment by ImZhangAo** [comment]
You need to configure the external authentication service Clerk or Next Auth.

**Comment by xudongyss** [comment]
> You need to configure the external authentication service Clerk or Next Auth.
配了 Clerk

**Comment by xudongyss** [comment]
> You need to configure the external authentication service Clerk or Next Auth.

配了 Clerk

**Comment by wcu1117** [comment]
我使用了自定义的微信授权登录成功之后，接入postsql也出现了这个问题。
`userAuth {
  ctx: {
    authorizationHeader: null,
    clerkAuth: undefined,
    nextAuth: undefined,
    userId: undefined
  },
  type: 'query',
  path: 'user.getUserState',
  getRawInput: [AsyncFunction: getRawInput],
  meta: undefined,
  input: undefined,
  next: [Function: next]
}
{"level":30,"time":1724226070415,"pid":29716,"hostname":"鍗庡","msg":"Error in tRPC handler (lambda) on path: user.getUserState, type: query"}
TRPCError: UNAUTHORIZED
    at eval (webpack-internal:///(rsc)/./src/libs/trpc/middleware/userAuth.ts:14:15)
    at callRecursive (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:160:38)
    at procedure (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/procedureBuilder.mjs:190:30)
    at eval (webpack-internal:///(rsc)/./node_modules/@trpc/server/dist/unstable-core-do-not-import/http/resolveResponse.mjs:207:36)
    at Array.map (<anonymous>)
`

**Comment by arvinxx** [comment]
自定义问题不接受答疑
