### ISSUE TITLE
[Bug] docker database版本表结构创建问题

### ISSUE THREAD

**Issue by coulsontl** [lobehub/lobe-chat#3489]
### 📦 Environment

Docker

### 📌 Version

最新

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

首先我使用普通的镜像 `lobehub/lobe-chat:latest` 然后在环境变量里设置
```
- NEXT_PUBLIC_SERVICE_MODE=server
- DATABASE_DRIVER=node
```
这时候启动之后并不会自动生成表结构，登录后日志提示 `error: relation "nextauth_accounts" does not exist` 没有生成表结构

下面我换了一个镜像 `lobehub/lobe-chat-database:latest` 神奇的事情发生了，这个镜像自动生成了表结构，日志的开头也有了提示：
```
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.5
```
还没高兴多久，这个镜像在我登录的时候提示报错了。
```
[auth][error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ia (/app/.next/server/chunks/7247.js:362:40635)
    at async ic (/app/.next/server/chunks/7247.js:362:43270)
    at async ip (/app/.next/server/chunks/7247.js:362:45903)
    at async im (/app/.next/server/chunks/7247.js:362:49738)
    at async /app/node_modules/.pnpm/next@14.2.5_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
    at async eR.execute (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
    at async eR.handle (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512)
    at async doRender (/app/node_modules/.pnpm/next@14.2.5_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1377:42)
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
```
PS: 参考这个issue: https://github.com/lobehub/lobe-chat/issues/3421#issuecomment-2283591379 我怀疑是database镜像没有实现PROXY_URL这个环境变量导致的(我是在国内部署的所以需要使用代理)

这时候我又想起来开头的镜像，于是我又切换回镜像 `lobehub/lobe-chat:latest` ，

下面奇迹发生了，切回去之后可以正常登录了且没有任何报错。所以DB版本的正确使用方法是：
* 先使用 `lobe-chat-database` 来自动生成表结构
* 再切换回 `lobehub/lobe-chat:latest` 才能正常使用

我感觉这应该是个bug，2个镜像必须配合使用，单独使用任何一个都用不了

**Comment by arvinxx** [comment]
1. lobe-chat 镜像不是为了 database 模式做的。因此你用 lobe-chat 镜像期望达成 database 的效果是做不到的，要用服务端数据库必须要用 lobe-chat-database 镜像；
2. 你提到的 TypeError: fetch failed 大概率是网络问题，但 `PROXY_URL` 这个变量目前在 db 的镜像里是没有加进去， @hezhijie0327 你看下要不直接加到 https://github.com/lobehub/lobe-chat/pull/3471 这个 PR 里？

**Comment by hezhijie0327** [comment]
@arvinxx 加上了
