### ISSUE TITLE
[Bug] 升级 1.12.0 启动容器报错

### ISSUE THREAD

**Issue by LarkinZero** [lobehub/lobe-chat#3529]
### 📦 部署环境

Docker

### 📌 软件版本

1.12.0

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Edge

### 🐛 问题描述

[Database] Start to migration...
❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below:
error: could not open extension control file "/usr/share/postgresql/13/extension/vector.control": No such file or directory
    at /app/node_modules/.pnpm/pg@8.12.0/node_modules/pg/lib/client.js:526:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /app/node_modules/drizzle-orm/pg-core/dialect.cjs:60:13
    at async NodePgSession.transaction (/app/node_modules/drizzle-orm/node-postgres/session.cjs:141:22)
    at async PgDialect.migrate (/app/node_modules/drizzle-orm/pg-core/dialect.cjs:56:5)
    at async Object.migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.cjs:27:3)
    at async runMigrations (/app/docker.cjs:17:3) {
  length: 192,
  severity: 'ERROR',
  code: '58P01',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  routine: 'parse_extension_control_file'
  line: '538',
  file: 'extension.c',
}

### 📷 复现步骤

从 1.11.9 升级到 1.12.0
用 Portainer 重建功能升级最新镜像，启动时报错
DATABASE_URL是正确配置了的

### 🚦 期望结果

正常启动

### 📝 补充信息

无

**Comment by arvinxx** [comment]
https://github.com/lobehub/lobe-chat/issues/3527
