### ISSUE TITLE
[Bug] 上传文件失败

### ISSUE THREAD

**Issue by alphandbelt1** [lobehub/lobe-chat#3547]
### 📦 Environment

Other

### 📌 Version

1.12.2

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

上传文件的时候前端右上角提示Invaild Key length，其实已经上传成功了，但是没有对话的时候应该是没有识别到。
上传图片是ok的，可以正常上传，对话也能识别到

![image](https://github.com/user-attachments/assets/169a88c5-1541-4f61-8b24-31235bd62418)
![image](https://github.com/user-attachments/assets/57ce8b58-aa1a-401e-88eb-eb026ca97531)

**Comment by alphandbelt1** [comment]
> ### 📦 Environment
> Other
> 
> ### 📌 Version
> 1.12.2
> 
> ### 💻 Operating System
> Ubuntu
> 
> ### 🌐 Browser
> Chrome
> 
> ### 🐛 Bug Description
> 上传文件的时候前端右上角提示Invaild Key length，其实已经上传成功了，但是没有对话的时候应该是没有识别到。 上传图片是ok的，可以正常上传，对话也能识别到
> 
> ![image](https://private-user-images.githubusercontent.com/81293467/360318501-169a88c5-1541-4f61-8b24-31235bd62418.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDk5NDcsIm5iZiI6MTcyNDMwOTY0NywicGF0aCI6Ii84MTI5MzQ2Ny8zNjAzMTg1MDEtMTY5YTg4YzUtMTU0MS00ZjYxLThiMjQtMzEyMzViZDYyNDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA2NTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNzQxODEzYmQ4ZmE0YWM2ZGFhZjE3MTE4MzExMjVkMDJhZWE2OTRlZWU2M2Y1N2ViNTQzZjg1NTNlMjc5ZmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.91hAXOFg3v7ctg4ZchvpzcDDxaOR7xAdcuf-ypUATiI) ![image](https://private-user-images.githubusercontent.com/81293467/360318715-57ce8b58-aa1a-401e-88eb-eb026ca97531.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMDk5NDcsIm5iZiI6MTcyNDMwOTY0NywicGF0aCI6Ii84MTI5MzQ2Ny8zNjAzMTg3MTUtNTdjZThiNTgtYWExYS00MDFlLTg4ZWItZWIwMjZjYTk3NTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDA2NTQwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MzQzY2I2NzlkOTllNDcwYjM1M2ExMGZmZmIzOThhNjJhYzVkNmNkZDcwYmMyODQxZDBjOThjYWU0ZGNkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XRuPD8E_VnhBMl9uwF3_9la3iRy24RgZienDe4vZeIk)
> 
> ### 📷 Recurrence Steps
> _No response_
> 
> ### 🚦 Expected Behavior
> _No response_
> 
> ### 📝 Additional Information
> _No response_

 ✓ Ready in 894ms
{"level":30,"time":1724308860486,"pid":56002,"hostname":"0x01","msg":"Error in tRPC handler (lambda) on path: message.createMessage, type: mutation"}
error: insert or update on table "messages_files" violates foreign key constraint "files_to_messages_file_id_files_id_fk"
    at /home/ubuntu/Aiwork/lobe-chat-1.12.2/node_modules/.pnpm/pg@8.12.0/node_modules/pg/lib/client.js:526:17
    ... 8 lines matching cause stack trace ...
    at async t (/home/ubuntu/Aiwork/lobe-chat-1.12.2/.next/server/chunks/51222.js:1:5651) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: error: insert or update on table "messages_files" violates foreign key constraint "files_to_messages_file_id_files_id_fk"
      at /home/ubuntu/Aiwork/lobe-chat-1.12.2/node_modules/.pnpm/pg@8.12.0/node_modules/pg/lib/client.js:526:17
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /home/ubuntu/Aiwork/lobe-chat-1.12.2/.next/server/chunks/94512.js:5:21060
      at async m.transaction (/home/ubuntu/Aiwork/lobe-chat-1.12.2/.next/server/chunks/56506.js:27:9426)
      at async /home/ubuntu/Aiwork/lobe-chat-1.12.2/.next/server/chunks/94512.js:5:36616
      at async u.middlewares (/home/ubuntu/Aiwork/lobe-chat-1.12.2/.next/server/chunks/51222.js:1:5345)
      at async t (/home/ubuntu/Aiwork/lobe-chat-1.12.2/.next/server/chunks/51222.js:1:5651)
      at async t (/home/ubuntu/Aiwork/lobe-chat-1.12.2/.next/server/chunks/51222.js:1:5651)
      at async t (/home/ubuntu/Aiwork/lobe-chat-1.12.2/.next/server/chunks/51222.js:1:5651)
      at async t (/home/ubuntu/Aiwork/lobe-chat-1.12.2/.next/server/chunks/51222.js:1:5651) {
    length: 329,
    severity: 'ERROR',
    code: '23503',
    detail: 'Key (file_id)=(Snipaste_2024-08-21_15-44-53.png) is not present in table "files".',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    补充一下
