### ISSUE TITLE
[Bug] Issues with creating images using the DALL-E 3 plugin

### ISSUE THREAD

**Issue by bentwnghk** [lobehub/lobe-chat#3549]
File upload works fine, but there seems to be some issues with creating images using the DALL-E 3 plugin.
After generating the images, an error message pops up:
![螢幕擷取畫面 2024-08-22 120357](https://github.com/user-attachments/assets/80e822b9-b05a-4047-843f-e62024622288)

LobeChat docker log:
```
2024/08/22 12:03PM 30 pid=1 hostname=1f285d7e9362 msg=Error in tRPC handler (lambda) on path: file.createFile, type: mutation
error: null value in column "hash_id" of relation "global_files" violates not-null constraint
    at /app/node_modules/.pnpm/pg-pool@3.6.2_pg@8.12.0/node_modules/pg-pool/index.js:45:11
    ... 8 lines matching cause stack trace ...
    at async r (/app/.next/server/chunks/51222.js:1:5993) {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: error: null value in column "hash_id" of relation "global_files" violates not-null constraint
      at /app/node_modules/.pnpm/pg-pool@3.6.2_pg@8.12.0/node_modules/pg-pool/index.js:45:11
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /app/.next/server/chunks/56506.js:27:8157
      at async /app/.next/server/chunks/94512.js:5:27444
      at async u.middlewares (/app/.next/server/chunks/51222.js:1:5345)
      at async t (/app/.next/server/chunks/51222.js:1:5651)
      at async t (/app/.next/server/chunks/51222.js:1:5651)
      at async t (/app/.next/server/chunks/51222.js:1:5651)
      at async t (/app/.next/server/chunks/51222.js:1:5651)
      at async r (/app/.next/server/chunks/51222.js:1:5993) {
    length: 385,
    severity: 'ERROR',
    code: '23502',
    detail: 'Failing row contains (null, image/png, 3163266, files/478972/4d734af8-84bd-4ffc-8f94-0cb74c1fd45d.png, {"date": "478972", "path": "files/478972/4d734af8-84bd-4ffc-8f94..., 2024-08-22 04:03:33.753476+00).',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'global_files',
    column: 'hash_id',
    dataType: undefined,
    constraint: undefined,
    file: 'execMain.c',
    line: '2003',
    routine: 'ExecConstraints'
  }
}
```
PostgresDB docker log:
```
2024-08-21 19:00:33.409 UTC [1] LOG:  starting PostgreSQL 16.3 (Debian 16.3-1.pgdg120+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
2024-08-21 19:00:33.409 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
2024-08-21 19:00:33.409 UTC [1] LOG:  listening on IPv6 address "::", port 5432
2024-08-21 19:00:33.510 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
2024-08-21 19:00:33.618 UTC [29] LOG:  database system was shut down at 2024-08-21 19:00:11 UTC
2024-08-21 19:00:33.777 UTC [1] LOG:  database system is ready to accept connections
2024-08-21 19:00:47.668 UTC [36] FATAL:  password authentication failed for user "netdata"
2024-08-21 19:00:47.668 UTC [36] DETAIL:  Role "netdata" does not exist.
	Connection matched file "/var/lib/postgresql/data/pg_hba.conf" line 128: "host all all all scram-sha-256"
2024-08-21 19:05:33.711 UTC [27] LOG:  checkpoint starting: time
2024-08-21 19:05:33.846 UTC [27] LOG:  checkpoint complete: wrote 2 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.039 s, sync=0.011 s, total=0.136 s; sync files=3, longest=0.009 s, average=0.004 s; distance=0 kB, estimate=0 kB; lsn=0/1FC8A68, redo lsn=0/1FC8A30
2024-08-21 23:40:12.369 UTC [888] ERROR:  null value in column "hash_id" of relation "global_files" violates not-null constraint
2024-08-21 23:40:12.369 UTC [888] DETAIL:  Failing row contains (null, image/png, 3163267, files/478968/8cf70763-e060-47ba-be60-5431189e3d07.png, {"date": "478968", "path": "files/478968/8cf70763-e060-47ba-be60..., 2024-08-21 23:40:12.368935+00).
2024-08-21 23:40:12.369 UTC [888] STATEMENT:  insert into "global_files" ("hash_id", "file_type", "size", "url", "metadata", "created_at") values (default, $1, $2, $3, $4, default) returning "hash_id", "file_type", "size", "url", "metadata", "created_at"
2024-08-21 23:40:38.408 UTC [27] LOG:  checkpoint starting: time
2024-08-21 23:40:47.952 UTC [27] LOG:  checkpoint complete: wrote 95 buffers (0.6%); 0 WAL file(s) added, 0 removed, 1 recycled; write=9.431 s, sync=0.068 s, total=9.545 s; sync files=57, longest=0.012 s, average=0.002 s; distance=450 kB, estimate=450 kB; lsn=0/2039578, redo lsn=0/2039540
```

Oh it's a bug with Dalle plugin, I will fix it soon.

_Originally posted by @arvinxx in https://github.com/lobehub/lobe-chat/issues/3527#issuecomment-2303789469_

**Comment by mujiannan** [comment]
我检查了`src/server/routers/lambda/file.ts`中的`fileRouter`：
```TypeScript
      const { id } = await ctx.fileModel.create({
        fileHash: input.hash,
        fileType: input.fileType,
        knowledgeBaseId: input.knowledgeBaseId,
        metadata: input.metadata,
        name: input.name,
        size: input.size,
        url: input.url,
      });

      return { id, url: getFullFileUrl(input.url) };
```

以及`src/database/server/models/file.ts`中的`FileModel`：
```TypeScript
  createGlobalFile = async (file: Omit<NewGlobalFile, 'id' | 'userId'>) => {
    return serverDB.insert(globalFiles).values(file).returning();
  };

  checkHash = async (hash: string) => {
    const item = await serverDB.query.globalFiles.findFirst({
      where: eq(globalFiles.hashId, hash),
    });
    if (!item) return { isExist: false };

    return {
      fileType: item.fileType,
      isExist: true,
      metadata: item.metadata,
      size: item.size,
      url: item.url,
    };
```

检查`minio`发现，`DALLE.3`创建的图片上传成功了；检查`Postgres`发现，`global_files`中也生成了引用到正确文件的`hash_id`。
