### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by mt-altman** [lobehub/lobe-chat#3554]
### 📦 部署环境

Docker

### 📌 软件版本

lobehub / lobe-chat-database

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

项目启动失败，报错日志如下
`[Database] Start to migration...
❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below:
Error: self-signed certificate in certificate chain
    at /app/node_modules/.pnpm/pg-pool@3.6.2_pg@8.12.0/node_modules/pg-pool/index.js:45:11
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PgDialect.migrate (/app/node_modules/drizzle-orm/pg-core/dialect.cjs:50:5)
    at async Object.migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.cjs:27:3)
    at async runMigrations (/app/docker.cjs:17:3) {
  code: 'SELF_SIGNED_CERT_IN_CHAIN'`
  
  dataBaseUrl 以及配置仅 sslmode，不能解决问题
  `postgres://avnadmin:password@hostname:port/lobe_chat?sslmode=require
`

### 🚦 期望结果

支持配置项 来忽略证书链验证

**Comment by arvinxx** [comment]
这是你数据库安全证书问题吧？可能要自己想办法解决了，这个不在我们的问题范围内
