### ISSUE TITLE
[Bug] doc文件分块错误，文件内容包含文字图片等

### ISSUE THREAD

**Issue by ZeroDeng01** [lobehub/lobe-chat#3570]
### 📦 部署环境

Vercel

### 📌 软件版本

1.12.9

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

doc文件分块错误，其实pdf、ppt等都会错误
```
Unhandled Rejection: h [TRPCClientError]: Unexpected token '<', "<!doctype "... is not valid JSON
    at h.from (/var/task/.next/server/chunks/6476.js:35:134907)
    at /var/task/.next/server/chunks/6476.js:35:140673
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
      at JSON.parse (<anonymous>)
      at parseJSONFromBytes (node:internal/deps/undici/undici:5472:19)
      at successSteps (node:internal/deps/undici/undici:5454:27)
      at fullyReadBody (node:internal/deps/undici/undici:4381:9)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async consumeBody (node:internal/deps/undici/undici:5463:7)
      at async I (/var/task/.next/server/chunks/6476.js:35:139418)
      at async Object.fetch (/var/task/.next/server/chunks/6476.js:35:139980)
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```
![image](https://github.com/user-attachments/assets/86b6c076-1b08-4c7d-8c39-f31f46c77ff7)
![image](https://github.com/user-attachments/assets/cf620466-912d-485e-8b56-ae007ec1ea6b)

**Comment by ZeroDeng01** [comment]
![image](https://github.com/user-attachments/assets/52217b1f-27cd-4e76-9312-83e194a7fa6b)
![image](https://github.com/user-attachments/assets/be75a920-2616-4248-8d77-9633c68d9353)
`APP_URL`为部署的lobe的主地址`https://xxx.xxxx.net`.
docx可以了，部分pptx和pdf依然存在问题报错如下：
![image](https://github.com/user-attachments/assets/f1bc181a-c8a8-40d3-a74b-990b97e90ce8)
![image](https://github.com/user-attachments/assets/197ea21d-d69d-410e-8ce6-9d9219b9477a)

**Comment by arvinxx** [comment]
报错的 PDF 和 PPTX 可以发出来看下

**Comment by ZeroDeng01** [comment]
Thx!由于可复现问题的文件不适合分享所以没办法提供测试样本!
