### ISSUE TITLE
[Bug] 本地部署数据库版本时无法正常使用S3存储

### ISSUE THREAD

**Issue by ReddotCleaner** [lobehub/lobe-chat#3781]
### 📦 部署环境

Docker

### 📌 软件版本

latest

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

本地部署数据库版本时无法正常使用S3存储，尝试过cloudflare R2以及本地部署minio，均报错
```
Invalid environment variables: { S3_ENDPOINT: [ 'Invalid url' ], S3_PUBLIC_DOMAIN: [ 'Invalid url' ] }
```
访问lobechat时报错
![image](https://github.com/user-attachments/assets/23d775aa-3923-41d2-aec7-80ee71b57784)

### 📷 复现步骤

安装时参照的流程为：https://lobehub.com/zh/docs/self-hosting/server-database/docker

### 🚦 期望结果

稳定出现S3 endpoint及URL错误

### 📝 补充信息

这里是我的env文件，敏感信息已经脱敏
```
# 网站域名
APP_URL=http://192.168.31.213:3210

# DB 必须的环境变量
# 用于加密敏感信息的密钥，可以使用 openssl rand -base64 32 生成
KEY_VAULTS_SECRET='KEY_VAULTS_SECRETKEY_VAULTS_SECRET'
# Postgres 数据库连接字符串
# 格式：postgres://username:password@host:port/dbname，如果你的 pg 实例为 Docker 容器，请使用容器名
DATABASE_URL=postgres://user:pass@192.168.31.208:5432/postgres

# NEXT_AUTH 相关，可以使用 auth0、Azure AD、GitHub、Authentik、zitadel 等，如有其他接入诉求欢迎提 PR
NEXT_AUTH_SECRET=NEXT_AUTH_SECRETNEXT_AUTH_SECRET
NEXT_AUTH_SSO_PROVIDERS=logto
LOGTO_CLIENT_ID=LOGTO_CLIENT_ID
LOGTO_CLIENT_SECRET=LOGTO_CLIENT_SECRETLOGTO_CLIENT_SECRET
LOGTO_ISSUER=https://lobe-auth-api.example.com/oidc


# S3 相关
S3_ACCESS_KEY_ID="S3_ACCESS_KEY_ID"
S3_SECRET_ACCESS_KEY="S3_SECRET_ACCESS_KEYS3_SECRET_ACCESS_KEYS3_SECRET_ACCESS_KEY"
S3_ENABLE_PATH_STYLE="1"
S3_BUCKET="lobe"
S3_ENDPOINT="https://562.r2.cloudflarestorage.com"
S3_PUBLIC_DOMAIN="https://s3.s3s3.xyz"
#S3_REGION=ap-chengdu # 如果需要指定地域

# 其他环境变量，视需求而定
# OPEANAI_API_KEY=sk-xxxx
# OPENAI_PROXY_URL=https://api.openai.com/v1
# OPENAI_MODEL_LIST=.

```

运行及错误日志
```
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.7
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 ✓ Starting...
 ✓ Ready in 83ms
❌ Invalid environment variables: { S3_ENDPOINT: [ 'Invalid url' ], S3_PUBLIC_DOMAIN: [ 'Invalid url' ] }
Error: Invalid environment variables
    at p (/app/.next/server/chunks/83140.js:1:886)
    at /app/.next/server/chunks/83140.js:1:1066
    at i (/app/.next/server/chunks/83140.js:1:1374)
    at /app/.next/server/chunks/36777.js:305:20242
    at 855306 (/app/.next/server/chunks/36777.js:305:21327)
    at t (/app/.next/server/webpack-runtime.js:1:143)
    at 647622 (/app/.next/server/chunks/36777.js:305:9727)
    at Function.t (/app/.next/server/webpack-runtime.js:1:143)
    at async tr (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:224358)
    at async rW (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:7025) {
  digest: '358761572'
}
Error: Invalid environment variables
    at p (/app/.next/server/chunks/83140.js:1:886)
    at /app/.next/server/chunks/83140.js:1:1066
    at i (/app/.next/server/chunks/83140.js:1:1374)
    at /app/.next/server/chunks/36777.js:305:20242
    at 855306 (/app/.next/server/chunks/36777.js:305:21327)
    at t (/app/.next/server/webpack-runtime.js:1:143)
    at 647622 (/app/.next/server/chunks/36777.js:305:9727)
    at Function.t (/app/.next/server/webpack-runtime.js:1:143)
    at async tr (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:12:224358)
    at async rW (/app/node_modules/.pnpm/next@14.2.7_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._dnmyh4q5vccmzwzgeuqoes2zd4/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:16:7025) {
  digest: '358761572'
}

```

**Comment by cold-sword** [comment]
S3 相关中环境变量引号去掉试试？

**Comment by ReddotCleaner** [comment]
> S3 相关中环境变量引号去掉试试？

一样的错误，试过了

**Comment by cold-sword** [comment]
> > S3 相关中环境变量引号去掉试试？
> 
> 一样的错误，试过了

![Screenshot_2024-09-05-23-25-47-857_mark.via.gp.jpg](https://github.com/user-attachments/assets/07c23798-124f-4d87-8f14-109a1d4e7b6c)

翻阅了下官方WiKi：https://lobehub.com/zh/docs/self-hosting/environment-variables/s3

path-style 和 virtual-host 在 S3 中是访问 bucket 和 object 的不同方式，URL 的结构和域名解析不太一样

假设 S3 服务商的域名是 s3.example.net ，bucket 为 mybucket，object 为 config.env，具体区别如下：

path-style : s3.example.net/mybucket/config.env
virtual-host : mybucket.s3.example.net/config.env

你的S3存储桶是Virtual-Host访问模式：https://s3.s3s3.xyz。

试试
# S3 相关
......
试试S3_ENABLE_PATH_STYLE="0"
或者
直接注释掉#S3_ENABLE_PATH_STYLE="1"

**Comment by arvinxx** [comment]
这个报错是说明你的 S3 URL 没有正确配置，因此没被正确识别成 URL，建议好好检查下你的环境变量是否有正确被注入

**Comment by GE-fighting** [comment]
请问这个问题解决了嘛，我也遇到一样的问题，用的是阿里云的oss

**Comment by ReddotCleaner** [comment]
> 请问这个问题解决了嘛，我也遇到一样的问题，用的是阿里云的oss

后面我用cf的对象存储好了

**Comment by GE-fighting** [comment]
> > 请问这个问题解决了嘛，我也遇到一样的问题，用的是阿里云的oss
> 
> 后面我用cf的对象存储好了

好的，谢谢佬，我去试试

**Comment by haoyuxin** [comment]
http://localhost:9000/ not  http://localhost:9000
