### ISSUE TITLE
使用图片加文字的方式提问或者纯图片就卡死，单纯文字，或者文件加文字都没问题[Bug] 

### ISSUE THREAD

**Issue by H-TTTTT** [lobehub/lobe-chat#3817]
### 📦 Environment

Docker

### 📌 Version

1.15.18 数据库版本

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 🐛 Bug Description

![image](https://github.com/user-attachments/assets/e44bb8e7-b2ea-4513-a7f1-ce561bdbf5d0)
![image](https://github.com/user-attachments/assets/1bfac904-4496-475b-82b6-221af24c9b8f)
报错细节
```
{
  "name": "TypeError",
  "stack": "TypeError: Failed to fetch\n    at http://192.168.31.11:3210/_next/static/chunks/85471-98fadabd001ef649.js:1:46388\n    at http://192.168.31.11:3210/_next/static/chunks/85471-98fadabd001ef649.js:1:47220\n    at new Promise (<anonymous>)\n    at body (http://192.168.31.11:3210/_next/static/chunks/85471-98fadabd001ef649.js:1:46237)\n    at tN (http://192.168.31.11:3210/_next/static/chunks/85471-98fadabd001ef649.js:1:47225)\n    at push.41159.constructor.getChatCompletion (http://192.168.31.11:3210/_next/static/chunks/85471-98fadabd001ef649.js:1:51995)\n    at async push.41159.constructor.createAssistantMessageStream (http://192.168.31.11:3210/_next/static/chunks/85471-98fadabd001ef649.js:1:51000)\n    at async internal_fetchAIChatMessage (http://192.168.31.11:3210/_next/static/chunks/56966-f2f4e95ac3870a09.js:1:27798)\n    at async internal_coreProcessMessage (http://192.168.31.11:3210/_next/static/chunks/56966-f2f4e95ac3870a09.js:1:26761)\n    at async Object.internal_resendMessage (http://192.168.31.11:3210/_next/static/chunks/56966-f2f4e95ac3870a09.js:1:29057)",
  "message": "Failed to fetch"
}
```
搭建方式，使用官网的方法，数据库搭建方式就出现这个问题
https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose
如果使用这个非数据库版本，就不会出现这个问题
https://lobehub.com/zh/docs/self-hosting/platform/docker-compose

### 📷 Recurrence Steps

文件加文字是不影响的
![image](https://github.com/user-attachments/assets/6b91b95d-3474-41c5-af4e-0c391d120867)
单纯图片就不行

**Comment by BiFangKNT** [comment]
我感觉我的议题和你的是同一个bug #3814

**Comment by H-TTTTT** [comment]
> 我感觉我的议题和你的是同一个bug #3814

我看了下，应该是一样的
