### ISSUE TITLE
[Bug] next-auth fetch failed with third auth provider

### ISSUE THREAD

**Issue by alwqx** [lobehub/lobe-chat#3821]
### 📦 部署环境

Docker

### 📌 软件版本

v1.15.18

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome, Safari

## env
lobechat database with third auth provider: auth0, cloudflare-zero-trust.

## problem
when click `login`, will throw error:
```shell
$ docker compose logs -f lobechat-db
lobe  | [Database] Start to migration...
lobe  | ✅ database migration pass.
lobe  | -------------------------------------
lobe  |   ▲ Next.js 14.2.8
lobe  |   - Local:        http://localhost:3210
lobe  |   - Network:      http://0.0.0.0:3210
lobe  |
lobe  |  ✓ Starting...
lobe  |  ✓ Ready in 45ms
lobe  | [auth][error] TypeError: fetch failed
lobe  |     at node:internal/deps/undici/undici:13178:13
lobe  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lobe  |     at async ia (/app/.next/server/chunks/76974.js:357:40645)
lobe  |     at async ic (/app/.next/server/chunks/76974.js:357:43280)
lobe  |     at async ip (/app/.next/server/chunks/76974.js:357:45913)
lobe  |     at async im (/app/.next/server/chunks/76974.js:357:49748)
lobe  |     at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
lobe  |     at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
lobe  |     at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
lobe  |     at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/server/base-server.js:1359:42)
lobe  | [NextAuth] Error: {
lobe  |   cause: 'Configuration',
lobe  |   message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
lobe  |   name: 'NextAuth Error'
lobe  | }
```

### 📷 复现步骤

lobechat database with auth0,cloudflare-zero-trust auth.

detaild see video:

https://github.com/user-attachments/assets/91dc26de-c6d5-4561-90e4-5fffc30c382a

### 🚦 期望结果

I think this may be caused by network timeout config.

when click `cloudflare-zero-trust`, lohechat will fetch something from cloudfalre but failed. May be we can set fetch timeout to a longer value such as `5s`.

**Comment by cy948** [comment]
If your server located in mainland China, you will get this networking problem.

**Comment by arvinxx** [comment]
you can try with `PROXY_URL`
