### ISSUE TITLE
[Bug] UNAUTHORIZED error when visiting web ui

### ISSUE THREAD

**Issue by AbondonedScrawl** [lobehub/lobe-chat#3825]
### 📦 Environment

Docker

### 📌 Version

Latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome, Safari, Firefox

### 🐛 Bug Description

I have carefully followed each step in this guide https://lobehub.com/docs/self-hosting/server-database/docker-compose. Every time I end up with a chat that is not working. I get following error:

<img width="436" alt="Screenshot 2024-09-08 at 15 33 49" src="https://github.com/user-attachments/assets/95820913-c51e-4879-890e-aa1e266ea4b2">

When looking at lobe-database logs, it looks like this:

```
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.8
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210
 ✓ Starting...
 ✓ Ready in 51ms
next auth: undefined
2024/09/08 03:14PM 30 pid=1 hostname=41fb7efbb4b8 msg=Error in tRPC handler (lambda) on path: session.createSession, type: mutation
a [TRPCError]: UNAUTHORIZED
    at /app/.next/server/chunks/39184.js:1:2617
    at t (/app/.next/server/chunks/5663.js:1:5733)
    at r (/app/.next/server/chunks/5663.js:1:6075)
    at /app/.next/server/chunks/8946.js:1:7083
    at Array.map (<anonymous>)
    at y (/app/.next/server/chunks/8946.js:1:6644)
    at async E (/app/.next/server/app/trpc/lambda/[trpc]/route.js:1:3654)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186) {
  code: 'UNAUTHORIZED',
  [cause]: undefined
```

### 📝 Additional Information

Issue persists on other hardware as well.

**Comment by arvinxx** [comment]
Do you login?

**Comment by AbondonedScrawl** [comment]
> Do you login?

Not sure what you mean. I just follow the guide

**Comment by arvinxx** [comment]
I mean you need to login and then try the upload

**Comment by AbondonedScrawl** [comment]
Damn it, I missed that part completely. Thank you. Now it is working

**Comment by moeinrahimi1** [comment]
I have followed instruction using docker-compose, after configuring logto and updating env, lobe chat wont show me login page but rather every action result in unauthorized

**Comment by arvinxx** [comment]
@moeinrahimi1 click the logo to login

**Comment by louwenjie231-outlook** [comment]
is solved?
