### ISSUE TITLE
上传图片提问报错[Bug] 

### ISSUE THREAD

**Issue by H-TTTTT** [lobehub/lobe-chat#3859]
### 📦 Environment

Docker

### 📌 Version

v1.15.26

### 💻 Operating System

Other Linux

### 🌐 Browser

Edge

### 🐛 Bug Description

我是用的是本地搭建的数据库版本
https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose

![image](https://github.com/user-attachments/assets/4512b746-f0e4-4b06-904e-8b5e8a67d8c7)
![image](https://github.com/user-attachments/assets/29f4b590-04d3-4188-bf6f-2ac584c6630e)
![image](https://github.com/user-attachments/assets/0bfe14a0-d935-467c-954b-238c5ac79851)
错误内容都是一致的

```
{
  "name": "TypeError",
  "stack": "TypeError: Failed to fetch\n    at http://192.168.31.11:3210/_next/static/chunks/85471-f7e63425ba9b5f94.js:1:46939\n    at http://192.168.31.11:3210/_next/static/chunks/85471-f7e63425ba9b5f94.js:1:47771\n    at new Promise (<anonymous>)\n    at body (http://192.168.31.11:3210/_next/static/chunks/85471-f7e63425ba9b5f94.js:1:46788)\n    at tN (http://192.168.31.11:3210/_next/static/chunks/85471-f7e63425ba9b5f94.js:1:47776)\n    at tH.getChatCompletion (http://192.168.31.11:3210/_next/static/chunks/85471-f7e63425ba9b5f94.js:1:52546)\n    at async tH.createAssistantMessageStream (http://192.168.31.11:3210/_next/static/chunks/85471-f7e63425ba9b5f94.js:1:51551)\n    at async internal_fetchAIChatMessage (http://192.168.31.11:3210/_next/static/chunks/56966-54d56f5330e105e1.js:1:27837)\n    at async internal_coreProcessMessage (http://192.168.31.11:3210/_next/static/chunks/56966-54d56f5330e105e1.js:1:26800)\n    at async sendMessage (http://192.168.31.11:3210/_next/static/chunks/56966-54d56f5330e105e1.js:1:24308)",
  "message": "Failed to fetch"
}
```

### 🚦 Expected Behavior

希望可以恢复正常
![image](https://github.com/user-attachments/assets/ba3d1034-01d1-4377-ba6f-a54201252bac)

**Comment by arvinxx** [comment]
重复 #3881
