### ISSUE TITLE
[Bug] Undeployed database alterations found

### ISSUE THREAD

**Issue by AbondonedScrawl** [lobehub/lobe-chat#3965]
### 📦 Environment

Docker

### 📌 Version

v1.17.3

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome, Safari

### 🐛 Bug Description

When using docker compose, logto throws this error and exits:

```
> cli
> logto db seed --swe
info Seeding skipped
npm notice
npm notice New patch version of npm available! 10.8.2 -> 10.8.3
npm notice Changelog: https://github.com/npm/cli/releases/tag/v10.8.3
npm notice To update run: npm install -g npm@10.8.3
npm notice
> start
> cd packages/core && NODE_ENV=production node .
(node:44) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
cache    warn No Redis client initialized, skipping
pre      error Found undeployed database alterations, you must deploy them first by npm run alteration deploy command.
 See https://docs.logto.io/docs/references/using-cli/database-alteration for reference.
index    error Error while initializing app:
index    error Error: Undeployed database alterations found.
    at checkAlterationState (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26444:9)
    at async Promise.all (index 0)
    at async checkPreconditions (file:///etc/logto/packages/core/build/main-F72FFTZD.js:26408:3)
    at async Promise.all (index 3)
    at async file:///etc/logto/packages/core/build/main-F72FFTZD.js:26480:3
```

This started happening during latest updates.

**Comment by AbondonedScrawl** [comment]
@dosu, any ideas?

**Comment by AbondonedScrawl** [comment]
lobe-database logs:

```
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.8
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 ✓ Starting...
 ✓ Ready in 56ms
LOGTO_CLIENT_ID will be removed in the future. Please set AUTH_LOGTO_ID instead.
LOGTO_CLIENT_SECRET will be removed in the future. Please set AUTH_LOGTO_SECRET instead.
LOGTO_ISSUER will be removed in the future. Please set AUTH_LOGTO_ISSUER instead.
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
LOGTO_CLIENT_ID will be removed in the future. Please set AUTH_LOGTO_ID instead.
LOGTO_CLIENT_SECRET will be removed in the future. Please set AUTH_LOGTO_SECRET instead.
LOGTO_ISSUER will be removed in the future. Please set AUTH_LOGTO_ISSUER instead.
LOGTO_CLIENT_ID will be removed in the future. Please set AUTH_LOGTO_ID instead.
LOGTO_CLIENT_SECRET will be removed in the future. Please set AUTH_LOGTO_SECRET instead.
LOGTO_ISSUER will be removed in the future. Please set AUTH_LOGTO_ISSUER instead.
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
[auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
```

@dosu

**Comment by AbondonedScrawl** [comment]
@dose

**Comment by AbondonedScrawl** [comment]
@dosu

**Comment by SpeedupMaster** [comment]
This is caused by the logto update, logto was updated to version 1.20.0 today. There are two solutions:
1. Continue to use version v1.19.0
2. Enter the logto container and run the following command to deploy the database changes:
`npm run alteration deploy`

**Comment by arvinxx** [comment]
we will remove logto soon and the recommand the casdoor as our auth provider. stay tuned.

**Comment by Lovest20018** [comment]
容器不能启动，没办法迁移，只能拉老版本先用了，期待用casdoor。

**Comment by zhangleijun111** [comment]
> Casdoor

等你了大神，logto生产搞到很痛苦，casdoor支持内网docker部署嘛

**Comment by zhangleijun111** [comment]
> 2\. npm run alteration deploy

我这个报错还有的拯救嘛

[]
![1726470656127](https://github.com/user-attachments/assets/062ba4e3-c443-4b75-934e-d4e34f3323a7)
(url)
