### ISSUE TITLE
LobeChat 因授权问题无法连接至MinIO服务器

### ISSUE THREAD

**Issue by AkarinLiu** [lobehub/lobe-chat#3990]
### Discussed in https://github.com/lobehub/lobe-chat/discussions/3988

<div type='discussions-op-text'>

<sup>Originally posted by **AkarinLiu** September 16, 2024</sup>
我尝试搭建 LobeChat 的服务器版本，出现了问题，一直提示授权失败，不知道怎么办。
![image](https://github.com/user-attachments/assets/26819d8c-cda1-49ee-8f40-c18e0a126fc4)
WinSCP还是可以连接的，但 LobeChat 无法连接。
这个问题甚至将存储桶的权限设为公开也没有解决。

```
lobe-database  |   code: 'UNAUTHORIZED',
lobe-database  |   [cause]: undefined                                               
lobe-database  | }                                                                  
lobe-database  | [auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant                                             
lobe-database  | [auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant                                             
lobe-database  | next auth: undefined
lobe-database  | {"level":30,"time":1726466738734,"pid":1,"hostname":"ef40a50a7562","msg":"Error in tRPC handler (lambda) on path: file.getFiles, type: query"}         
lobe-database  | a [TRPCError]: UNAUTHORIZED
lobe-database  |     at /app/.next/server/chunks/39184.js:1:2615                    
lobe-database  |     at t (/app/.next/server/chunks/5663.js:1:5733)
lobe-database  |     at r (/app/.next/server/chunks/5663.js:1:6075)                 
lobe-database  |     at /app/.next/server/chunks/8946.js:1:7083                     
lobe-database  |     at Array.map (<anonymous>)                                     
lobe-database  |     at y (/app/.next/server/chunks/8946.js:1:6644)                 
lobe-database  |     at async _ (/app/.next/server/app/trpc/lambda/[trpc]/route.js:1:3654)                                                                              
lobe-database  |     at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
lobe-database  |     at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
lobe-database  |     at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186) {
lobe-database  |   code: 'UNAUTHORIZED',
lobe-database  |   [cause]: undefined                                               
lobe-database  | }
lobe-database  | [auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant
lobe-database  | [auth][warn][env-url-basepath-redundant] Read more: https://warnings.authjs.dev#env-url-basepath-redundant                                             
lobe-database  | next auth: undefined
lobe-database  | {"level":30,"time":1726466741268,"pid":1,"hostname":"ef40a50a7562","msg":"Error in tRPC handler (lambda) on path: file.getFiles, type: query"}         
lobe-database  | a [TRPCError]: UNAUTHORIZED
lobe-database  |     at /app/.next/server/chunks/39184.js:1:2615                    
lobe-database  |     at t (/app/.next/server/chunks/5663.js:1:5733)                 
lobe-database  |     at r (/app/.next/server/chunks/5663.js:1:6075)
lobe-database  |     at /app/.next/server/chunks/8946.js:1:7083                     
lobe-database  |     at Array.map (<anonymous>)
lobe-database  |     at y (/app/.next/server/chunks/8946.js:1:6644)                 
lobe-database  |     at async _ (/app/.next/server/app/trpc/lambda/[trpc]/route.js:1:3654)                                                                              
lobe-database  |     at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
lobe-database  |     at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
lobe-database  |     at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186) {
lobe-database  |   code: 'UNAUTHORIZED',
lobe-database  |   [cause]: undefined                                               
lobe-database  | }                                                                  
```</div>

**Comment by LovelyGuYiMeng** [comment]
你没设置登录系统，数据库版必须要有个登录系统，没有登录系统就会一直授权失败

**Comment by zhangleijun111** [comment]
> 你没设置登录系统，数据库版必须要有个登录系统，没有登录系统就会一直授权失败

是否可以通过配置环境变量跳过身份认证这个环节
