### ISSUE TITLE
[Bug] pnpm build sitemap Error

### ISSUE THREAD

**Issue by Sen-CaPoo** [lobehub/lobe-chat#4057]
### 📦 部署环境

Other

### 📌 软件版本

1.19.20
從 https://github.com/lobehub/lobe-chat/releases/tag/v1.19.4 開始出現問題

### 💻 系统环境

Windows

### 🌐 浏览器

Chrome

### 🐛 问题描述

執行 pnpm build 後，出現以下錯誤訊息:

> next build

  ▲ Next.js 14.2.8

   Creating an optimized production build ...
 ✓ (pwa) Compiling for server...
 ✓ (pwa) Compiling for server...
...

./src/store/chat/slices/plugin/action.ts
144:13  Warning: Empty block statement.  no-empty

info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
 ✓ Linting and checking validity of types
 ⚠ Using edge runtime on a page currently disables static generation for that page
 ✓ Collecting page data
   Generating static pages (5/94)  [=   ]
Error occurred prerendering page "/sitemap/assistants.xml". Read more: https://nextjs.org/docs/messages/prerender-error

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
    at successSteps (node:internal/deps/undici/undici:4718:27)
    at fullyReadBody (node:internal/deps/undici/undici:1433:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4727:7)
    at async eT.getAssistantList (E:\UChat-V26\lobe-chat\.next\server\chunks\41805.js:1:76946)
    at async eG.getAssistants (E:\UChat-V26\lobe-chat\.next\server\chunks\41805.js:4:697)
    at async g (E:\UChat-V26\lobe-chat\.next\server\app\sitemap\[__metadata_id__]\route.js:1:1935)
    at async E:\UChat-V26\lobe-chat\node_modules\.pnpm\next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36932
    at async eC.execute (E:\UChat-V26\lobe-chat\node_modules\.pnpm\next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27548)
   Generating static pages (16/94)  [==  ]
Error occurred prerendering page "/sitemap/plugins.xml". Read more: https://nextjs.org/docs/messages/prerender-error

SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4747:19)
    at successSteps (node:internal/deps/undici/undici:4718:27)
    at fullyReadBody (node:internal/deps/undici/undici:1433:9)
    at async specConsumeBody (node:internal/deps/undici/undici:4727:7)
    at async eT.getPluginList (E:\UChat-V26\lobe-chat\.next\server\chunks\41805.js:1:78056)
    at async eG.getPlugins (E:\UChat-V26\lobe-chat\.next\server\chunks\41805.js:4:893)
    at async g (E:\UChat-V26\lobe-chat\.next\server\app\sitemap\[__metadata_id__]\route.js:1:1935)
    at async E:\UChat-V26\lobe-chat\node_modules\.pnpm\next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:36932
    at async eC.execute (E:\UChat-V26\lobe-chat\node_modules\.pnpm\next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:27548)
 ✓ Generating static pages (94/94)

> Export encountered errors on following paths:
        /sitemap/[__metadata_id__]/route: /sitemap/assistants.xml
        /sitemap/[__metadata_id__]/route: /sitemap/plugins.xml
 ELIFECYCLE  Command failed with exit code 1.

### 📷 复现步骤

執行 pnpm install 後，接著在執行 pnpm build 命令就會這樣。

**Comment by arvinxx** [comment]
你是有自定义修改的部分吗？目前官方 docker 构建都是正常的，感觉应该没问题？有没有可复现的方案

**Comment by AlexBlack2202** [comment]
i have same problem  with  the latest version [Version 1.22.6]

My step:

download 1.22.6 as zip format at https://github.com/lobehub/lobe-chat/releases/tag/v1.22.6

unzip

create .env file with some info

```
NEXT_PUBLIC_SERVICE_MODE=server

DATABASE_URL=xxxx
DATABASE_DRIVER=node
# use `openssl rand -base64 32` to generate a key for the encryption of the database
# we use this key to encrypt the user api key
KEY_VAULTS_SECRET=xxxx
APP_URL=http://localhost:3210
```

run command 
```
pnpm install 
 pnpm run build
```

and it show error

```
    Generating static pages (0/98)  [=   ]
 Error occurred prerendering page "/sitemap/plugins.xml". Read more: https://nextjs.org/docs/messages/prerender-error

 TypeError: fetch failed
   at Object.fetch (node:internal/deps/undici/undici:11372:11)
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)


Error occurred prerendering page "/sitemap/assistants.xml". Read more: https://nextjs.org/docs/messages/prerender-error
... ✓ Generating static pages (98/98)

> Export encountered errors on following paths:
        /sitemap/[__metadata_id__]/route: /sitemap/assistants.xml
        /sitemap/[__metadata_id__]/route: /sitemap/plugins.xml
```

so , any update for this problem
