### ISSUE TITLE
[Bug] 文件分块报错：分块失败，请检查后重试

### ISSUE THREAD

**Issue by xuxji** [lobehub/lobe-chat#4092]
### 📦 部署环境

Vercel

### 📌 软件版本

v1.19.22

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

在文件目录下，上传一个文件，点击分块后报错：

<img width="417" alt="image" src="https://github.com/user-attachments/assets/7fe22561-733d-4626-953a-286b058d78cc">

```shell
[ParseFileToChunks] error: h [TRPCClientError]: Unexpected token '<', "<!doctype "... is not valid JSON
    at h.from (/var/task/.next/server/chunks/15002.js:35:134906)
    at /var/task/.next/server/chunks/15002.js:35:140635
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  meta: undefined,
  shape: undefined,
  data: undefined,
  [cause]: SyntaxError: Unexpected token '<', "<!doctype "... is not valid JSON
      at JSON.parse (<anonymous>)
      at parseJSONFromBytes (node:internal/deps/undici/undici:5472:19)
      at successSteps (node:internal/deps/undici/undici:5454:27)
      at fullyReadBody (node:internal/deps/undici/undici:4381:9)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async consumeBody (node:internal/deps/undici/undici:5463:7)
      at async I (/var/task/.next/server/chunks/15002.js:35:139417)
      at async Object.fetch (/var/task/.next/server/chunks/15002.js:35:139979)
}
```

### 📷 复现步骤

在文件目录下，上传一个文件，点击分块

### 🚦 期望结果

分块并向量化成功

**Comment by xuxji** [comment]
> 检查你的 APP_URL 是否配置正确，且是否可以被正常访问到

感谢。APP_URL 配置成应用的地址（https://xxxxx.com）后解决
