### ISSUE TITLE
[Bug] 文件正常上传AWS S3，但是分块报错

### ISSUE THREAD

**Issue by tunogya** [lobehub/lobe-chat#4171]
### 📦 Environment

Vercel

### 📌 Version

v1.20.0

### 💻 Operating System

macOS

### 🌐 Browser

Chrome

### 🐛 Bug Description

POST /trpc/lambda/chunk.retryParseFileTask

DataError: Invalid key length
    at new DOMException (node:internal/per_context/domexception:53:5)
    ... 8 lines matching cause stack trace ...
    at async /var/task/.next/server/chunks/13065.js:1:16592 {
  code: 'INTERNAL_SERVER_ERROR',
  name: 'TRPCError',
  [cause]: DOMException [DataError]: Invalid key length
      at new DOMException (node:internal/per_context/domexception:53:5)
      at __node_internal_ (node:internal/util:670:10)
      at validateKeyLength (node:internal/crypto/aes:77:11)
      at Object.aesImportKey (node:internal/crypto/aes:271:7)
      at SubtleCrypto.importKey (node:internal/crypto/webcrypto:641:10)
      at i.initWithEnvKey (/var/task/.next/server/chunks/96096.js:8:67)
      at c (/var/task/.next/server/chunks/96096.js:8:1899)
      at Q.asyncParseFileToChunks (/var/task/.next/server/chunks/96096.js:8:8163)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async /var/task/.next/server/chunks/13065.js:1:16592
}

**Comment by tunogya** [comment]
修复了，是我的 KEY_VAULTS_SECRET 设置不符合加密规范，使用 openssl rand -base64 32 重新生成就👌
