### ISSUE TITLE
[Docs] Feedback for `self-hosting/server-database/docker-compose`

### ISSUE THREAD

**Issue by ikiwihome** [lobehub/lobe-chat#4186]
### 📝 Reference

https://github.com/lobehub/lobe-chat/tree/main/docs/self-hosting/server-database/docker-compose.zh-CN.mdx

### 🐛 Feedback

_Your response_

2024-09-28 11:16:33 [Database] Start to migration...
2024-09-28 11:16:33 ✅ database migration pass.
2024-09-28 11:16:33 -------------------------------------
2024-09-28 11:16:33   ▲ Next.js 14.2.8
2024-09-28 11:16:33   - Local:        http://localhost:3210
2024-09-28 11:16:33   - Network:      http://0.0.0.0:3210
2024-09-28 11:16:33 
2024-09-28 11:16:33  ✓ Starting...
2024-09-28 11:16:33  ✓ Ready in 42ms
2024-09-28 11:16:48 next auth: undefined
2024-09-28 11:16:48 next auth: undefined
2024-09-28 11:16:48 {"level":30,"time":1727493408930,"pid":19,"hostname":"14600212524f","msg":"Error in tRPC handler (lambda) on path: file.getFiles, type: query"}
2024-09-28 11:16:48 {"level":30,"time":1727493408932,"pid":19,"hostname":"14600212524f","msg":"Error in tRPC handler (lambda) on path: knowledgeBase.getKnowledgeBases, type: query"}
2024-09-28 11:16:47 LOGTO_CLIENT_ID will be removed in the future. Please set AUTH_LOGTO_ID instead.
2024-09-28 11:16:47 LOGTO_CLIENT_SECRET will be removed in the future. Please set AUTH_LOGTO_SECRET instead.
2024-09-28 11:16:47 LOGTO_CLIENT_ID will be removed in the future. Please set AUTH_LOGTO_ID instead.
2024-09-28 11:16:47 LOGTO_CLIENT_SECRET will be removed in the future. Please set AUTH_LOGTO_SECRET instead.
2024-09-28 11:16:47 LOGTO_CLIENT_ID will be removed in the future. Please set AUTH_LOGTO_ID instead.
2024-09-28 11:16:47 LOGTO_CLIENT_SECRET will be removed in the future. Please set AUTH_LOGTO_SECRET instead.
2024-09-28 11:16:48 a [TRPCError]: UNAUTHORIZED
2024-09-28 11:16:48     at /app/.next/server/chunks/39184.js:1:2619
2024-09-28 11:16:48     at c (/app/.next/server/chunks/27418.js:4:74)
2024-09-28 11:16:48     at r (/app/.next/server/chunks/27418.js:1:5663)
2024-09-28 11:16:48     at /app/.next/server/chunks/48718.js:1:7084
2024-09-28 11:16:48     at Array.map (<anonymous>)
2024-09-28 11:16:48     at y (/app/.next/server/chunks/48718.js:1:6645)
2024-09-28 11:16:48     at async _ (/app/.next/server/app/trpc/lambda/[trpc]/route.js:1:3652)
2024-09-28 11:16:48     at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
2024-09-28 11:16:48     at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
2024-09-28 11:16:48     at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_supports-color@8.1.1__@opentelemetry+api@1.9.0_react-dom@18.3._itjmu72s7n7tov6po6nkhcdpya/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186) {
2024-09-28 11:16:48   code: 'UNAUTHORIZED',
2024-09-28 11:16:48   [cause]: undefined
2024-09-28 11:16:48 }

**Comment by cy948** [comment]
你想提的问题是?

**Comment by arvinxx** [comment]
you need to login first
