### ISSUE TITLE
请求失败

### ISSUE THREAD

**Issue by followdd** [lobehub/lobe-chat#4193]
请求失败
很抱歉，服务器似乎遇到了一些困难，暂时无法完成您的请求，请稍后再试

**Comment by arvinxx** [comment]
看下服务端日志

**Comment by followdd** [comment]
> 看下服务端日志
您好~ 很抱歉我是一个刚刚学习编程的新手，请问如何查看服务端日志？感谢

**Comment by followdd** [comment]
![Uploading 20240929013158.png…]()

**Comment by followdd** [comment]
inspector.js:7 
 POST https://www.google-analytics.com/g/collect?v=2&tid=G-6YKT4WQPK3&gtm=45je49p…E7%9A%84%E5%A4%A7%E8%84%91%20%C2%B7%20LobeChat&en=page_view&_ee=1&tfd=3331 net::ERR_SSL_PROTOCOL_ERROR
chat:1 <meta name="apple-mobile-web-app-capable" content="yes"> is deprecated. Please include <meta name="mobile-web-app-capable" content="yes">
inspector.js:7 
 POST https://w.clarity.ms/collect net::ERR_SSL_PROTOCOL_ERROR
inspector.js:7 
 POST https://w.clarity.ms/collect net::ERR_SSL_PROTOCOL_ERROR
inspector.js:7 
 POST https://w.clarity.ms/collect net::ERR_SSL_PROTOCOL_ERROR
clarity.js:2 
 POST https://w.clarity.ms/collect net::ERR_SSL_PROTOCOL_ERROR
9
The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
inspector.js:7 
 POST https://www.google-analytics.com/g/collect?v=2&tid=G-6YKT4WQPK3&gtm=45je49p…4%91%20%C2%B7%20LobeChat&en=scroll&epn.percent_scrolled=90&_et=11&tfd=8344 net::ERR_SSL_PROTOCOL_ERROR
/chat?session=inbox:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
inspector.js:7 
 POST https://lobechat.com/trpc/lambda/chunk.semanticSearchForChat?batch=1 500 (Internal Server Error)
16642-4e86e4c17a342a0a.js:1 Uncaught (in promise) TRPCClientError
    at s.from (16642-4e86e4c17a342a0a.js:1:878)
    at 16642-4e86e4c17a342a0a.js:1:7358
inspector.js:7 
 POST https://www.google-analytics.com/g/collect?v=2&tid=G-6YKT4WQPK3&gtm=45je49p…dt=%E9%9A%8F%E4%BE%BF%E8%81%8A%E8%81%8A%20%C2%B7%20LobeChat&_s=3&tfd=14708 net::ERR_SSL_PROTOCOL_ERROR

**Comment by arvinxx** [comment]
应该是你达到免费量上限了
