### ISSUE TITLE
[Bug] PostgreSQL connect ECONNREFUSED 

### ISSUE THREAD

**Issue by nullikacademy** [lobehub/lobe-chat#4336]
### 📦 Environment

Other

### 📌 Version

1.21.16

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

The application has been deployed without any issues, but it constantly displays a message related to the database connection. Where is the problem coming from? Could you please guide me?

LobeChat:
Request Failed
Sorry, the server seems to be experiencing some difficulties and is temporarily unable to complete your request. Please try again later.
Error Details
text
connect ECONNREFUSED 81.12.30.45:443

Error Log:
21
{"level":30,"time":1728723471108,"pid":13,"hostname":"opengpt130-bb6f74675-6bmkp","msg":"Error in tRPC handler (lambda) on path: agent.getAgentConfig, type: query"}
22
a [TRPCError]: connect ECONNREFUSED 81.12.30.45:443
at i (/app/.next/server/chunks/900.js:1:944)
... 6 lines matching cause stack trace ...
at async /app/.next/server/chunks/29795.js:1:7166
at async Promise.all (index 0)
at async y (/app/.next/server/chunks/29795.js:1:9774) {
code: 'INTERNAL_SERVER_ERROR',
[cause]: o [Error]: connect ECONNREFUSED 81.12.30.45:443
at /app/.next/server/chunks/900.js:1:1255
at new a (/app/.next/server/chunks/900.js:1:1297)
at i (/app/.next/server/chunks/900.js:1:944)
at c (/app/.next/server/chunks/900.js:4:286)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async c (/app/.next/server/chunks/900.js:4:68)
at async c (/app/.next/server/chunks/900.js:4:68)
at async c (/app/.next/server/chunks/900.js:4:68)
at async r (/app/.next/server/chunks/900.js:1:5649)
at async /app/.next/server/chunks/29795.js:1:7166 {
error: Error: connect ECONNREFUSED 81.12.30.45:443
at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1607:16)
at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
errno: -111,
code: 'ECONNREFUSED',
syscall: 'connect',
address: '81.12.30.45',
port: 443
},
target: WebSocket {
_events: [Object: null prototype],
_eventsCount: 4,
_maxListeners: undefined,
_binaryType: 'arraybuffer',
_closeCode: 1006,
_closeFrameReceived: false,
_closeFrameSent: false,
_closeMessage: <Buffer >,
_closeTimer: null,
_extensions: {},
_protocol: '',
_readyState: 3,
_receiver: null,
_sender: null,
_socket: null,
_bufferedAmount: 0,
_isServer: false,
_redirects: 0,
_url: 'wss://c052adfd-6288-4a78-a109-f5c23d22ee9b.hadb.ir/v2',
_req: null,
[Symbol(shapeMode)]: false,
[Symbol(kCapture)]: false
},
type: 'error'
}
}

**Comment by nullikacademy** [comment]
Why is it making a WebSocket request when it's supposed to be a database?

**Comment by arvinxx** [comment]
check the document: https://orm.drizzle.team/docs/connect-neon

<img width="893" alt="image" src="https://github.com/user-attachments/assets/fd455b3d-2b9e-4eb6-a3f3-54e023cd3d92">


we need transaction
