### ISSUE TITLE
[Bug] 点击任意一个插件，会报错且页面无法访问

### ISSUE THREAD

**Issue by RubyLiuBlog** [lobehub/lobe-chat#4527]
### 📦 部署环境

Docker

### 📌 软件版本

v1.26.3

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

发现页面的插件，点击任意一个插件，会报错且页面无法访问

docker 日志报错信息如下
```bash
TypeError: fetchError
    at _ (/app/.next/server/chunks/64417.js:1:1828)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C (/app/.next/server/chunks/64417.js:1:2644)
    at async M.getPluginById (/app/.next/server/chunks/64417.js:1:5180)
    at async j (/app/.next/server/app/(main)/discover/(detail)/plugin/[slug]/page.js:31:5107) {
  digest: '3242081510'
}
```

### 📷 复现步骤

1.点击左侧菜单discover
2.点击顶部tab插件页
3.点击任意一款插件

### 🚦 期望结果

期待访问正确的插件详情页

**Comment by RubyLiuBlog** [comment]
我明白了 是我的云服务器访问不了https://bilibili.chat-plugin.lobehub.com/manifest.json，这种问题怎么解决呢?
@arvinxx

**Comment by RubyLiuBlog** [comment]
我的服务器可以ping 的通这个域名 chat-plugin.lobehub.com

**Comment by RubyLiuBlog** [comment]
问题找到了,是我的云服务器无法连接到76.76.21.22这个ip地址，我已经联系我的云服务商去解决了
