### ISSUE TITLE
[Bug] vercel部署失败

### ISSUE THREAD

**Issue by davaded** [lobehub/lobe-chat#4557]
### 📦 Environment

Vercel

### 📌 Version

最新

### 💻 Operating System

Other

### 🌐 Browser

Chrome

### 🐛 Bug Description

 ✓ (serwist) Bundling the service worker script with the URL '/sw.js' and the scope '/'...
 ✓ Compiled successfully
   Linting and checking validity of types ...
   Collecting page data ...
node:buffer:1294
      throw lazyDOMException(
      ^
InvalidCharacterError: The string to be decoded is not correctly encoded.
    at atob (node:buffer:1294:13)
    at u (/vercel/path0/.next/server/edge-chunks/17.js:1:25526)
    at /vercel/path0/.next/server/edge-chunks/17.js:5:38344
    at /vercel/path0/.next/server/edge-chunks/17.js:5:38393
    at /vercel/path0/.next/server/edge-chunks/17.js:5:38664
    at 9891 (/vercel/path0/.next/server/edge-chunks/17.js:5:38918)
    at t (/vercel/path0/.next/server/edge-runtime-webpack.js:1:143)
    at 7290 (/vercel/path0/.next/server/app/(backend)/trpc/edge/[trpc]/route.js:5:5757)
    at t (/vercel/path0/.next/server/edge-runtime-webpack.js:1:143)
    at t (/vercel/path0/.next/server/app/(backend)/trpc/edge/[trpc]/route.js:378:70492)
> Build error occurred
Error: Failed to collect page data for /trpc/edge/[trpc]
    at /vercel/path0/node_modules/next/dist/build/utils.js:1268:15
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  type: 'Error'
}
error: script "build" exited with code 1
Error: Command "bun run build" exited with 1

**Comment by davaded** [comment]
我自己处理吗？

**Comment by arvinxx** [comment]
重试下
