### ISSUE TITLE
[Bug] 注册时提示error TypeError: fetch failed

### ISSUE THREAD

**Issue by sunshinexiaozhu** [lobehub/lobe-chat#4646]
### 📦 部署环境

Docker

### 📌 软件版本

latest

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

使用文档里面的域名方式部署后：https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose
访问logto-ui管理后台：
![QQ_1731058636380](https://github.com/user-attachments/assets/ff037267-c83a-4739-ace2-757bf28e1062)
查看日志error：
![QQ_1731058749866](https://github.com/user-attachments/assets/83415d0f-5679-436d-9fa9-0126ab3a09ad)

docker compose：
![QQ_1731058839915](https://github.com/user-attachments/assets/78f78310-c8b4-4063-a0ba-605d4b353ba4)

nginx config：
![QQ_1731058914810](https://github.com/user-attachments/assets/b7a6dec2-5ccc-4ca4-add8-7ecfaca13098)

### 🚦 期望结果

不知是哪里出现了问题，帮忙解答一下

**Comment by sunshinexiaozhu** [comment]
补充说明，我这个是在内网环境，没有加dns记录   都是通过在本地添加hosts记录访问的
是否跟这个有关

**Comment by changjiong** [comment]
我的问题跟你一样，也是在注册的时候报错internal server error。我是部署在公网，域名模式。后台看日志是说有个函数PasswordPolicyChecker.hasBeenPwned  fetch  timeout，也不知道是什么原因，不知道这里面是不是有被墙的地方。报错日志如下：


jYeLt-cqGzkJuJzA   --> PATCH /api/interaction/profile 500 514ms 36b
EbypNzGnBtFw5UkM   <-- PATCH /api/interaction/profile
EbypNzGnBtFw5UkM error TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PasswordPolicyChecker.hasBeenPwned (file:///etc/logto/packages/toolkit/core-kit/lib/password-policy.js:226:26)
    at async PasswordPolicyChecker.check (file:///etc/logto/packages/toolkit/core-kit/lib/password-policy.js:97:43)
    at async validatePassword (file:///etc/logto/packages/core/build/main-BOZ4RWKM.js:16192:18)
    at async file:///etc/logto/packages/core/build/main-BOZ4RWKM.js:16374:7
    at async guardMiddleware (file:///etc/logto/packages/core/build/main-BOZ4RWKM.js:4536:7)
    at async file:///etc/logto/packages/core/build/main-BOZ4RWKM.js:2171:7
    at async file:///etc/logto/packages/core/build/main-BOZ4RWKM.js:2202:5
    at async cors (/etc/logto/node_modules/.pnpm/@koa+cors@5.0.0/node_modules/@koa/cors/index.js:64:16)
    at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:58:5
    at async /etc/logto/node_modules/.pnpm/koa-mount@4.0.0/node_modules/koa-mount/index.js:52:26
    at async compressMiddleware (/etc/logto/node_modules/.pnpm/koa-compress@5.1.1/node_modules/koa-compress/lib/index.js:56:5)
    at async file:///etc/logto/packages/core/build/main-BOZ4RWKM.js:743:7
    at async file:///etc/logto/packages/core/build/main-BOZ4RWKM.js:1233:7
    at async file:///etc/logto/packages/core/build/main-BOZ4RWKM.js:1077:7 {
  [cause]: AggregateError [ETIMEDOUT]:
      at internalConnectMultiple (node:net:1118:18)
      at internalConnectMultiple (node:net:1186:5)
      at Timeout.internalConnectMultipleTimeout (node:net:1712:5)
      at listOnTimeout (node:internal/timers:583:11)
      at process.processTimers (node:internal/timers:519:7) {
    code: 'ETIMEDOUT',
    [errors]: [ [Error], [Error], [Error], [Error] ]
  }
}

**Comment by changjiong** [comment]
呵

**Comment by changjiong** [comment]
参考 Logto 开源代码仓库的 [Issue bug: Error on create a password](https://github.com/logto-io/logto/issues/6577#issuecomment-2359921567)，在 Postgres 中执行：

update sign_in_experiences set password_policy='{"rejects": {"pwned": false}}' where tenant_id='admin';

**Comment by changjiong** [comment]
还有个办法是疯狂连续点击提交注册，某个时间点会注册成功，可能是在timeout的时间内。   第一个用户是管理员账户无法登录作为lobechat用户，需要在另行注册一个普通用户。
