### ISSUE TITLE
[Bug] Microsoft Entra ID Error AADSTS50011 with OpenID authentication

### ISSUE THREAD

**Issue by gemnioo** [lobehub/lobe-chat#4723]
### 📦 Environment

Docker

### 📌 Version

lobehub/lobe-chat-database v1.31.10

### 💻 Operating System

Other Linux

### 🌐 Browser

Firefox

### 🐛 Bug Description

Follow this  tutorial https://lobehub.com/zh/docs/self-hosting/advanced/auth/next-auth/microsoft-entra-id 

I successful add Microsoft Entra ID info in the lobe-chat.env config. but shows error Error AADSTS50011

Follow Microsoft docs https://learn.microsoft.com/en-us/troubleshoot/entra/entra-id/app-integration/error-code-AADSTS50011-redirect-uri-mismatch#resolution

"On the app registration page, select Authentication. In the Platform configurations section, select Add URI to add the redirect URI displayed in the error message to Microsoft Entra ID."

I modify the Web Redirect URIs 

![image](https://github.com/user-attachments/assets/17e69634-5ff9-42a9-aa24-7055b6c47420)

But shows error like this 

![image](https://github.com/user-attachments/assets/e1315e68-42e1-4cdd-bfd8-f11a24034822)

if click the Reload button 

![image](https://github.com/user-attachments/assets/369b0d8c-64f9-428f-a419-7d8a0f16528a)

and click will looped to the first Ooops page.

the config in the lobe-chat.env like 

```
NEXT_AUTH_SECRET=openssl rand -base64 32
NEXT_AUTH_SSO_PROVIDERS=microsoft-entra-id
AUTH_MICROSOFT_ENTRA_ID_ID=
AUTH_MICROSOFT_ENTRA_ID_SECRET=
AUTH_MICROSOFT_ENTRA_ID_TENANT_ID=
NEXTAUTH_URL= https://claw-jp.tail1030ff.ts.net/api/auth
```

I tried modify the NEXTAUTH_URL with /api/auth ending  or  /api/auth/callback/microsoft-entra-id

the only difference were "/api/auth/callback/microsoft-entra-id" will Reload to Sign in with Microsoft Entra ID Page.

Pls advise.  Should I ADD user "LobeChat" into  Home -> Microsoft Entra ID -> App registrations -> Owner ? 

### 📷 Recurrence Steps

Docker deploy with 

lobe-chat-database docker 
pgvector/pgvector:pg17
Cloudflare R2 bucket 
Microsoft Entra ID
"tailscale serve or tailscale funnel"

**Comment by gemnioo** [comment]
> `NEXT_AUTH_SECRET` should be a base64 string

yep I use "openssl rand -base64 32" instead

**Comment by gemnioo** [comment]
> What did it say in docker logs?

docker logs $(docker ps -a | grep lobe-chat-database | awk '{print $1}').  

```
🌐 DNS Server: [ '127.0.0.11' ]
-------------------------------------
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.8
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 ✓ Starting...
 ✓ Ready in 119ms
[auth][error] MissingCSRF: CSRF token was missing during an action signin. Read more at https://errors.authjs.dev#missingcsrf
    at tR (/app/.next/server/chunks/38106.js:1:39757)
    at i0 (/app/.next/server/chunks/38106.js:368:52432)
    at async i2 (/app/.next/server/chunks/38106.js:368:56596)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
    at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1359:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1581:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1489:28)
    at async NextNodeServer.renderPageComponent (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1913:24)
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: u: JWTs must use Compact JWS serialization, JWT must be a string
    at /app/.next/server/chunks/38106.js:368:33665
    at iH (/app/.next/server/chunks/38106.js:368:34195)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async iz (/app/.next/server/chunks/38106.js:368:40333)
    at async i0 (/app/.next/server/chunks/38106.js:368:51902)
    at async i2 (/app/.next/server/chunks/38106.js:368:56596)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
    at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1359:42)
 ````
 and  
 
 ```
 [auth][details]: {
  "provider": "microsoft-entra-id"
}
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: u: JWTs must use Compact JWS serialization, JWT must be a string
    at /app/.next/server/chunks/38106.js:368:33665
    at iH (/app/.next/server/chunks/38106.js:368:34195)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async iz (/app/.next/server/chunks/38106.js:368:40333)
    at async i0 (/app/.next/server/chunks/38106.js:368:51902)
    at async i2 (/app/.next/server/chunks/38106.js:368:56596)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
    at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1359:42)
[auth][details]: {
  "provider": "microsoft-entra-id"
}
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
```

**Comment by gemnioo** [comment]
the main "JWTs must use Compact JWS serialization, JWT must be a string" 

looks like this error https://github.com/BerriAI/litellm/issues/6793

**Comment by gemnioo** [comment]
follow the just released tutorial, switch NextAuth methods from Microsoft Entra ID  to Cloudflare Zero Trust  

https://lobehub.com/zh/docs/self-hosting/advanced/auth/next-auth/cloudflare-zero-trust

I could success login. seems like this ""JWTs must use Compact JWS serialization, JWT must be a string""  error in Microsoft Entra ID auth lead to this issue. 

and I can confirm the "NEXTAUTH_URL=" in lobe-chat.env should end with "example.com/api/auth" and the Web Redirect URIs in Microsoft Entra ID -- Callback URL or  "Platform configurations section, select Add URI to add the redirect URI" should be end "/api/auth/callback/microsoft-entra-id" 

PS: some one need update the tutorial screenshort (need update the "/api/auth/callback/azure-ad"

**Comment by gemnioo** [comment]
> It's wierd because I have just tried login to my deployment and succeeded. My deployment is on Vercel, but I don't think that makes any difference. Besides,
> 
>     * I use the latest version
> 
>     * I does not set `NEXTAUTH_URL`

okay I will tried again with not set "NEXTAUTH_URL" next few days with  lobehub/lobe-chat-database image update.

**Comment by gemnioo** [comment]
@BrandonStudio  I tried the lobehub/lobe-chat-database [v1.32.2] and removing NEXTAUTH_URL. the login error shows:

https://0.0.0.0:3210/api/auth/error?error=Configuration

![image](https://github.com/user-attachments/assets/70922469-92fa-4b4c-8f79-84f33a303898)

**Comment by cy948** [comment]
@EINDEX Hi, can you help this?

**Comment by cy948** [comment]
CSRF error see #3991

**Comment by EINDEX** [comment]
Hi @gemnioo 

You are using https with IP 0.0.0.0, which seems strange, what is your redirect URL on Azure side?

for the localhost server on MS entra id SSO, if nextauth_url is the default value the redirect URL should be setting `http://localhost:3210/api/auth/callback/microsoft-entra-id`.

**Comment by gemnioo** [comment]
> Hi @gemnioo
> 
> You are using https with IP 0.0.0.0, which seems strange, what is your redirect URL on Azure side?
> 
> for the localhost server on MS entra id SSO, if nextauth_url is the default value the redirect URL should be setting `http://localhost:3210/api/auth/callback/microsoft-entra-id`.

on Azure side the Web redirect URL is https://name.tailscale_tailnet_name.ts.net//api/auth/callback/microsoft-entra-id

on lobe-chat.env NEXTAUTH_URL=https://name.tailscale_tailnet_name.ts.net/api/auth

I use tailscale funnel --bg 3210 or tailscale serve --bg 3210 to expose lobechat in Internat or within Tailnet

**Comment by EINDEX** [comment]
Hi @gemnioo 

I am using this configuration with ts net command which is running well, cannot reproduce your error.

```
tailscale serve http://localhost:3210
```

```
docker run -it --rm \
  -e KEY_VAULTS_SECRET=<secret> \
 -e NEXTAUTH_URL=https://<name>.<ts-net>.ts.net/api/auth  -e NEXT_AUTH_SECRET=327db52f83367f00ae0f2d40b6d2313c \
  -e NEXT_AUTH_SSO_PROVIDERS=microsoft-entra-id \
  -e AUTH_MICROSOFT_ENTRA_ID_SECRET= \
  -e AUTH_MICROSOFT_ENTRA_ID_ID= \
  -e AUTH_MICROSOFT_ENTRA_ID_ISSUER= \
  -e ACCESS_CODE=disable \
  -e NEXTAUTH_SECRET= \
  -e ENABLE_OAUTH_SSO=1 \
  -e APP_URL=https://<name>.<ts-net>.ts.net/ \
 -p 3210:3210  lobehub/lobe-chat
 ```
 
 
<img width="1377" alt="image" src="https://github.com/user-attachments/assets/b2c4882d-0817-43ec-8754-04ac39435cf2">

**Comment by gemnioo** [comment]
@EINDEX   lunch break quick deploy in another device with --network host linked to tailnet pgvector db.  still shows Error AADSTS50011 in incognito mode.

![Screenshot 2024-11-25 ](https://github.com/user-attachments/assets/7577b4d0-d0b5-42fe-9b6b-b9568b5ed2d9)


docker command
```
docker run -it -d \
  -p 3210:3210 \
  --network host \
  --env-file lobe-chat.env \
  --name lobe-chat-database \
  lobehub/lobe-chat-database
  ```
  lobe-chat.env
  ```
FEATURE_FLAGS="-welcome_suggest"
APP_URL=https://name.tailnet_name.ts.net
DATABASE_URL=postgres://postgres:PASSWORD@100.100.100.100:5432/postgres   \\example
KEY_VAULTS_SECRET=
NEXT_AUTH_SECRET=
NEXT_AUTH_SSO_PROVIDERS=microsoft-entra-id
AUTH_MICROSOFT_ENTRA_ID_ID=
AUTH_MICROSOFT_ENTRA_ID_SECRET=
AUTH_MICROSOFT_ENTRA_ID_TENANT_ID=
NEXTAUTH_URL=https://name.tailnet_name.ts.net/api/auth
S3_ACCESS_KEY_ID= 
S3_SECRET_ACCESS_KEY= 
S3_BUCKET=lobechat
S3_ENDPOINT=https://   .r2.cloudflarestorage.com
S3_PUBLIC_DOMAIN=https://      .r2.dev
OPENAI_API_KEY=PASSWORD
OPENAI_PROXY_URL=http://100.100.100.100/chat/completions  \\example
```
VDS logs check
```
root@device:~# docker image pull lobehub/lobe-chat-database:latest
latest: Pulling from lobehub/lobe-chat-database
74f6cce96022: Pull complete
Digest: sha256:e3e87bc6a99540d384b460301f4f939279fec133d67613fe4c88cdcbef15df83
Status: Downloaded newer image for lobehub/lobe-chat-database:latest
docker.io/lobehub/lobe-chat-database:latest
root@device:~# docker run --rm \
  -d -p 14321:8080 \
  -v "${PWD}/searxng:/etc/searxng" \
  -e "BASE_URL=http://localhost:14321/" \
  -e "INSTANCE_NAME=searxng" \
  searxng/searxng
4f854452a214baf7d18f085b1ded82f82a2d81ccb26090814a8c2f496dbb4b4f

root@device:~# nano lobe-chat.env
root@device:~# cat lobe-chat.env
FEATURE_FLAGS="-welcome_suggest"
APP_URL=https://name.tailnet_name.ts.net
DATABASE_URL=postgres://postgres:PASSWORD@100.100.100.100:5432/postgres
KEY_VAULTS_SECRET=
NEXT_AUTH_SECRET=
NEXT_AUTH_SSO_PROVIDERS=microsoft-entra-id
AUTH_MICROSOFT_ENTRA_ID_ID=
AUTH_MICROSOFT_ENTRA_ID_SECRET=
AUTH_MICROSOFT_ENTRA_ID_TENANT_ID=
S3_ACCESS_KEY_ID=
S3_SECRET_ACCESS_KEY=
S3_BUCKET=lobechat
S3_ENDPOINT=https://    .r2.cloudflarestorage.com
S3_PUBLIC_DOMAIN=https://  .r2.dev
OPENAI_API_KEY=
OPENAI_PROXY_URL=http://100.100.100.100/chat/completions
root@device:~# docker run -it -d \
  -p 3210:3210 \
  --network host \
  --env-file lobe-chat.env \
  --name lobe-chat-database \
  lobehub/lobe-chat-database
WARNING: Published ports are discarded when using host network mode
7a5c50340141059d72c73a6735d59cfb98a2de0e56920affee2b5f1ca362fea6
root@device:~# docker logs -f lobe-chat-database
🌐 DNS Server: [ '1.1.1.1', '8.8.8.8' ]
-------------------------------------
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.8
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 ✓ Starting...
 ✓ Ready in 101ms
^C
```

**Comment by edenchan1020** [comment]
@EINDEX   @gemnioo  @BrandonStudio  i have met the same issue too with microsoft-entra-id ,  have you resolved this problem ? 

the logs:

🌐 DNS Server: [ '127.0.0.11' ]
-------------------------------------
[Database] Start to migration...
✅ database migration pass.
-------------------------------------
  ▲ Next.js 14.2.8
  - Local:        http://localhost:3210
  - Network:      http://0.0.0.0:3210

 ✓ Starting...
 ✓ Ready in 109ms
[auth][error] CallbackRouteError: Read more at https://errors.authjs.dev#callbackrouteerror
[auth][cause]: u: JWTs must use Compact JWS serialization, JWT must be a string
    at /app/.next/server/chunks/43505.js:368:33665
    at iH (/app/.next/server/chunks/43505.js:368:34195)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async iz (/app/.next/server/chunks/43505.js:368:40333)
    at async i0 (/app/.next/server/chunks/43505.js:368:51902)
    at async i2 (/app/.next/server/chunks/43505.js:368:56596)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
    at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/server/base-server.js:1359:42)
[auth][details]: {
  "provider": "microsoft-entra-id"
}
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}

**Comment by EINDEX** [comment]
@edenchan1020  Please check without the tailscale proxy and domain.

**Comment by edenchan1020** [comment]
I have tryed and with the same results. 

does it  support the keyclock ?

**Comment by EINDEX** [comment]
Base on authjs yes,
https://authjs.dev/getting-started/providers/keycloak

**Comment by gemnioo** [comment]
@edenchan1020  I cloud success deploy with Cloudflare Zero Trust within the tailscale tailnet.

@EINDEX  looks like the Microsoft Entra ID  and Azure AD authorization will have Breaking Change in v2 ?  

https://github.com/lobehub/lobe-chat/pull/4579

https://github.com/lobehub/lobe-chat/discussions/3283

**Comment by EINDEX** [comment]
@gemnioo For my side, I can successfully work with Entra ID without tailscale, but with tailscale I have same issue.

**Comment by gemnioo** [comment]
> @gemnioo For my side, I can successfully work with Entra ID without tailscale, but with tailscale I have same issue.

got it. thanks for ur help ~

**Comment by mengdahuang** [comment]
> Hi [@gemnioo](https://github.com/gemnioo)
> 
> I am using this configuration with ts net command which is running well, cannot reproduce your error.
> 
> I suggest using an incognito window to try again.
> 
> ```
> tailscale serve http://localhost:3210
> ```
> 
> ```
> docker run -it --rm \
>   -e KEY_VAULTS_SECRET=<secret> \
>   -e NEXTAUTH_URL=https://<name>.<ts-net>.ts.net/api/auth  \
>   -e NEXT_AUTH_SECRET=<secret> \
>   -e NEXT_AUTH_SSO_PROVIDERS=microsoft-entra-id \
>   -e AUTH_MICROSOFT_ENTRA_ID_SECRET= \
>   -e AUTH_MICROSOFT_ENTRA_ID_ID= \
>   -e AUTH_MICROSOFT_ENTRA_ID_ISSUER= \
>   -e ACCESS_CODE=disable \
>   -e NEXTAUTH_SECRET= \
>   -e ENABLE_OAUTH_SSO=1 \
>   -e APP_URL=https://<name>.<ts-net>.ts.net/ \
>   -p 3210:3210  lobehub/lobe-chat
> ```
> 
> <img alt="image" width="1377" src="https://private-user-images.githubusercontent.com/13883964/389345725-b2c4882d-0817-43ec-8754-04ac39435cf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkxODI0MTcsIm5iZiI6MTczOTE4MjExNywicGF0aCI6Ii8xMzg4Mzk2NC8zODkzNDU3MjUtYjJjNDg4MmQtMDgxNy00M2VjLTg3NTQtMDRhYzM5NDM1Y2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjEwVDEwMDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZTFjYTYyZjgxNmZkZWU0OGVhYTliMzc4MzkwMzM5ZDE3NDYwNDI5NmE1YjRkNDdiOTQzNTU3MzZmYWFiMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TB35PHgdtW5UM_iAdsfkpKYhFE_nynE3Suu-D0ooiJw">



> Hi [@gemnioo](https://github.com/gemnioo)
> 
> I am using this configuration with ts net command which is running well, cannot reproduce your error.
> 
> I suggest using an incognito window to try again.
> 
> ```
> tailscale serve http://localhost:3210
> ```
> 
> ```
> docker run -it --rm \
>   -e KEY_VAULTS_SECRET=<secret> \
>   -e NEXTAUTH_URL=https://<name>.<ts-net>.ts.net/api/auth  \
>   -e NEXT_AUTH_SECRET=<secret> \
>   -e NEXT_AUTH_SSO_PROVIDERS=microsoft-entra-id \
>   -e AUTH_MICROSOFT_ENTRA_ID_SECRET= \
>   -e AUTH_MICROSOFT_ENTRA_ID_ID= \
>   -e AUTH_MICROSOFT_ENTRA_ID_ISSUER= \
>   -e ACCESS_CODE=disable \
>   -e NEXTAUTH_SECRET= \
>   -e ENABLE_OAUTH_SSO=1 \
>   -e APP_URL=https://<name>.<ts-net>.ts.net/ \
>   -p 3210:3210  lobehub/lobe-chat
> ```
> 
> <img alt="image" width="1377" src="https://private-user-images.githubusercontent.com/13883964/389345725-b2c4882d-0817-43ec-8754-04ac39435cf2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkxODI0MTcsIm5iZiI6MTczOTE4MjExNywicGF0aCI6Ii8xMzg4Mzk2NC8zODkzNDU3MjUtYjJjNDg4MmQtMDgxNy00M2VjLTg3NTQtMDRhYzM5NDM1Y2YyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAyMTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMjEwVDEwMDgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2ZTFjYTYyZjgxNmZkZWU0OGVhYTliMzc4MzkwMzM5ZDE3NDYwNDI5NmE1YjRkNDdiOTQzNTU3MzZmYWFiMjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.TB35PHgdtW5UM_iAdsfkpKYhFE_nynE3Suu-D0ooiJw">

@EINDEX 请问大佬，为什么你的应用名字可以设置为EINDEX ? 这是改源码的还是有环境变量参数可以设置？谢谢！

**Comment by EINDEX** [comment]
> [@EINDEX](https://github.com/EINDEX) 请问大佬，为什么你的应用名字可以设置为EINDEX ? 这是改源码的还是有环境变量参数可以设置？谢谢！

@mengdahuang 这是登录的用户名
