### ISSUE TITLE
[Bug] lobechat-database-docker quick deploy script produces broken startup

### ISSUE THREAD

**Issue by anphex** [lobehub/lobe-chat#4730]
### 📦 Environment

Docker

### 📌 Version

latest as of 19th november 2024

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

`      
panic: dial tcp 172.30.0.3:5432: connect: no route to host

goroutine 1 [running]:

github.com/casdoor/casdoor/object.InitAdapter()

	/go/src/casdoor/object/ormer.go:91 +0x246

main.main()

	/go/src/casdoor/main.go:35 +0x30

panic: dial tcp 172.30.0.3:5432: connect: no route to host

goroutine 1 [running]:

github.com/casdoor/casdoor/object.InitAdapter()

	/go/src/casdoor/object/ormer.go:91 +0x246

main.main()

	/go/src/casdoor/main.go:35 +0x30`

This is what happens when I run this command as stated in your guide:
`bash <(curl -fsSL https://raw.githubusercontent.com/lobehub/lobe-chat/HEAD/docker-compose/local/setup.sh) -f`

My understanding is this should work out of the box, but why can't cassador reach the postgres database?

Also the lobechat-chat container can't reach the database
`  errno: -113,

  code: 'EHOSTUNREACH',

  syscall: 'connect',

  address: '172.30.0.3',


  port: 5432

}

❌ Error during DB migration:

Error: 🔴 Process exited with code 1

    at ChildProcess.<anonymous> (/app/startServer.js:88:68)

    at ChildProcess.emit (node:events:519:28)

    at maybeClose (node:internal/child_process:1105:16)

    at ChildProcess._handle.onexit (node:internal/child_process:305:5)`

### 📷 Recurrence Steps

Follow this guide step by step up until 
`docker compose up -d`

### 🚦 Expected Behavior

Clean start of the lobechat-database compose environment.

**Comment by arvinxx** [comment]
@hezhijie0327 help to check it?

**Comment by hezhijie0327** [comment]
Seems `postgresql` service not started?

Casdoor Conf:
https://github.com/lobehub/lobe-chat/blob/aaae0596aca743d8ae6adc1aec62777dc8fb105c/docker-compose/local/docker-compose.yml#L60

**Comment by anphex** [comment]
![image](https://github.com/user-attachments/assets/0c915843-eec8-467f-a3e7-5862e711665a)

This are the containers right after startup. Cassdor crashes because of unreachable postgres database. Lobechat-chat shows "healthy" even though internally the logs say:

```
> [Database] Start to migration...
> 
> ❌ Database migrate failed. Please check your database is valid and DATABASE_URL is set correctly. The error detail is below:
> 
> Error: connect EHOSTUNREACH 192.168.0.2:5432
> 
>     at /app/node_modules/.pnpm/pg-pool@3.7.0_pg@8.13.1/node_modules/pg-pool/index.js:45:11
> 
>     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
> 
>     at async PgDialect.migrate (/app/node_modules/drizzle-orm/pg-core/dialect.cjs:56:5)
> 
>     at async Object.migrate (/app/node_modules/drizzle-orm/node-postgres/migrator.cjs:27:3)
> 
>     at async runMigrations (/app/docker.cjs:17:3) {
> 
>   errno: -113,
> 
>   code: 'EHOSTUNREACH',
> 
>   syscall: 'connect',
> 
>   address: '192.168.0.2',
> 
> 
>   port: 5432
> 
> }
> 
> ❌ Error during DB migration:
> 
> Error: 🔴 Process exited with code 1
> 
>     at ChildProcess.<anonymous> (/app/startServer.js:88:68)
> 
>     at ChildProcess.emit (node:events:519:28)
> 
>     at maybeClose (node:internal/child_process:1105:16)
> 
>     at ChildProcess._handle.onexit (node:internal/child_process:305:5)
```


This is the postgres log right after startup:

```
> PostgreSQL Database directory appears to contain a database; Skipping initialization
> 
> 2024-11-19 06:54:11.871 UTC [1] LOG:  starting PostgreSQL 16.4 (Debian 16.4-1.pgdg120+2) on x86_64-pc-linux-gnu, compiled by gcc (Debian 12.2.0-14) 12.2.0, 64-bit
> 
> 2024-11-19 06:54:11.881 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
> 
> 2024-11-19 06:54:11.881 UTC [1] LOG:  listening on IPv6 address "::", port 5432
> 
> 2024-11-19 06:54:11.883 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
> 
> 2024-11-19 06:54:11.888 UTC [29] LOG:  database system was shut down at 2024-11-18 20:25:49 UTC
> 
> 2024-11-19 06:54:11.898 UTC [1] LOG:  database system is ready to accept connections
> 
> 2024-11-19 06:59:11.988 UTC [27] LOG:  checkpoint starting: time
> 
> 2024-11-19 06:59:11.997 UTC [27] LOG:  checkpoint complete: wrote 3 buffers (0.0%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.002 s, sync=0.002 s, total=0.010 s; sync files=2, longest=0.001 s, average=0.001 s; distance=0 kB, estimate=0 kB; lsn=0/1953980, redo lsn=0/1953948
> 
> 
```

**Comment by anphex** [comment]
The problem is on my server, not on your setup files. I want to apologize and look into this issue n my server. Seems that docker networking is broken on my system.

I tested it on another server and there it worked perfectly. Thank you for your effort and sorry for basically wasting your time :(

**Comment by anphex** [comment]
I just want to add my solution for anyone trying to Deploy it on a Virtualmin Managed Server. I do not remember changing any config related to FirewallD and docker, so I think the flaw is by design from Virtualmin. Here is the solution achieved with the help of Claude Sonnet 3.5 November edition:

> The core issue was a conflict between Docker's network management and firewalld zones. Here's what happened:
> 
> The main error was:
> 
> CopyFailed to program NAT chain: ZONE_CONFLICT: 'docker0' already bound to 'trusted'
> The problem occurred because:
> 
> Docker manages its own networking and creates its own firewall rules
> We had accidentally assigned the docker0 interface to the trusted zone in firewalld
> This created a conflict because the same network interface (docker0) was being managed by two different systems
> 
> It's like having two traffic cops trying to direct traffic at the same intersection - they'll conflict with each other!
> The fix involved:
> 
> Removing the docker0 interface from the trusted zone
> Cleaning up the Docker network configurations
> Letting Docker manage its own networking through its default docker zone
> 
> Best practices going forward:
> 
> Let Docker manage its own networking through the docker zone
> Don't manually assign Docker's interfaces to other firewalld zones
> If you need to add specific rules, add them to the docker zone rather than trusted
> 
> This is why it started working on the clean test network we created - it didn't have any conflicting zone assignments. The solution ensured that only one system (Docker) was managing the container networking, removing the conflict.
