### ISSUE TITLE
[Bug] 书生浦语使用Artifacts插件就会报错

### ISSUE THREAD

**Issue by SAnBlog** [lobehub/lobe-chat#4733]
### 📦 部署环境

Docker

### 📌 软件版本

v1.32.0

### 💻 系统环境

macOS

### 🌐 浏览器

Chrome

### 🐛 问题描述

![image](https://github.com/user-attachments/assets/abc119cc-d115-4a61-a8d2-c931d167409b)

**Comment by hezhijie0327** [comment]
这个报错有点神奇，是去阿里云的...

```
  stack: 'Error: 405 \n\t<!DOCTYPE html>\n<html lang="zh-cn">\n\n<head>\n  <meta charset="utf-8">\n  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">\n  <meta name="data-spm" content="a3c0e" />\n  <title>405</title>\n  <style>\n    html, body, div, a, h2, p { margin: 0; padding: 0;  }\n    a { text-decoration: none; color: #3b6ea3;  }\n    .container { width: 1000px; margin: auto; color: #696969; }\n    .header { padding: 50px 0; }\n    .header .message { height: 36px; padding-left: 120px; background: url(https://errors.aliyun.com/images/TB1TpamHpXXXXaJXXXXeB7nYVXX-104-162.png) no-repeat 0 -128px; line-height: 36px; }\n    .main { padding: 50px 0; background: #f4f5f7; }\n    .main img { position: relative; left: 120px; }\n    .footer { margin-top: 30px; text-align: right; }\n    .footer a { padding: 8px 30px; border-radius: 10px; border: 1px solid #4babec; }\n    .footer a:hover { opacity: .8; }\n    .alert-shadow { display: none; position: absolute; top: 0; left: 0; width: 100%; height: 100%; background: #999; opacity: .5; }\n    .alert { display: none; position: absolute; top: 200px; left: 50%; width: 600px; margin-left: -300px; padding-bottom: 25px; border: 1px solid #ddd; box-shadow: 0 2px 2px 1px rgba(0, 0, 0, .1); background: #fff; font-size: 14px; color: #696969; }\n    .alert h2 {  margin: 0 2px; padding: 10px 15px 5px 15px; font-size: 14px; font-weight: normal; border-bottom: 1px solid #ddd; }\n    .alert a { display: block; position: absolute; right: 10px; top: 8px; width: 30px; height: 20px; text-align: center; }\n    .alert p {  padding: 20px 15px; }\n  </style>\n</head>\n\n<body data-spm="7663354">\n  <div data-spm="1998410538">\n    <div class="header">\n      <div class="container">\n        <div class="message">\n          很抱歉，由于您访问的URL有可能对网站造成安全威胁，您的 访问被阻断。\n\t\t  <div>您的请求ID是：<strong>\n\t\t  ff3564ab-9e6b-4d15-aae1-5c27834fb1e2\n\t\t  </strong></div>\n        </div>\n      </div>\n    </div>\n    <div class="main">\n      <div class="container">\n        <img src="https://errors.aliyun.com/images/TB15QGaHpXXXXXOaXXXXia39XXX-660-117.png" />\n      </div>\n    </div>\n    <div class="footer">\n      <div class="container">\n        <a target="_blank" id="report" href="javascript:;" data-spm-click="gostr=/waf.123.123;locaid=d001;"> 误报反馈</a>\n      </div>\n    </div>\n  </div>\n  <div id="alertShadow" class="alert-shadow"></div>\n  <div id="alertContainer" class="alert">\n    <h2>提示：<a href="javascript:;" title="关闭" id="closeAlert">X</a></h2>\n    <p>感谢您的反馈，应用防火墙会尽快进行分析和确认。</p>\n  </div>\n  <script>\n    function show() {\n      var g = function(ele) { return document.getElementById(ele); };\n      var reportHandle = g(\'report\');\n      var alertShadow = g(\'alertShadow\');\n      var alertContainer = g(\'alertContainer\');\n      var closeAlert = g(\'closeAlert\');\n      var own = {};\n      own.report = function() {\n        // SPM\n        own.alert();\n      };\n      own.alert = function() {\n        alertShadow.style.display = \'block\';\n        alertContainer.style.display = \'block\';\n      };\n      own.close = function() {\n        alertShadow.style.display = \'none\';\n        alertContainer.style.display = \'none\';\n      };\n    };\n  </script>\n</body>\n\n</html>\n\t\n    at $.generate (/app/.next/server/edge-chunks/323.js:4:1897)\n    at sW.makeStatusError (/app/.next/server/edge-chunks/323.js:4:15336)\n    at sW.makeRequest (/app/.next/server/edge-chunks/323.js:4:16276)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.chat (/app/.next/server/edge-chunks/10.js:9:3864)\n    at async /app/.next/server/app/(backend)/webapi/chat/[provider]/route.js:1:1502\n    at async /app/.next/server/edge-chunks/507.js:1:90725\n    at async $.execute (/app/.next/server/edge-chunks/507.js:1:88435)\n    at async $.handle (/app/.next/server/edge-chunks/507.js:1:91992)\n    at async ex.handler (/app/.next/server/edge-chunks/507.js:2:32453)',
```

**Comment by arvinxx** [comment]
进 waf 了吗…

**Comment by arvinxx** [comment]
@SAnBlog 感觉这个问题和你网络有关系，应该跟 LobeChat 的实现没啥关系？

**Comment by SAnBlog** [comment]
应该不是网络问题,本地有代理跑也是报错,云跑也是同一个错
