### ISSUE TITLE
[Bug] 「部署问题」Casdoor 配置与 NextAuth 认证错误

### ISSUE THREAD

**Issue by Shukino20001015** [lobehub/lobe-chat#4760]
### 📦 Environment

Docker

### 📌 Version

1.0

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

你好，在按照官方文档 https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose 进行部署时遇到了问题。

当前进度：

已完成"发布到生产（IP 模式）"的配置步骤
Casdoor 通过 MinIO buckets 上传资源成功
Lobe UI 界面可以访问
遇到的问题：

登录时显示页面存在问题
后台日志显示 NextAuth 错误：
log

‘’‘
[auth][error] TypeError: fetch failed
...
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
’‘’

观察到的现象： 在 Casdoor 上：

每次重启服务后，MinIO 服务商的配置会重置
应用的转发 API 路径配置也需要重新设置
疑问：

Casdoor 配置无法持久化是否是导致认证失败的原因？
如何解决这些配置在重启后丢失的问题？
请问有什么解决方案？感谢帮助！

### 📷 Recurrence Steps

根据文档做的步骤，没有啥变动，顶多加了几个llm api 环境变量

### 🚦 Expected Behavior

我的服务能够在局域网/公网中正常使用，即可以用户注册使用服务

### 📝 Additional Information

123

**Comment by Shukino20001015** [comment]
这是casdoor重启前：
![image](https://github.com/user-attachments/assets/d6e4d9dd-1b5f-4ba2-bded-c190939bb45c)

这是重启后：
![image](https://github.com/user-attachments/assets/081adc54-da17-4ed7-822c-97542e6aa652)

配置似乎没有持久化，我想知道是不是这个原因导致我的用户注册失败的？

**Comment by SpeedupMaster** [comment]
用啥部署的？配置应该是有持久化储存的

**Comment by Shukino20001015** [comment]
> 用啥部署的？配置应该是有持久化储存的

![image](https://github.com/user-attachments/assets/6819a667-b353-48d4-8f03-d5c92ff483a9)

![image](https://github.com/user-attachments/assets/b0f1c2c4-5731-46c9-ae44-bd704813f902)

现在我修改了外部的init_data.json,现在重启是可以看到配置了，提供商上传资源正常，但是lobe chat 界面登录还是存在问题，最终会得到”http://192.168.2.6:3210/api/auth/error?error=Configuration“这个结果。不理解为啥还是不能实现本地用户登录&注册？

**Comment by SpeedupMaster** [comment]
> > 用啥部署的？配置应该是有持久化储存的
> 
> ![image](https://private-user-images.githubusercontent.com/61822951/389156677-6819a667-b353-48d4-8f03-d5c92ff483a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzExNDYsIm5iZiI6MTczMjMzMDg0NiwicGF0aCI6Ii82MTgyMjk1MS8zODkxNTY2NzctNjgxOWE2NjctYjM1My00OGQ0LThmMDMtZDVjOTJmZjQ4M2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAzMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2I2MmJhMDljNDc1YWNmMjg5NTcxZGRmN2U2MDcyNzY1MzQ4ZTg0NDMzZDRiZjEyZTE3NDdlY2NjNGE3ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vI5QaUzIMgTAkH3_qwHQrvUCYrxoh6-5a4z1i9l20VE)
> 
> ![image](https://private-user-images.githubusercontent.com/61822951/389156727-b0f1c2c4-5731-46c9-ae44-bd704813f902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzExNDYsIm5iZiI6MTczMjMzMDg0NiwicGF0aCI6Ii82MTgyMjk1MS8zODkxNTY3MjctYjBmMWMyYzQtNTczMS00NmM5LWFlNDQtYmQ3MDQ4MTNmOTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAzMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZmFhMTNmZDRjNThlODMyNjNmOWUwNzkwOGM0MjYzNzFjMTU1ZTBmYzhkMjk4MzI3NTc4MDhlNTc2ZGUxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rybK1D8nqhyhjCuPlmGaaYqP5t1UzMjp81rf3mu5Xko)
> 
> 现在我修改了外部的init_data.json,现在重启是可以看到配置了，提供商上传资源正常，但是lobe chat 界面登录还是存在问题，最终会得到”[http://192.168.2.6:3210/api/auth/error?error=Configuration“这个结果。不理解为啥还是不能实现本地用户登录&注册？](http://192.168.2.6:3210/api/auth/error?error=Configuration%E2%80%9C%E8%BF%99%E4%B8%AA%E7%BB%93%E6%9E%9C%E3%80%82%E4%B8%8D%E7%90%86%E8%A7%A3%E4%B8%BA%E5%95%A5%E8%BF%98%E6%98%AF%E4%B8%8D%E8%83%BD%E5%AE%9E%E7%8E%B0%E6%9C%AC%E5%9C%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95&%E6%B3%A8%E5%86%8C%EF%BC%9F)

你需要修改下载下来的 docker-compose.yml 文件，执行一次全文替换，将 localhost 替换为 your_server_ip。
这个有替换吗？

**Comment by Shukino20001015** [comment]
> > > 用啥部署的？配置应该是有持久化储存的
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/61822951/389156677-6819a667-b353-48d4-8f03-d5c92ff483a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzExNDYsIm5iZiI6MTczMjMzMDg0NiwicGF0aCI6Ii82MTgyMjk1MS8zODkxNTY2NzctNjgxOWE2NjctYjM1My00OGQ0LThmMDMtZDVjOTJmZjQ4M2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAzMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2I2MmJhMDljNDc1YWNmMjg5NTcxZGRmN2U2MDcyNzY1MzQ4ZTg0NDMzZDRiZjEyZTE3NDdlY2NjNGE3ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vI5QaUzIMgTAkH3_qwHQrvUCYrxoh6-5a4z1i9l20VE)
> > ![image](https://private-user-images.githubusercontent.com/61822951/389156727-b0f1c2c4-5731-46c9-ae44-bd704813f902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzExNDYsIm5iZiI6MTczMjMzMDg0NiwicGF0aCI6Ii82MTgyMjk1MS8zODkxNTY3MjctYjBmMWMyYzQtNTczMS00NmM5LWFlNDQtYmQ3MDQ4MTNmOTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAzMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZmFhMTNmZDRjNThlODMyNjNmOWUwNzkwOGM0MjYzNzFjMTU1ZTBmYzhkMjk4MzI3NTc4MDhlNTc2ZGUxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rybK1D8nqhyhjCuPlmGaaYqP5t1UzMjp81rf3mu5Xko)
> > 现在我修改了外部的init_data.json,现在重启是可以看到配置了，提供商上传资源正常，但是lobe chat 界面登录还是存在问题，最终会得到”[http://192.168.2.6:3210/api/auth/error?error=Configuration“这个结果。不理解为啥还是不能实现本地用户登录&注册？](http://192.168.2.6:3210/api/auth/error?error=Configuration%E2%80%9C%E8%BF%99%E4%B8%AA%E7%BB%93%E6%9E%9C%E3%80%82%E4%B8%8D%E7%90%86%E8%A7%A3%E4%B8%BA%E5%95%A5%E8%BF%98%E6%98%AF%E4%B8%8D%E8%83%BD%E5%AE%9E%E7%8E%B0%E6%9C%AC%E5%9C%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95&%E6%B3%A8%E5%86%8C%EF%BC%9F)
> 
> 你需要修改下载下来的 docker-compose.yml 文件，执行一次全文替换，将 localhost 替换为 your_server_ip。 这个有替换吗？

"sed -i 's/localhost/192.168.2.6/g' docker-compose.yml"替换了

**Comment by SpeedupMaster** [comment]
> > > > 用啥部署的？配置应该是有持久化储存的
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/61822951/389156677-6819a667-b353-48d4-8f03-d5c92ff483a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzExNDYsIm5iZiI6MTczMjMzMDg0NiwicGF0aCI6Ii82MTgyMjk1MS8zODkxNTY2NzctNjgxOWE2NjctYjM1My00OGQ0LThmMDMtZDVjOTJmZjQ4M2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAzMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2I2MmJhMDljNDc1YWNmMjg5NTcxZGRmN2U2MDcyNzY1MzQ4ZTg0NDMzZDRiZjEyZTE3NDdlY2NjNGE3ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vI5QaUzIMgTAkH3_qwHQrvUCYrxoh6-5a4z1i9l20VE)
> > > ![image](https://private-user-images.githubusercontent.com/61822951/389156727-b0f1c2c4-5731-46c9-ae44-bd704813f902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzExNDYsIm5iZiI6MTczMjMzMDg0NiwicGF0aCI6Ii82MTgyMjk1MS8zODkxNTY3MjctYjBmMWMyYzQtNTczMS00NmM5LWFlNDQtYmQ3MDQ4MTNmOTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAzMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZmFhMTNmZDRjNThlODMyNjNmOWUwNzkwOGM0MjYzNzFjMTU1ZTBmYzhkMjk4MzI3NTc4MDhlNTc2ZGUxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rybK1D8nqhyhjCuPlmGaaYqP5t1UzMjp81rf3mu5Xko)
> > > 现在我修改了外部的init_data.json,现在重启是可以看到配置了，提供商上传资源正常，但是lobe chat 界面登录还是存在问题，最终会得到”[http://192.168.2.6:3210/api/auth/error?error=Configuration“这个结果。不理解为啥还是不能实现本地用户登录&注册？](http://192.168.2.6:3210/api/auth/error?error=Configuration%E2%80%9C%E8%BF%99%E4%B8%AA%E7%BB%93%E6%9E%9C%E3%80%82%E4%B8%8D%E7%90%86%E8%A7%A3%E4%B8%BA%E5%95%A5%E8%BF%98%E6%98%AF%E4%B8%8D%E8%83%BD%E5%AE%9E%E7%8E%B0%E6%9C%AC%E5%9C%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95&%E6%B3%A8%E5%86%8C%EF%BC%9F)
> > 
> > 
> > 你需要修改下载下来的 docker-compose.yml 文件，执行一次全文替换，将 localhost 替换为 your_server_ip。 这个有替换吗？
> 
> "sed -i 's/localhost/192.168.2.6/g' docker-compose.yml"替换了

那配置应该没问题的啊，可以检查下docker-compose.yml文件，确认下是否成功替换了

**Comment by Shukino20001015** [comment]
> > > > > 用啥部署的？配置应该是有持久化储存的
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/61822951/389156677-6819a667-b353-48d4-8f03-d5c92ff483a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzExNDYsIm5iZiI6MTczMjMzMDg0NiwicGF0aCI6Ii82MTgyMjk1MS8zODkxNTY2NzctNjgxOWE2NjctYjM1My00OGQ0LThmMDMtZDVjOTJmZjQ4M2E5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAzMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2I2MmJhMDljNDc1YWNmMjg5NTcxZGRmN2U2MDcyNzY1MzQ4ZTg0NDMzZDRiZjEyZTE3NDdlY2NjNGE3ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.vI5QaUzIMgTAkH3_qwHQrvUCYrxoh6-5a4z1i9l20VE)
> > > > ![image](https://private-user-images.githubusercontent.com/61822951/389156727-b0f1c2c4-5731-46c9-ae44-bd704813f902.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzMzExNDYsIm5iZiI6MTczMjMzMDg0NiwicGF0aCI6Ii82MTgyMjk1MS8zODkxNTY3MjctYjBmMWMyYzQtNTczMS00NmM5LWFlNDQtYmQ3MDQ4MTNmOTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDAzMDA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZmFhMTNmZDRjNThlODMyNjNmOWUwNzkwOGM0MjYzNzFjMTU1ZTBmYzhkMjk4MzI3NTc4MDhlNTc2ZGUxODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rybK1D8nqhyhjCuPlmGaaYqP5t1UzMjp81rf3mu5Xko)
> > > > 现在我修改了外部的init_data.json,现在重启是可以看到配置了，提供商上传资源正常，但是lobe chat 界面登录还是存在问题，最终会得到”[http://192.168.2.6:3210/api/auth/error?error=Configuration“这个结果。不理解为啥还是不能实现本地用户登录&注册？](http://192.168.2.6:3210/api/auth/error?error=Configuration%E2%80%9C%E8%BF%99%E4%B8%AA%E7%BB%93%E6%9E%9C%E3%80%82%E4%B8%8D%E7%90%86%E8%A7%A3%E4%B8%BA%E5%95%A5%E8%BF%98%E6%98%AF%E4%B8%8D%E8%83%BD%E5%AE%9E%E7%8E%B0%E6%9C%AC%E5%9C%B0%E7%94%A8%E6%88%B7%E7%99%BB%E5%BD%95&%E6%B3%A8%E5%86%8C%EF%BC%9F)
> > > 
> > > 
> > > 你需要修改下载下来的 docker-compose.yml 文件，执行一次全文替换，将 localhost 替换为 your_server_ip。 这个有替换吗？
> > 
> > 
> > "sed -i 's/localhost/192.168.2.6/g' docker-compose.yml"替换了
> 
> 那配置应该没问题的啊，可以检查下docker-compose.yml文件，确认下是否成功替换了

是啊，lobechat页面可以显示出来，但是登录注册跳转到casdoor失败，然后是log里有“[auth][error] TypeError: fetch failed
    at node:internal/deps/undici/undici:13185:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async iB (/app/.next/server/chunks/39652.js:368:46804)
    at async iG (/app/.next/server/chunks/39652.js:368:49678)
    at async i0 (/app/.next/server/chunks/39652.js:368:52320)
    at async i2 (/app/.next/server/chunks/39652.js:368:56476)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
    at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/base-server.js:1359:42)
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}
[auth][error] TypeError: fetch failed”这种字样，我不大清楚该如何解决了。。

**Comment by arvinxx** [comment]
TypeError: fetch failed 说明是请求失败，检查下连通性是否正常。确认下没有被墙之类的

**Comment by Sun-drenched** [comment]
有配置NEXTAUTH_URL吗？

**Comment by Sun-drenched** [comment]
[NextAuth] Error: {
cause: 'Configuration',
message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
name: 'NextAuth Error'

看上去还是配置问题，你贴一下有关变量呢？我没有用官方教程里给的一键脚本or配置，手动配置后casdoor是正常的。

**Comment by Shukino20001015** [comment]
> @Shukino20001015
> 
> `TypeError: fetch failed` 说明是请求失败，检查下连通性是否正常。确认下没有被墙之类的

解决了，发现是 数据库防火墙没有打开，其他开了

**Comment by Shukino20001015** [comment]
> > @Shukino20001015
> > `TypeError: fetch failed` 说明是请求失败，检查下连通性是否正常。确认下没有被墙之类的
> 
> 解决了，发现是 数据库防火墙没有打开，其他开了



> @Shukino20001015
> 
> `TypeError: fetch failed` 说明是请求失败，检查下连通性是否正常。确认下没有被墙之类的

3q
