### ISSUE TITLE
[Bug] Creating new assistant with only one image returns error, must include text

### ISSUE THREAD

**Issue by danbus** [lobehub/lobe-chat#4805]
### 📦 Environment

Docker

### 📌 Version

v1.34.1

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

聊天时如果只发送一张图片则返回错误，已设置角色描述，100%复现， 如果想正常运行则需要添加图片并包含文字描述
![aa](https://github.com/user-attachments/assets/cd13d2a5-fe13-462c-a703-beeaadd0525a)

正常：
![bb](https://github.com/user-attachments/assets/fb6d4ebe-2a56-41f0-b515-0cad17e5d3c8)

### 📷 Recurrence Steps

1.设置助手提示
2.上传一张图片，不包含任何文字提示

### 🚦 Expected Behavior

在设置助手提示后，单独上传一张照片也可正常返回

### 📝 Additional Information

无

**Comment by arvinxx** [comment]
@danbus 服务端报啥错

**Comment by danbus** [comment]
`lobe-chat    |  ⨯ Error: failed to pipe response
lobe-chat    |     at pipeToNodeResponse (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/pipe-readable.js:126:15)
lobe-chat    |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lobe-chat    |     at async NextNodeServer.runEdgeFunction (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/next-server.js:1250:13)
lobe-chat    |     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/next-server.js:248:37)
lobe-chat    |     at async NextNodeServer.handleRequestImpl (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/base-server.js:813:17)
lobe-chat    |     at async invokeRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/router-server.js:173:21)
lobe-chat    |     at async handleRequest (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/router-server.js:350:24)
lobe-chat    |     at async requestHandlerImpl (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/router-server.js:374:13)
lobe-chat    |     at async Server.requestListener (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/start-server.js:141:13) {
lobe-chat    |   [cause]: ValidationException: messages: text content blocks must be non-empty
lobe-chat    |       at er (/app/.next/server/edge-chunks/484.js:5:29463)
lobe-chat    |       at eu (/app/.next/server/edge-chunks/484.js:5:30539)
lobe-chat    |       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
lobe-chat    |       at async /app/.next/server/edge-chunks/484.js:5:29865
lobe-chat    |       at async _.deserializer (/app/.next/server/edge-chunks/610.js:11:12466)
lobe-chat    |       at async _.asyncIterator (/app/.next/server/edge-chunks/610.js:11:10997)
lobe-chat    |       at async ed (/app/.next/server/edge-chunks/736.js:9:11992)
lobe-chat    |       at async Object.pull (/app/.next/server/edge-chunks/484.js:8:94519) {
lobe-chat    |     '$fault': 'client',
lobe-chat    |     '$metadata': {
lobe-chat    |       httpStatusCode: undefined,
lobe-chat    |       requestId: undefined,
lobe-chat    |       extendedRequestId: undefined,
lobe-chat    |       cfId: undefined
lobe-chat    |     }
lobe-chat    |   }
lobe-chat    | }
lobe-chat    | Error: aborted
lobe-chat    |     at abortIncoming (node:_http_server:796:17)
lobe-chat    |     at socketOnClose (node:_http_server:790:3)
lobe-chat    |     at Socket.emit (node:events:530:35)
lobe-chat    |     at TCP.<anonymous> (node:net:343:12)
lobe-chat    |     at TCP.callbackTrampoline (node:internal/async_hooks:130:17) {
lobe-chat    |   code: 'ECONNRESET'
lobe-chat    | }
`
