### ISSUE TITLE
[Bug] xAI未开启“使用客户端请求模式”时，请求异常

### ISSUE THREAD

**Issue by jiongjiongJOJO** [lobehub/lobe-chat#4810]
### 📦 部署环境

Docker

### 📌 软件版本

v1.34.1（docker:7bd808c546958a218eadfa065e621fd0f436c3be465108e7ed4ebdb9cf6f3ae7）

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

关闭"使用客户端请求模式"功能后，无法使用xAI

### 📷 复现步骤

![PixPin_2024-11-27_14-28-19](https://github.com/user-attachments/assets/3766f1c9-526d-4865-8021-aa6f2f29d4f4)
开关打开：正常请求，且使用正常

![PixPin_2024-11-27_14-29-21](https://github.com/user-attachments/assets/708e7fdd-15f2-498b-9a1a-57773f603014)
开关关闭：无法请求，请求错误内容：
```json
{"body":{"error":{"headers":{"cf-ray":"***********","connection":"keep-alive","content-encoding":"br","content-type":"text/html","date":"Wed, 27 Nov 2024 06:28:41 GMT","server":"cloudflare","strict-transport-security":"max-age=31536000","transfer-encoding":"chunked","vary":"Accept-Encoding"},"stack":"Error: 403 <!doctype html>\n<html>\n<body>\n<p>This service is not available in your region.</p>\n</body>\n</html>\n    at $.generate (/app/.next/server/edge-chunks/153.js:4:1768)\n    at sW.makeStatusError (/app/.next/server/edge-chunks/153.js:4:15336)\n    at sW.makeRequest (/app/.next/server/edge-chunks/153.js:4:16276)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.chat (/app/.next/server/edge-chunks/736.js:9:3864)\n    at async /app/.next/server/app/(backend)/webapi/chat/[provider]/route.js:1:1486\n    at async /app/.next/server/edge-chunks/107.js:1:90728\n    at async $.execute (/app/.next/server/edge-chunks/107.js:1:88438)\n    at async $.handle (/app/.next/server/edge-chunks/107.js:1:91995)\n    at async ex.handler (/app/.next/server/edge-chunks/107.js:2:32453)","status":403},"endpoint":"https://api.x.ai/v1","provider":"xai"},"errorType":"ProviderBizError"}
```

### 🚦 期望结果

按钮开关均能正常使用

### 📝 补充信息

因为docker启动指令支持了 `XAI_API_KEY` 环境变量，就想着试一下xAI，结果启动后请求错误。

后面排查发现是因为关闭“使用客户端请求模式”功能后导致的，且docker启动环境变量中没找到指定开启“使用客户端请求模式”功能的内容（可能真的是有这个功能但是我没找到吧）。

另外官网的doc文档好像没有xAI相关的描述，还是翻了代码才找到的这个环境变量。

**Comment by jiongjiongJOJO** [comment]
补充docker启动指令：
```bash
docker run -d -p 3210:3210 \
  -e GOOGLE_API_KEY=xxxxxxxxxxxxxx \
  -e GOOGLE_PROXY_URL=xxxxxxxxxxxxxxx \
  -e GOOGLE_MODEL_LIST=xxxxxxxxxxxxxx \
  -e ENABLED_XAI=1 \
  -e XAI_API_KEY=xxxxxxxxxxxxx \
  --name lobe-chat \
  lobehub/lobe-chat
```

**Comment by hezhijie0327** [comment]
This service is not available in your region.

当前网络环境问题，配置下代理

补个完整 Error Code
```
{
  "error": {
    "headers": {
      "cf-ray": "8e9074557ae52f08-LAX",
      "connection": "keep-alive",
      "content-encoding": "br",
      "content-type": "text/html",
      "date": "Wed, 27 Nov 2024 07:37:42 GMT",
      "server": "cloudflare",
      "strict-transport-security": "max-age=31536000",
      "transfer-encoding": "chunked",
      "vary": "Accept-Encoding"
    },
    "stack": "Error: 403 <!doctype html>\n<html>\n<body>\n<p>This service is not available in your region.</p>\n</body>\n</html>\n    at $.generate (/app/.next/server/edge-chunks/153.js:4:1768)\n    at sW.makeStatusError (/app/.next/server/edge-chunks/153.js:4:15336)\n    at sW.makeRequest (/app/.next/server/edge-chunks/153.js:4:16276)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async Object.chat (/app/.next/server/edge-chunks/736.js:9:3864)\n    at async /app/.next/server/app/(backend)/webapi/chat/[provider]/route.js:1:1486\n    at async /app/.next/server/edge-chunks/107.js:1:90728\n    at async $.execute (/app/.next/server/edge-chunks/107.js:1:88438)\n    at async $.handle (/app/.next/server/edge-chunks/107.js:1:91995)\n    at async ex.handler (/app/.next/server/edge-chunks/107.js:2:32453)",
    "status": 403
  },
  "endpoint": "https://api.x.ai/v1",
  "provider": "xai"
}
```

**Comment by jiongjiongJOJO** [comment]
> 当前网络环境问题，配置下代理

抱歉，前段时间可以直连，我以为不用挂代理，没注意到这块🙄
