### ISSUE TITLE
[Bug] Auth errors when trying to configure lobechat with authelia/cloudflare

### ISSUE THREAD

**Issue by stone-w4tch3r** [lobehub/lobe-chat#4836]
### 📦 Environment

Docker

### 📌 Version

v1.34.5

### 💻 Operating System

Ubuntu

### 🌐 Browser

Firefox

### 🐛 Bug Description

I am trying to configure lobechat with authelia according to [docs](https://lobehub.com/docs/self-hosting/advanced/auth/next-auth/authelia) with caddy and docker compose.

But when clicking "log in" in lobechat UI I see error page. In docker logs there are auth errors: `UnknownAction: Cannot parse action at /api/auth/providers`.

In browser network console I see that request `GET https://lobechat.example.com/api/auth/session` returns 400 Bad Request.

I verified that authelia is up and running and can perform basic functions. 

<details>
<summary>Full logs</summary>

Docker compose:
```
...
lobe-app-container       | 🌐 DNS Server: [ '127.0.0.11' ]
lobe-app-container       | -------------------------------------
lobe-app-container       | [Database] Start to migration...
lobe-app-container       | ✅ database migration pass.
lobe-app-container       | -------------------------------------
lobe-app-container       |   ▲ Next.js 14.2.8
lobe-app-container       |   - Local:        http://localhost:3210
lobe-app-container       |   - Network:      http://0.0.0.0:3210
lobe-app-container       | 
lobe-app-container       |  ✓ Starting...
lobe-app-container       |  ✓ Ready in 126ms
lobe-app-container       | [NextAuth] Error: { cause: null, message: 'Unknown error type.', name: 'NextAuth Error' }
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/73905.js:1:37981
lobe-app-container       |     at tE (/app/.next/server/chunks/73905.js:1:38312)
lobe-app-container       |     at i2 (/app/.next/server/chunks/73905.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/73905.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/73905.js:1:37981
lobe-app-container       |     at tE (/app/.next/server/chunks/73905.js:1:38312)
lobe-app-container       |     at i2 (/app/.next/server/chunks/73905.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/73905.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/providers. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/73905.js:1:37981
lobe-app-container       |     at tE (/app/.next/server/chunks/73905.js:1:38312)
lobe-app-container       |     at i2 (/app/.next/server/chunks/73905.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/73905.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [NextAuth] Error: { cause: null, message: 'Unknown error type.', name: 'NextAuth Error' }
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/73905.js:1:37981
lobe-app-container       |     at tE (/app/.next/server/chunks/73905.js:1:38312)
lobe-app-container       |     at i2 (/app/.next/server/chunks/73905.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/73905.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/73905.js:1:37981
lobe-app-container       |     at tE (/app/.next/server/chunks/73905.js:1:38312)
lobe-app-container       |     at i2 (/app/.next/server/chunks/73905.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/73905.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/providers. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/73905.js:1:37981
lobe-app-container       |     at tE (/app/.next/server/chunks/73905.js:1:38312)
lobe-app-container       |     at i2 (/app/.next/server/chunks/73905.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/73905.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [NextAuth] Error: { cause: null, message: 'Unknown error type.', name: 'NextAuth Error' }
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/73905.js:1:37981
lobe-app-container       |     at tE (/app/.next/server/chunks/73905.js:1:38312)
lobe-app-container       |     at i2 (/app/.next/server/chunks/73905.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/73905.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
...
```

Authelia have no corresponding logs

Browser request
```
GET /api/auth/session HTTP/2
Host: lobechat.example.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:133.0) Gecko/20100101 Firefox/133.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br, zstd
Referer: https://lobechat.example.com/api/auth/error
Content-Type: application/json
DNT: 1
Sec-GPC: 1
Connection: keep-alive
Cookie: __Host-authjs.csrf-token=XXXXXX; __Secure-authjs.callback-url=https%3A%2F%2Flobechat.example.com; LOBE_LOCALE=en-US; LOBE_THEME_PRIMARY_COLOR=undefined; LOBE_THEME_NEUTRAL_COLOR=undefined; LOBE_THEME_APPEARANCE=dark
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Priority: u=4
TE: trailers
```
</details>

### 📷 Recurrence Steps

For full deploy code you can go to [authelia](https://github.com/stone-w4tch3r/devops/tree/main/selfhosting/authelia) and [lobechat](https://github.com/stone-w4tch3r/devops/tree/main/selfhosting/lobechat) projects.

Most important configuration:

authelia configuration.yml
```yml
...

session:
  secret: 'XXX'
  cookies:
    - domain: 'example.com'
      authelia_url: 'https://auth.example.com'
      default_redirection_url: 'https://example.com'

access_control:
  default_policy: 'deny'
  rules:
    - domain: 'test1.example.com'
      policy: 'two_factor'
    - domain: 'test2.example.com'
      policy: 'two_factor'

identity_providers:
  oidc:
    hmac_secret: 'XXX'
    jwks:
      - key: |
          -----BEGIN PRIVATE KEY-----
          XXX
          -----END PRIVATE KEY-----
    clients:
      - client_id: lobe-chat
        client_name: LobeChat
        client_secret: 'XXX'
        public: False
        authorization_policy: two_factor
        redirect_uris:
          - 'https://lobechat.example.com/api/auth/callback/authelia'
        scopes:
          - openid
          - profile
          - email
        userinfo_signed_response_alg: none
```

lobechat .env:
```dotenv
# Lobe settings
KEY_VAULTS_SECRET="XXX"
APP_URL="https://lobechat.example.com/"
NEXT_AUTH_SSO_PROVIDERS=authelia
NEXT_AUTH_SECRET="XXX"
AUTH_AUTHELIA_ID=lobe-chat
AUTH_AUTHELIA_SECRET=XXX
AUTH_AUTHELIA_ISSUER=https://auth.example.com
```

lobe docker compose entry:
```yml
  ...
  
  lobe:
    image: lobehub/lobe-chat-database
    container_name: lobe-app-container
    expose:
      - '${LOBE_PORT}'
    depends_on:
      - postgresql
      - minio
    environment:
      - 'NEXTAUTH_URL=${APP_URL}/api/auth/callback/authelia'

...
```

Open `lobechat.example.com` and click "login", you will see error page.

### 🚦 Expected Behavior

Login with authelia works

### 📝 Additional Information

I suppose something is missing in documentation. I will be glad to fix it after this issue will be resolved.

Or maybe some CORS stuff is not configured? This should not result in 400 Bad Request though

UPD: same error with cloudflare, [look](https://github.com/lobehub/lobe-chat/issues/4836#issuecomment-2526357725)

**Comment by stone-w4tch3r** [comment]
Guuys? No response for last weeks(

**Comment by stone-w4tch3r** [comment]
I used newly added debug env var, but logs are still not useful:

Note that I tried to configure cloudflare-zero-trust instead of authelia, but looks like issue is on lobechat's side

Right after loading app, button "login" not yet clicked:
```
lobe-app-container       | [Database] Start to migration...
lobe-app-container       | ✅ database migration pass.
lobe-app-container       | -------------------------------------
lobe-app-container       |   ▲ Next.js 14.2.8
lobe-app-container       |   - Local:        http://localhost:3210
lobe-app-container       |   - Network:      http://0.0.0.0:3210
lobe-app-container       | 
lobe-app-container       |  ✓ Starting...
lobe-app-container       |  ✓ Ready in 102ms
lobe-app-container       | [auth][warn][debug-enabled] Read more: https://warnings.authjs.dev#debug-enabled
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/59053.js:1:37982
lobe-app-container       |     at tE (/app/.next/server/chunks/59053.js:1:38313)
lobe-app-container       |     at i2 (/app/.next/server/chunks/59053.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/59053.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][debug]: request {}
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/59053.js:1:37982
lobe-app-container       |     at tE (/app/.next/server/chunks/59053.js:1:38313)
lobe-app-container       |     at i2 (/app/.next/server/chunks/59053.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/59053.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][debug]: request {}
```

After clicking "login":
```
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/providers. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/59053.js:1:37982
lobe-app-container       |     at tE (/app/.next/server/chunks/59053.js:1:38313)
lobe-app-container       |     at i2 (/app/.next/server/chunks/59053.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/59053.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][debug]: request {}
lobe-app-container       | [NextAuth] Error: { cause: null, message: 'Unknown error type.', name: 'NextAuth Error' }
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/installHook.js.map. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/59053.js:1:37982
lobe-app-container       |     at tE (/app/.next/server/chunks/59053.js:1:38313)
lobe-app-container       |     at i2 (/app/.next/server/chunks/59053.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/59053.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][debug]: request {}
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/59053.js:1:37982
lobe-app-container       |     at tE (/app/.next/server/chunks/59053.js:1:38313)
lobe-app-container       |     at i2 (/app/.next/server/chunks/59053.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/59053.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][debug]: request {}
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/session. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/59053.js:1:37982
lobe-app-container       |     at tE (/app/.next/server/chunks/59053.js:1:38313)
lobe-app-container       |     at i2 (/app/.next/server/chunks/59053.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/59053.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][debug]: request {}
lobe-app-container       | [auth][error] UnknownAction: Cannot parse action at /api/auth/installHook.js.map. Read more at https://errors.authjs.dev#unknownaction
lobe-app-container       |     at /app/.next/server/chunks/59053.js:1:37982
lobe-app-container       |     at tE (/app/.next/server/chunks/59053.js:1:38313)
lobe-app-container       |     at i2 (/app/.next/server/chunks/59053.js:368:53069)
lobe-app-container       |     at t (/app/.next/server/chunks/59053.js:368:63384)
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36938
lobe-app-container       |     at /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_30ee6726505e2ede0b5b6ba69e780ba9/node_modules/next/dist/server/lib/trace/tracer.js:140:36
lobe-app-container       |     at NoopContextManager.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/context/NoopContextManager.js:25:19)
lobe-app-container       |     at ContextAPI.with (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/api/context.js:60:46)
lobe-app-container       |     at NoopTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/NoopTracer.js:65:31)
lobe-app-container       |     at ProxyTracer.startActiveSpan (/app/node_modules/.pnpm/@opentelemetry+api@1.9.0/node_modules/@opentelemetry/api/build/src/trace/ProxyTracer.js:36:24)
lobe-app-container       | [auth][debug]: request {}
```

In browser console still 400

I hope you will be able to help me! Thanks

**Comment by stone-w4tch3r** [comment]
Okay, after many attempts I managed to fix issue. For me the key was to set `NEXTAUTH_URL=https://lobechat.example.com/api/auth`.

`https://chat.example.com/api/auth/callback/cloudflare-zero-trust` is incorrect for this env var and will lead to errors, same for authelia. In cloudflare dashboard or authelia config callback is same as in documentation.

Also when working with cloudflare it is important to save app configuration at the bottom of page.

tip: restart from scratch, follow lobe guides step by step without modifications, this helped me to narrow down the issue

Another note: I verified minio correctness and settings, check that you can open objects in the bucket via admin console. If objects will not load and you will encounter 403 error in browser network tab, verify minio CORS settings, also check [this](https://min.io/docs/minio/linux/integrations/setup-nginx-proxy-with-minio.html?ref=docs-redirect)

You can take a look at my configuration: [lobe](https://github.com/stone-w4tch3r/devops/tree/main/selfhosting/lobechat), [authelia](https://github.com/stone-w4tch3r/devops/tree/main/selfhosting/authelia), [minio](https://github.com/stone-w4tch3r/devops/tree/main/selfhosting/minio). Also in same repo there is a caddy config, but it is split into multiple files and may be not easy to understand
