### ISSUE TITLE
[Bug] Zeabur数据库版本部署报错，选择登录/注册后会出现页面遇到一点问题页面

### ISSUE THREAD

**Issue by Noah-Wu66** [lobehub/lobe-chat#4954]
### 📦 部署环境

Zeabur

### 📌 软件版本

LobeChat Database Version（Zeabur）

### 💻 系统环境

Other Linux

### 🌐 浏览器

Chrome

### 🐛 问题描述

按照教程做的，部署后选择登录/注册后可以正常进入注册界面，注册后会自动跳转到错误页面
![微信截图_20241210145330](https://github.com/user-attachments/assets/704bd234-5173-4e67-94c0-d84aeadfde53)

报错如下：
[auth][error] AdapterError: Read more at https://errors.authjs.dev#adaptererror

[auth][cause]: TypeError: Cannot read properties of undefined (reading 'trim')

    at createUser (/app/.next/server/app/(backend)/api/auth/[...nextauth]/route.js:1:7523)

    at r.<computed> (/app/.next/server/chunks/43505.js:1:43321)

    at rD (/app/.next/server/chunks/43505.js:368:3153)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async iz (/app/.next/server/chunks/43505.js:368:40734)

    at async i0 (/app/.next/server/chunks/43505.js:368:51902)

    at async i2 (/app/.next/server/chunks/43505.js:368:56596)

    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932

    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)

    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)

[auth][details]: {}

[auth][error] AdapterError: Read more at https://errors.authjs.dev#adaptererror

[auth][cause]: TypeError: Cannot read properties of undefined (reading 'trim')

    at createUser (/app/.next/server/app/(backend)/api/auth/[...nextauth]/route.js:1:7523)

    at r.<computed> (/app/.next/server/chunks/43505.js:1:43321)

    at rD (/app/.next/server/chunks/43505.js:368:3153)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

    at async iz (/app/.next/server/chunks/43505.js:368:40734)

    at async i0 (/app/.next/server/chunks/43505.js:368:51902)

    at async i2 (/app/.next/server/chunks/43505.js:368:56596)

    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932

    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)

    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)

[auth][details]: {}

[NextAuth] Error: {

  cause: 'Configuration',

  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',

  name: 'NextAuth Error'

}

**Comment by duskmoon314** [comment]
我在 v1.36.5 遇到了同样的问题，降级到 1.36.4 后没再遇到，尚不确定 1.36.6 是否解决此问题。

I encountered the same issue in v1.36.5, which was solved by downgrading to 1.36.4. I haven't checked 1.36.6.

**Comment by arvinxx** [comment]
@cy948 来看下？

**Comment by cy948** [comment]
用的哪个 sso provider 呢？

**Comment by duskmoon314** [comment]
我使用的是 logto，流程是按照 [docker-compose#发布到生产（域名模式）](https://lobehub.com/zh/docs/self-hosting/server-database/docker-compose#%E5%8F%91%E5%B8%83%E5%88%B0%E7%94%9F%E4%BA%A7%EF%BC%88%E5%9F%9F%E5%90%8D%E6%A8%A1%E5%BC%8F%EF%BC%89) 来进行的。

环境中除了流程提及的四个容器，还开了一个 traefik 作为反向代理。

**Comment by cy948** [comment]
目前先去logto的管理面板给用户设置一个邮箱吧，稍后我再推送修复的分支。
