### ISSUE TITLE
[Bug] 向量化失败

### ISSUE THREAD

**Issue by wangjianzzn** [lobehub/lobe-chat#5014]
### 📦 Environment

Docker

### 📌 Version

lobe-chat-database

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

next auth: undefined
next auth: undefined
{"level":30,"time":1734161596212,"pid":28,"hostname":"70497f2263d7","msg":"Error in tRPC handler (lambda) on path: file.getFiles, type: query"}
a [TRPCError]: UNAUTHORIZED
    at /app/.next/server/chunks/93519.js:1:1932
    at f (/app/.next/server/chunks/88615.js:4:74)
    at r (/app/.next/server/chunks/88615.js:1:5810)
    at /app/.next/server/chunks/20516.js:1:7781
    at Array.map (<anonymous>)
    at g (/app/.next/server/chunks/20516.js:1:7318)
    at async _ (/app/.next/server/app/(backend)/trpc/lambda/[trpc]/route.js:1:3799)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186) {
  cause: undefined,
  code: 'UNAUTHORIZED'
}
a [TRPCError]: UNAUTHORIZED
    at /app/.next/server/chunks/93519.js:1:1932
    at f (/app/.next/server/chunks/88615.js:4:74)
    at r (/app/.next/server/chunks/88615.js:1:5810)
    at /app/.next/server/chunks/20516.js:1:7781
    at Array.map (<anonymous>)
    at g (/app/.next/server/chunks/20516.js:1:7318)
    at async _ (/app/.next/server/app/(backend)/trpc/lambda/[trpc]/route.js:1:3799)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186) {
  cause: undefined,
  code: 'UNAUTHORIZED'
}
{"level":30,"time":1734161596213,"pid":28,"hostname":"70497f2263d7","msg":"Error in tRPC handler (lambda) on path: knowledgeBase.getKnowledgeBases, type: query"}
embeddingChunks error {
  message: '{"errorType":"InvalidProviderAPIKey"}',
  name: 'EmbeddingError'
}

### 📷 Recurrence Steps

![11111](https://github.com/user-attachments/assets/cc05cc62-f415-4ea8-be92-b3824e3f64e6)

### 🚦 Expected Behavior

请问是什么问题

**Comment by SpeedupMaster** [comment]
`InvalidProviderAPIKey`API Key的问题吧，分块需要使用`text-embedding-3-small`模型
