### ISSUE TITLE
[Bug] 'embedding task is timeout, please try again'

### ISSUE THREAD

**Issue by luojiong** [lobehub/lobe-chat#5050]
### 📦 Environment

Docker

### 📌 Version

v1.34.5

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome

### 🐛 Bug Description

当我创建知识库并进行向量分块的时候 提示我 `TaskTimeout`   向量化失败了

### 📷 Recurrence Steps

1 上传一份25mb 大小的pdf文件 其中包含文字和图片

2  任务执行几分钟后提示 TaskTimeout 错误 

3  我查看服务器得到的日志如下
然后我从服务器端 lobe-chat 应用查看日志得到
```ssh
执行第 1 个任务
执行第 2 个任务
执行第 3 个任务
执行第 4 个任务
执行第 5 个任务
执行第 6 个任务
(node:28) Warning: Label '任务[1]: embeddings' already exists for console.time()
(node:28) Warning: Label '任务[2]: embeddings' already exists for console.time()
(node:28) Warning: Label '任务[3]: embeddings' already exists for console.time()
(node:28) Warning: Label '任务[4]: embeddings' already exists for console.time()
(node:28) Warning: Label '任务[5]: embeddings' already exists for console.time()
(node:28) Warning: Label '任务[6]: embeddings' already exists for console.time()
{"level":30,"time":1734401506672,"pid":28,"hostname":"3540a69b3f10","msg":"Error in tRPC handler (lambda) on path: chunk.createEmbeddingChunksTask, type: mutation"}
a [TRPCError]: Unsupported GET-request to mutation procedure at path "chunk.createEmbeddingChunksTask"
    at /app/.next/server/chunks/40282.js:1:7509
    at Array.map (<anonymous>)
    at g (/app/.next/server/chunks/40282.js:1:7314)
    at async _ (/app/.next/server/app/(backend)/trpc/lambda/[trpc]/route.js:1:3799)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
    at async doRender (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/base-server.js:1359:42)
    at async cacheEntry.responseCache.get.routeKind (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/base-server.js:1581:28)
    at async NextNodeServer.renderToResponseWithComponentsImpl (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.23.6_@opentelemetry+api@1.9.0_@playwright+test@1.49.0_react-d_a02da77f73e71746904bb2e641b54beb/node_modules/next/dist/server/base-server.js:1489:28) {
  cause: undefined,
  code: 'METHOD_NOT_SUPPORTED'
}
embeddingChunks error n {
  name: 'TaskTimeout',
  body: { detail: 'embedding task is timeout, please try again' }
}

 ```

### 🚦 Expected Behavior

期望能成功进行向量分块

**Comment by luojiong** [comment]
我目前使用的docker镜像  可以直接在容器内部改吗

**Comment by luojiong** [comment]
我目前使用的docker镜像 可以直接在容器内部改吗 @dosu

**Comment by luojiong** [comment]
我不清楚为什么会出现这个问题   能否从根源上解决它@dosu

**Comment by luojiong** [comment]
相同的文件 制作自定义知识库 fastGpt 只需要3分钟左右成功创建并引用成功

**Comment by Klearcc** [comment]
在应该如何容器内找到并修改需要的文件，例如 asyncTask.ts

**Comment by Klearcc** [comment]
> 是的，您可以直接在容器内部进行修改。不过，这些更改只会在当前运行的容器中生效，并且在容器停止或删除后会丢失。为了使更改持久化，您可以考虑以下步骤：
> 
> 1. **进入容器**：使用 `docker exec -it <container_id> /bin/bash` 进入容器。
> 2. **修改文件**：在容器内找到并修改需要的文件，例如 `asyncTask.ts`。
> 3. **重新构建镜像**：如果您希望更改在未来的容器中生效，您需要基于修改后的内容重新构建 Docker 镜像。可以通过 `docker commit <container_id> <new_image_name>` 创建一个新的镜像。
> 4. **使用新镜像**：使用新创建的镜像启动新的容器。
> 
> 请注意，直接修改容器内的文件可能会导致与源代码库的版本不一致，因此建议在开发环境中进行测试后再应用到生产环境。
> 
> _To continue talking to [Dosu](https://dosu.dev), mention [@dosu](https://github.com/dosu).要继续与 Dosu 对话，请提及 。_
> 
> Help Dosu learn! Give it feedback: [Great Response](https://app.dosu.dev/response-feedback/094c79ec-bb3b-4449-a838-919c842e0fe7?feedback_type=great_response) | [Irrelevant Answer](https://app.dosu.dev/response-feedback/094c79ec-bb3b-4449-a838-919c842e0fe7?feedback_type=irrelevant_answer) | [Incorrect Sources](https://app.dosu.dev/response-feedback/094c79ec-bb3b-4449-a838-919c842e0fe7?feedback_type=incorrect_sources) | [Too Verbose](https://app.dosu.dev/response-feedback/094c79ec-bb3b-4449-a838-919c842e0fe7?feedback_type=too_verbose) | [Hallucination](https://app.dosu.dev/response-feedback/094c79ec-bb3b-4449-a838-919c842e0fe7?feedback_type=hallucination) | [Other](https://app.dosu.dev/response-feedback/094c79ec-bb3b-4449-a838-919c842e0fe7?feedback_type=other)

在应该如何容器内找到并修改需要的文件，例如 asyncTask.ts

**Comment by Klearcc** [comment]
@dosu 我在应该如何容器内找到并修改需要的文件，例如 asyncTask.ts @dosu

**Comment by Klearcc** [comment]
@dosu 应该选择哪个容器

**Comment by Klearcc** [comment]
@dosu 
并没有对应的路径和文件
─# docker exec -it --user root lobe-chat /bin/sh
/ # ls
app    bin    dev    etc    home   lib    lib64  proc   root   sys    tmp    usr    var
/ # ls -al
total 56
drwxr-xr-x    1 root     root          4096 Feb 13 13:05 .
drwxr-xr-x    1 root     root          4096 Feb 13 13:05 ..
-rwxr-xr-x    1 root     root             0 Feb 13 13:05 .dockerenv
drwxr-xr-x    1 nextjs   nodejs        4096 Feb 13 13:40 app
drwxr-xr-x    2 root     root         12288 Feb 13 05:52 bin
drwxr-xr-x    5 root     root           340 Feb 13 13:36 dev
drwxr-xr-x    1 root     root          4096 Feb 13 13:05 etc
drwxr-xr-x    2 nobody   nobody        4096 Sep 26 21:31 home
drwxr-xr-x    2 root     root          4096 Feb 13 05:52 lib
lrwxrwxrwx    1 root     root             3 Sep 26 21:31 lib64 -> lib
dr-xr-xr-x  212 root     root             0 Feb 13 13:36 proc
drwx------    1 root     root          4096 Feb 13 13:43 root
dr-xr-xr-x   13 root     root             0 Feb 13 13:36 sys
drwxrwxrwt    2 root     root          4096 Sep 26 21:31 tmp
drwxr-xr-x    4 root     root          4096 Sep 26 21:31 usr
drwxr-xr-x    4 root     root          4096 Sep 26 21:31 var

**Comment by luojiong** [comment]
@Klearcc  文件是有 我改了也没用   建议放弃  还会有其他问题。。  选择fastGpt 或者Dify吧
