### ISSUE TITLE
[Bug] logto and database are broken since last X updates

### ISSUE THREAD

**Issue by AbondonedScrawl** [lobehub/lobe-chat#5064]
### 📦 Environment

Docker

### 📌 Version

latest

### 💻 Operating System

Ubuntu

### 🌐 Browser

Chrome, Safari

### 🐛 Bug Description

Since a couple of updates ago, logto stoped working with following error message:

```
> logto db alt deploy
Error: Missing target version
    at getTargetVersion (file:///etc/logto/packages/cli/lib/commands/database/alteration/version.js:42:39)
    at chooseAlterationsByVersion (file:///etc/logto/packages/cli/lib/commands/database/alteration/version.js:58:33)
    at Object.handler (file:///etc/logto/packages/cli/lib/commands/database/alteration/index.js:88:43)
Specify --help for available options
```

Now database is throwing this message aswell:

```
[auth][error] r2: "response" is not a conform Authorization Server Metadata response (unexpected HTTP status code)
    at r5 (/app/.next/server/chunks/43505.js:368:4893)
    at ne (/app/.next/server/chunks/43505.js:368:6924)
    at iB (/app/.next/server/chunks/43505.js:368:46968)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async iG (/app/.next/server/chunks/43505.js:368:49798)
    at async i0 (/app/.next/server/chunks/43505.js:368:52440)
    at async i2 (/app/.next/server/chunks/43505.js:368:56596)
    at async /app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:36932
    at async eC.execute (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:27548)
    at async eC.handle (/app/node_modules/.pnpm/next@14.2.8_@babel+core@7.26.0_@opentelemetry+api@1.9.0_@playwright+test@1.49.1_react-d_1cf2c798572f9d55dae58de467e3f455/node_modules/next/dist/compiled/next-server/app-route.runtime.prod.js:6:38186)
[NextAuth] Error: {
  cause: 'Configuration',
  message: 'Wrong configuration, make sure you have the correct environment variables set. Visit https://lobehub.com/docs/self-hosting/advanced/authentication for more details.',
  name: 'NextAuth Error'
}

```

I ignored this issue as I had active session where I could continue using agents. However, now that I need to login it seems impossible. 

Whew trying to login I get this error:

<img width="1082" alt="Skärmavbild 2024-12-17 kl  19 30 46" src="https://github.com/user-attachments/assets/d966ccdb-88c7-4ce5-8035-f0934e5e3b6f" />

I use this docker compose file: https://raw.githubusercontent.com/lobehub/lobe-chat/HEAD/docker-compose/local/setup.sh

### 📷 Recurrence Steps

Use docker compose example

### 🚦 Expected Behavior

Working authentication, correct configuration of containers

**Comment by SpeedupMaster** [comment]
It seems to be a logto issue. You can try reverting to the version before the update. logto requires a manual database update before each update.

**Comment by fqscfqj** [comment]
“This is caused by the logto update, logto was updated to version 1.20.0 today. There are two solutions:

Continue to use version v1.19.0
Enter the logto container and run the following command to deploy the database changes:
npm run alteration deploy”

Only  keep  the  lobe-postgres  and  lobe-chat  containers  running.  After  restarting  the  lobe-chat  container,  quickly  enter  the  command  line  to  execute  commands  and  switch  the  database.  Remember  to  back  up  the  data  in  advance.
