### ISSUE TITLE
[Bug] WSL2上自建postgresql的无法执行db:migrate: Cannot read properties of undefined (reading 'migrate') 

### ISSUE THREAD

**Issue by xiangnanscu** [lobehub/lobe-chat#5068]
### 📦 部署环境

Other

### 📌 软件版本

Latest

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

注意, postgresql我不是使用的docker或serverless, 我使用ubuntu上直接安装的pg. `.env`文件里面我已经设置好了:
```env
DATABASE_DRIVER=node
NEXT_PUBLIC_SERVICE_MODE=server
```

### 📷 复现步骤

````
root@xnb:~/lobe-chat# bun run db:migrate
$ MIGRATION_DB=1 tsx ./scripts/migrateServerDB/index.ts
❌ Database migrate failed: TypeError: Cannot read properties of undefined (reading 'migrate')
    at migrate (/root/lobe-chat/node_modules/.pnpm/drizzle-orm@0.38.2_@neondatabase+serverless@0.10.4_@opentelemetry+api@1.9.0_@types+pg@8.11.10_5pu7i2tu2hxsw7cluzudcwqn54/node_modules/src/node-postgres/migrator.ts:10:19)
    at runMigrations (/root/lobe-chat/scripts/migrateServerDB/index.ts:17:11)
    at neonMigrate (/root/lobe-chat/scripts/migrateServerDB/index.ts:32:3)
    at Object.<anonymous> (/root/lobe-chat/scripts/migrateServerDB/index.ts:48:1)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.transformer (/root/lobe-chat/node_modules/.pnpm/tsx@4.19.2/node_modules/tsx/dist/register-DCnOAxY2.cjs:2:1186)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at cjsLoader (node:internal/modules/esm/translators:356:17)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:305:7)
------------------------------------------------------------------------------------------
⚠️ Database migrate failed due to not find the db instance.

1) You might not switch to server db mode, please set the env blow and try again:

```
NEXT_PUBLIC_SERVICE_MODE=server
```

2) if you are using docker postgres image, you may need to set DATABASE_DRIVER to node

```
DATABASE_DRIVER=node
```

if you have any other question, please open issue here: https://github.com/lobehub/lobe-chat/issues

error: script "db:migrate" exited with code 1
````

### 🚦 期望结果

不要出错

**Comment by arvinxx** [comment]
下面报错说明都给你写了，有尝试吗？

**Comment by xiangnanscu** [comment]
嗯,不能直接`bun run db:migrate`, 要使用`dotenv -- bun run db:migrate`
