### ISSUE TITLE
[Database Init Error] Aborted(). Build with -sASSERTIONS for more info.

### ISSUE THREAD

**Issue by 619086901** [lobehub/lobe-chat#5186]
```json
{
  "message": "Aborted(). Build with -sASSERTIONS for more info.",
  "name": "RuntimeError",
  "stack": "RuntimeError: Aborted(). Build with -sASSERTIONS for more info.\n    at abort (https://chat-preview.lobehub.com/_next/static/chunks/0871ae57.a5177feddfc2d7a1.js:1:74636)\n    at __abort_js (https://chat-preview.lobehub.com/_next/static/chunks/0871ae57.a5177feddfc2d7a1.js:1:157025)\n    at postgres.wasm.abort (wasm://wasm/postgres.wasm-02840556:wasm-function[14924]:0x6d6d64)\n    at postgres.wasm.ExceptionalCondition (wasm://wasm/postgres.wasm-02840556:wasm-function[12846]:0x5f0dcc)\n    at postgres.wasm.pg_re_throw (wasm://wasm/postgres.wasm-02840556:wasm-function[12791]:0x5eb5ae)\n    at invoke_v (https://chat-preview.lobehub.com/_next/static/chunks/0871ae57.a5177feddfc2d7a1.js:2:228442)\n    at postgres.wasm.PortalRun (wasm://wasm/postgres.wasm-02840556:wasm-function[7212]:0x3eca58)\n    at postgres.wasm.exec_simple_query (wasm://wasm/postgres.wasm-02840556:wasm-function[7297]:0x3ff710)\n    at postgres.wasm.interactive_file (wasm://wasm/postgres.wasm-02840556:wasm-function[7294]:0x3f8f3f)\n    at postgres.wasm.RePostgresSingleUserMain (wasm://wasm/postgres.wasm-02840556:wasm-function[7293]:0x3f8c19)\n    at postgres.wasm.pg_initdb (wasm://wasm/postgres.wasm-02840556:wasm-function[4958]:0x25633a)\n    at Object.Module._pg_initdb (https://chat-preview.lobehub.com/_next/static/chunks/0871ae57.a5177feddfc2d7a1.js:2:112385)\n    at t.rC (https://chat-preview.lobehub.com/_next/static/chunks/65865.1b874f6496f36293.js:8:14904)\n    at async t._checkReady (https://chat-preview.lobehub.com/_next/static/chunks/65865.1b874f6496f36293.js:8:10044)\n    at async t.query (https://chat-preview.lobehub.com/_next/static/chunks/65865.1b874f6496f36293.js:8:179)\n    at async z.migrate (https://chat-preview.lobehub.com/_next/static/chunks/31030.41eb6197e9e464b5.js:7:5)\n    at async q.migrate (https://chat-preview.lobehub.com/_next/static/chunks/87299-0694b2923929a3f7.js:1:59057)\n    at async https://chat-preview.lobehub.com/_next/static/chunks/87299-0694b2923929a3f7.js:1:59867\n    at async Object.initializeClientDB (https://chat-preview.lobehub.com/_next/static/chunks/app/layout-d7a4868f945f5a8a.js:1:48078)\n    at async https://chat-preview.lobehub.com/_next/static/chunks/94712-533713ef4a413e4d.js:1:9248"
}
```

**Comment by arvinxx** [comment]
@619086901 what's your browser version?
