### ISSUE TITLE
[Bug] 无法构建：Error: Configuring Next.js via 'next.config.ts' is not supported. Please replace the file with 'next.config.js' or 'next.config.mjs'.

### ISSUE THREAD

**Issue by xiangnanscu** [lobehub/lobe-chat#5204]
### 📦 部署环境

Other

### 📌 软件版本

Latest

### 💻 系统环境

Ubuntu

### 🌐 浏览器

Chrome

### 🐛 问题描述

@xiangnanscu ➜ /workspaces/lobe-chat (main) $ bun run build
$ next build

> Build error occurred
Error: Configuring Next.js via 'next.config.ts' is not supported. Please replace the file with 'next.config.js' or 'next.config.mjs'.
    at loadConfig (/workspaces/lobe-chat/node_modules/next/dist/server/config.js:787:19)
    at async Span.traceAsyncFn (/workspaces/lobe-chat/node_modules/next/dist/trace/trace.js:154:20)
    at async /workspaces/lobe-chat/node_modules/next/dist/build/index.js:358:28
    at async Span.traceAsyncFn (/workspaces/lobe-chat/node_modules/next/dist/trace/trace.js:154:20)
    at async build (/workspaces/lobe-chat/node_modules/next/dist/build/index.js:352:9)

### 📷 复现步骤

执行`bun run build`就出错

### 🚦 期望结果

不要出错

**Comment by arvinxx** [comment]
重装依赖
