### ISSUE TITLE
[Bug] The weather plugin cannot work without any error message

### ISSUE THREAD

**Issue by skyf0cker** [lobehub/lobe-chat#522]
### 💻 系统环境 | Operating System

macOS

### 🌐 浏览器 | Browser

Chrome

### 🐛 问题描述 | Bug Description

<img width="585" alt="image" src="https://github.com/lobehub/lobe-chat/assets/32331521/5bda414b-605a-41ec-aaa1-f824b289855c">

**Comment by mushan0x0** [comment]
0.105.2 版本未复现该问题

<img width="1324" alt="image" src="https://github.com/lobehub/lobe-chat/assets/29084441/577f555a-f3d5-4d5b-ad66-5071fcb99934">

**Comment by skyf0cker** [comment]
<img width="522" alt="image" src="https://github.com/lobehub/lobe-chat/assets/32331521/ab9ca177-5f5b-41a4-8d55-b0a758d83a15">
It looks like that the request to plugin return 405 error.

I use the self-hosted lobechat on vercel, it is the latest version
<img width="753" alt="image" src="https://github.com/lobehub/lobe-chat/assets/32331521/f931b006-ff82-476b-9b6d-33005b1d1de8">

**Comment by arvinxx** [comment]
> at the request to plugin return 405 error.

Please check the error on vercel log, and show me

**Comment by skyf0cker** [comment]
> > at the request to plugin return 405 error.
> 
> Please check the error on vercel log, and show me

<img width="379" alt="image" src="https://github.com/lobehub/lobe-chat/assets/32331521/f1f6c85e-93e5-4ec4-8a9c-40fbd73f3612">


>
TypeError: Can't modify immutable headers.
    at (node_modules/@lobehub/chat-plugins-gateway/dist/cors.js:79:14)
    at (node_modules/@lobehub/chat-plugins-gateway/dist/cors.js:84:4)
    at (node_modules/@lobehub/chat-plugins-gateway/dist/cors.js:83:16)

**Comment by arvinxx** [comment]
能方便看下安装的 `@lobehub/chat-plugins-gateway` 这个版本么？

**Comment by arvinxx** [comment]
> not familiar with vercel, can you help to tell me where can i get the installed version of this package

which package manager do you use? if you are using bun or pnpm, when your build project, it will show like this:

<img width="1450" alt="image" src="https://github.com/lobehub/lobe-chat/assets/28616219/e3da76fc-1204-4794-bb1d-6d473fe35863">

**Comment by skyf0cker** [comment]
> > not familiar with vercel, can you help to tell me where can i get the installed version of this package
> 
> which package manager do you use? if you are using bun or pnpm, when you build the project, it will show like this:
> 
> <img alt="image" width="1450" src="https://private-user-images.githubusercontent.com/28616219/286796373-e3da76fc-1204-4794-bb1d-6d473fe35863.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDEzMTEyNTEsIm5iZiI6MTcwMTMxMDk1MSwicGF0aCI6Ii8yODYxNjIxOS8yODY3OTYzNzMtZTNkYTc2ZmMtMTIwNC00Nzk0LWJiMWQtNmQ0NzNmZTM1ODYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzExMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMTMwVDAyMjIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRmYTE4ZTk2ZGNiN2Y4NDljNzJhNTRiNzU0ZGMzYmFjZDE1MmZmYTJmOTRkZjliZWM2ZDgzZTI3Njc4ZGZjOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mxFGzpcHNgAW7-JGS1-hlwhwYau-r10PGKAWY51_mcQ">

<img width="706" alt="image" src="https://github.com/lobehub/lobe-chat/assets/32331521/f4ca1cdc-2240-47d6-86f2-7f7e6a876b9b">
it's 1.5.3

**Comment by arvinxx** [comment]
我也能复现了，等下看下什么问题
