### ISSUE TITLE
[Bug] v1.41.0 更新後如果已經是登入狀態，再點選登出就會卡在"用戶狀態初始化"

### ISSUE THREAD

**Issue by Sen-CaPoo** [lobehub/lobe-chat#5221]
### 📦 Environment

Docker

### 📌 Version

v1.41.0

### 💻 Operating System

Windows

### 🌐 Browser

Chrome

### 🐛 Bug Description

v1.41.0 更新後如果已經是登入狀態，再點選登出就會卡在應用剛開啟時的讀取畫面"用戶狀態初始化..."，重開依然如此，刪除 cookie 後依然無法打開。

**Comment by arvinxx** [comment]
我测试下来是正常的呀？能否给出更加具体的复现情况？例如是怎么部署的，最好能有录屏看下

**Comment by Sen-CaPoo** [comment]
> 我测试下来是正常的呀？能否给出更加具体的复现情况？例如是怎么部署的，最好能有录屏看下

目前退回上一版 v1.3x 正常
重現方法：在 1.3x 版本使用 Docker + Clerk 並且正常登入 > 更新到 1.4x 版本在進行登出(此時就會進入卡住狀態)

URL "https://xxx/" 就會卡住，但手動補上 https://xxx/chat 就可以正常進入，但是只要刪除掉 /chat 就不會自動跳轉。

使用 Docker + Clerk 認證方式，沒有啟用 Pglite Client DB 功能，畫面停留在新版的啟動畫面［用戶狀態初始化...］，不論刪除 cookie 或 Ctrl+F5 重新整理都相同狀況。

Chrome 瀏覽器的 DevTools Console 出現以下訊息:

警告:clerk.browser.js:12 Clerk: Clerk has been loaded with development keys. Development instances have strict usage limits and should not be used when deploying your application to production. Learn more: https://clerk.com/docs/deployments/overview

錯誤:5ea94cf1-d4d8dddaa4971af6.js:1 Uncaught Error: Minified React error #418; visit https://react.dev/errors/418?args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at rv (5ea94cf1-d4d8dddaa4971af6.js:1:30576)
    at 5ea94cf1-d4d8dddaa4971af6.js:1:117133
    at uf (5ea94cf1-d4d8dddaa4971af6.js:1:119861)
    at uu (5ea94cf1-d4d8dddaa4971af6.js:1:112257)
    at 5ea94cf1-d4d8dddaa4971af6.js:1:108295
    at 5ea94cf1-d4d8dddaa4971af6.js:1:108302
    at i8 (5ea94cf1-d4d8dddaa4971af6.js:1:108399)
    at uD (5ea94cf1-d4d8dddaa4971af6.js:1:129037)
    at MessagePort.T (19080-0089b75bb1cb1421.js:1:128713)

警告: Chrome is moving towards a new experience that allows users to choose to browse without third-party cookies.ultimate-bird-48.clerk.accounts.dev/v1/client?__clerk_api_version=2024-10-01&_clerk_js_version=5.43.2&__clerk_db_jwt=dvb_2qt5Tu3iHfOfvtutUQdid2ajDN5:1

**Comment by arvinxx** [comment]
是使用client db + auth 的方式？

**Comment by Sen-CaPoo** [comment]
> 是使用client db + auth 的方式？

是的。

**Comment by arvinxx** [comment]
@Sen-CaPoo 建议切换到 server db + auth 哈。 Client db + auth 的方式目前已经不准备维护了，现在我们部署模式类型分支有点多，我们暂时没有精力能确保所有类型都能稳定。未来的部署方式 (LobeChat 2.0) 就只会收敛到两种：
1. 基于 Pglite 的浏览器版本，不需要 auth，配置了auth 但不配 db 会强抛错。
2. 基于 postgres 的服务端版本，需要完整auth、s3 和 db。

之前这个方案能用其实是 bug as feature ，那个 bug 修掉以后这个不 work 了其实算是正常的。

**Comment by Sen-CaPoo** [comment]
> @Sen-CaPoo 建议切换到 server db + auth 哈。 Client db + auth 的方式目前已经不准备维护了，现在我们部署模式类型分支有点多，我们暂时没有精力能确保所有类型都能稳定。未来的部署方式 (LobeChat 2.0) 就只会收敛到两种：
> 
> 1. 基于 Pglite 的浏览器版本，不需要 auth，配置了auth 但不配 db 会强抛错。
> 2. 基于 postgres 的服务端版本，需要完整auth、s3 和 db。
> 
> 之前这个方案能用算是 bug as feature ，那个 bug 修掉以后这个不 work 了其实算是正常的。

理解，目前先採用應急手段就是手動將網址導向 /chat 順利使用，主要原因為我這邊是教學單位，同學們沒辦法保證都能備份好數據進行遷移 Pglite。

另外就是 postgres 在部屬上有些困難，還無法順利進行。

還是感謝 @arvinxx 與其他開發者的努力與貢獻，這個項目非常的棒。

**Comment by arvinxx** [comment]
> 理解，目前先採用應急手段就是手動將網址導向 /chat 順利使用，主要原因為我這邊是教學單位，同學們沒辦法保證都能備份好數據進行遷移 Pglite。

嗯嗯了解，我们升级 2.0 大版本的时候会做好这个数据的自动迁移，届时直接切换 pglite 应该不会有太大的问题。

另外就是建议提前测试下 pglite 的方案下在你们的应用场景下是否会存在预期外的问题。这样可以尽早和我们反馈，看看有没有解法。

> 另外就是 postgres 在部屬上有些困難，還無法順利進行。

这块具体的问题是什么？是文档哪方面写的不够详细吗
