### ISSUE TITLE
能否提供PROXY_URL 配置

### ISSUE THREAD

**Issue by zt199510** [lobehub/lobe-chat#985]
### 🥰 需求描述

当前的OPENAI_PROXY_URL 可能需要自己去部署一个代理服务，感觉有点多余  ，直接提供PROXY_URL会更方便一点

### 🧐 解决方案

直接提供PROXY_URL 配置  

### 📝 补充信息

无

**Comment by TonyBlur** [comment]
这个在设置里有啊![Screenshot_2024-01-14-12-08-53-625_com.microsoft.emmx-edit.jpg](https://github.com/lobehub/lobe-chat/assets/101348912/d884a89c-b568-45c3-80fb-f0c181bebee2)

**Comment by zt199510** [comment]
> 这个在设置里有啊![Screenshot_2024-01-14-12-08-53-625_com.microsoft.emmx-edit.jpg](https://private-user-images.githubusercontent.com/101348912/296529251-d884a89c-b568-45c3-80fb-f0c181bebee2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTk2MTQsIm5iZiI6MTcwNTIxOTMxNCwicGF0aCI6Ii8xMDEzNDg5MTIvMjk2NTI5MjUxLWQ4ODRhODljLWI1NjgtNDVjMy04MGZiLWYwYzE4MWJlYmVlMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwODAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTkyZTE4MDkwNjc2NTU4MGFkM2YwNmEzNDYzYjM4OGYzMmIwYzI3OWI0ZWQzMWQ2NTY3ZWIyMjVhYTQ5OGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3ETB1ksBUFqTD62f-kqw2Nb572No77ivzeQxUHWsTrI)

这个需要你自己再去部署一个代理服务器 然后填写地址  直接使用Proxy_URL  就不需要

**Comment by TonyBlur** [comment]
> > 这个在设置里有啊![Screenshot_2024-01-14-12-08-53-625_com.microsoft.emmx-edit.jpg](https://private-user-images.githubusercontent.com/101348912/296529251-d884a89c-b568-45c3-80fb-f0c181bebee2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTk2MTQsIm5iZiI6MTcwNTIxOTMxNCwicGF0aCI6Ii8xMDEzNDg5MTIvMjk2NTI5MjUxLWQ4ODRhODljLWI1NjgtNDVjMy04MGZiLWYwYzE4MWJlYmVlMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwODAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTkyZTE4MDkwNjc2NTU4MGFkM2YwNmEzNDYzYjM4OGYzMmIwYzI3OWI0ZWQzMWQ2NTY3ZWIyMjVhYTQ5OGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3ETB1ksBUFqTD62f-kqw2Nb572No77ivzeQxUHWsTrI)
> 
> 这个需要你自己再去部署一个代理服务器 然后填写地址  直接使用Proxy_URL  就不需要

不用自己部署啊，你直接在这里输入代理API的地址和key就能用

**Comment by piwawa** [comment]
> > > 这个在设置里有啊![Screenshot_2024-01-14-12-08-53-625_com.microsoft.emmx-edit.jpg](https://private-user-images.githubusercontent.com/101348912/296529251-d884a89c-b568-45c3-80fb-f0c181bebee2.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMTk2MTQsIm5iZiI6MTcwNTIxOTMxNCwicGF0aCI6Ii8xMDEzNDg5MTIvMjk2NTI5MjUxLWQ4ODRhODljLWI1NjgtNDVjMy04MGZiLWYwYzE4MWJlYmVlMi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTE0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExNFQwODAxNTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZTkyZTE4MDkwNjc2NTU4MGFkM2YwNmEzNDYzYjM4OGYzMmIwYzI3OWI0ZWQzMWQ2NTY3ZWIyMjVhYTQ5OGM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.3ETB1ksBUFqTD62f-kqw2Nb572No77ivzeQxUHWsTrI)
> > 
> > 
> > 这个需要你自己再去部署一个代理服务器 然后填写地址  直接使用Proxy_URL  就不需要
> 
> 不用自己部署啊，你直接在这里输入代理API的地址和key就能用

他要的是走本地代理，就是翻墙，比如 v2ray 的10809端口

**Comment by zhuozhiyongde** [comment]
参见 https://github.com/lobehub/lobe-chat/issues/524

你可以使用上述问题中提到的 Vercel 透明代理来解决这个问题。

**Comment by arvinxx** [comment]
这次在做多 Provider 方案时，发现 proxy 是必须的。

因此会支持上 `HTTP_PROXY_URL` 环境变量来提供本地代理。

**Comment by piwawa** [comment]
> 这次在做多 Provider 方案时，发现 proxy 是必须的 （Google Gemini 的 sdk 不支持 baseURL）
> 
> 因此会支持上 `HTTP_PROXY_URL` 环境变量来提供本地代理：#1173

这个 `env` 是不是现在还没加上？

**Comment by arvinxx** [comment]
@piwawa 对，功能其实实现了，但是没实装： https://github.com/lobehub/lobe-chat/blob/main/src/app/api/chat/google/route.ts#L3-L14

原因是这个配置只能在 Node 环境下跑，一旦开启以后就没法切到 Edge Runtime 了，这会导致vercel 部署的体验受到很大的影响

**Comment by piwawa** [comment]
> @piwawa 对，功能其实实现了，但是没实装： https://github.com/lobehub/lobe-chat/blob/main/src/app/api/chat/google/route.ts#L3-L14
> 
> 原因是这个配置只能在 Node 环境下跑，一旦开启以后就没法切到 Edge Runtime 了，这会导致vercel 部署的体验受到很大的影响。 cc @coulsontl @shorexilin @zhuozhiyongde


更新之后一直没法调用api，我这个api是`oneapi`部署的，用chatgpt-next-web和本地调用 (不翻墙) 都没问题，就这个lobe不行，加 `/v1` 和不加都报错，能看下问题原因吗？

![image](https://github.com/lobehub/lobe-chat/assets/46926496/b0d69adc-13d6-4298-acdf-e9f9f0e25d54)
![image](https://github.com/lobehub/lobe-chat/assets/46926496/510f77d2-39de-4a16-b892-3a3b068d456a)

```
 ⨯ Error: fetch failed
    at context.fetch (/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/context.js:272:38)
    at r (/app/.next/server/edge-chunks/699.js:5589:76)
    at doOriginalFetch (/app/.next/server/edge-chunks/699.js:8034:24)
    at /app/.next/server/edge-chunks/699.js:8159:20
    at /app/.next/server/edge-chunks/699.js:8409:36
    at NoopContextManager.with (/app/.next/server/edge-chunks/699.js:732:30)
    at ContextAPI.with (/app/.next/server/edge-chunks/699.js:402:58)
    at NoopTracer.startActiveSpan (/app/.next/server/edge-chunks/699.js:1325:34)
    at ProxyTracer.startActiveSpan (/app/.next/server/edge-chunks/699.js:1365:36)
    at /app/.next/server/edge-chunks/699.js:8398:103 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9145:28)
      at eval (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9101:50)
      at Immediate.eval [as _onImmediate] (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9133:13)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
 ⨯ Error: fetch failed
    at context.fetch (/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/server/web/sandbox/context.js:272:38)
    at r (/app/.next/server/edge-chunks/699.js:5589:76)
    at doOriginalFetch (/app/.next/server/edge-chunks/699.js:8034:24)
    at /app/.next/server/edge-chunks/699.js:8159:20
    at /app/.next/server/edge-chunks/699.js:8409:36
    at NoopContextManager.with (/app/.next/server/edge-chunks/699.js:732:30)
    at ContextAPI.with (/app/.next/server/edge-chunks/699.js:402:58)
    at NoopTracer.startActiveSpan (/app/.next/server/edge-chunks/699.js:1325:34)
    at ProxyTracer.startActiveSpan (/app/.next/server/edge-chunks/699.js:1365:36)
    at /app/.next/server/edge-chunks/699.js:8398:103 {
  cause: ConnectTimeoutError: Connect Timeout Error
      at onConnectTimeout (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9145:28)
      at eval (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9101:50)
      at Immediate.eval [as _onImmediate] (eval at requireWithFakeGlobalScope (/app/node_modules/.pnpm/next@14.1.1_@babel+core@7.23.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/compiled/edge-runtime/index.js:1:657096), <anonymous>:9133:13)
      at process.processImmediate (node:internal/timers:478:21)
      at process.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'UND_ERR_CONNECT_TIMEOUT'
  }
}
```

**Comment by arvinxx** [comment]
@piwawa 你 Discord 上私戳我帮你看看

**Comment by coulsontl** [comment]
> @piwawa 对，功能其实实现了，但是没实装： https://github.com/lobehub/lobe-chat/blob/main/src/app/api/chat/google/route.ts#L3-L14
> 
> 原因是这个配置只能在 Node 环境下跑，一旦开启以后就没法切到 Edge Runtime 了，这会导致vercel 部署的体验受到很大的影响。 cc @coulsontl @shorexilin @zhuozhiyongde

@arvinxx 能否在打包的时候，根据渠道来决定是不是要打开这段代码？

**Comment by CXwudi** [comment]
既然lobe-chat是个纯前端应用，那是不是不管什么部署方式，只要浏览器翻出去了就行，而这只需要打开系统代理即可

**Comment by coulsontl** [comment]
> Can you decide whether to open this code based on the channel when packaging?

纯前端应用是指你在本地自定义了API地址的时候才是；走默认API的话不是纯前端应用，比如Docker部署的方式，我在聊天时实际上是去请求我部署Docker的服务端，然后服务器再调用OpenAI进行对话

**Comment by Arbitraryfate** [comment]
请问PROXY_URL是否支持ipv6网址？
